import React from 'react';
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { act, render, screen, fireEvent, waitFor } from '@testing-library/react';
import { CssVarsProvider, extendTheme } from '@mui/joy/styles';
import { getThemeConfig } from '@client/app/utils/themes';
import type { FallbackInfo } from '@bike4mind/common';

vi.mock('@client/app/contexts/WebsocketContext', () => ({
  useWebsocket: () => ({ subscribeToAction: vi.fn(() => vi.fn()) }),
}));

import FallbackModelBadge from './FallbackModelBadge';

const appTheme = extendTheme({ ...getThemeConfig() });
const TestWrapper = ({ children }: { children: React.ReactNode }) => (
  <CssVarsProvider theme={appTheme}>{children}</CssVarsProvider>
);

const SESSION_ID = 'session-1';

function seedFallback(overrides: Partial<FallbackInfo> = {}): void {
  const info: FallbackInfo = {
    sessionId: SESSION_ID,
    // Cross-path twins: identical display names, different provider paths (the case the
    // provider-path annotation exists to disambiguate).
    primaryModel: 'global.anthropic.claude-opus-4-8',
    primaryModelName: 'Claude 4.8 Opus',
    fallbackModel: 'claude-opus-4-8',
    fallbackModelName: 'Claude 4.8 Opus',
    timestamp: Date.now(),
    ...overrides,
  };
  localStorage.setItem('lastFallbackInfo', JSON.stringify(info));
}

const FIVE_MINUTES = 5 * 60 * 1000;

describe('FallbackModelBadge', () => {
  beforeEach(() => {
    localStorage.clear();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('renders the badge and disambiguates identically-named twins by provider path in the tooltip', async () => {
    seedFallback();
    render(
      <TestWrapper>
        <FallbackModelBadge sessionId={SESSION_ID} />
      </TestWrapper>
    );

    const chip = await screen.findByTestId('fallback-model-badge-chip');
    fireEvent.mouseOver(chip);

    const tooltip = await screen.findByText(
      'Claude 4.8 Opus (Bedrock) was unavailable, response generated by Claude 4.8 Opus (Anthropic direct). Click to dismiss.'
    );
    expect(tooltip).toBeInTheDocument();
  });

  it('names the fallback model on the chip itself, without needing hover', async () => {
    seedFallback({ fallbackModelName: 'GPT-5' });
    render(
      <TestWrapper>
        <FallbackModelBadge sessionId={SESSION_ID} />
      </TestWrapper>
    );

    const chip = await screen.findByTestId('fallback-model-badge-chip');
    expect(chip).toHaveTextContent('Fallback: GPT-5');
  });

  // The two ways the badge used to vanish on its own, which is what made a fallback easy to miss.
  it('still renders a fallback older than the former five-minute recency window', async () => {
    seedFallback({ timestamp: Date.now() - 10 * FIVE_MINUTES });
    render(
      <TestWrapper>
        <FallbackModelBadge sessionId={SESSION_ID} />
      </TestWrapper>
    );

    expect(await screen.findByTestId('fallback-model-badge-chip')).toBeInTheDocument();
  });

  it('does not auto-dismiss once five minutes elapse while mounted', () => {
    vi.useFakeTimers();
    seedFallback();
    render(
      <TestWrapper>
        <FallbackModelBadge sessionId={SESSION_ID} />
      </TestWrapper>
    );

    // Flush the 100ms state debounce, then run well past the old auto-dismiss deadline.
    act(() => {
      vi.advanceTimersByTime(100);
    });
    expect(screen.getByTestId('fallback-model-badge-chip')).toBeInTheDocument();

    act(() => {
      vi.advanceTimersByTime(FIVE_MINUTES + 1000);
    });
    expect(screen.getByTestId('fallback-model-badge-chip')).toBeInTheDocument();
  });

  it('clears the badge and the stored fallback when dismissed', async () => {
    seedFallback();
    render(
      <TestWrapper>
        <FallbackModelBadge sessionId={SESSION_ID} />
      </TestWrapper>
    );

    // Joy hangs the Chip's onClick on an inner MuiChip-action button (it covers the chip in a
    // real browser); data-testid is on the non-interactive root, so clicking that does nothing.
    await screen.findByTestId('fallback-model-badge-chip');
    fireEvent.click(screen.getByRole('button'));

    await waitFor(() => {
      expect(screen.queryByTestId('fallback-model-badge-chip')).not.toBeInTheDocument();
    });
    expect(localStorage.getItem('lastFallbackInfo')).toBeNull();
  });

  it('does not render when the stored fallback belongs to a different session', async () => {
    seedFallback({ sessionId: 'other-session' });
    render(
      <TestWrapper>
        <FallbackModelBadge sessionId={SESSION_ID} />
      </TestWrapper>
    );

    await waitFor(() => {
      expect(screen.queryByTestId('fallback-model-badge-chip')).not.toBeInTheDocument();
    });
  });
});
