import { ModelBackend, type FallbackInfo } from '@bike4mind/common';

// Bedrock-hosted model ids carry a region scope (us./eu./apac./global.) or a bare vendor-dot
// prefix; direct-provider ids are bare slugs (e.g. claude-opus-4-8, gpt-5). Keep in sync with
// the id conventions in b4m-core/common/src/models.ts.
const BEDROCK_ID_PREFIXES = [
  'us.',
  'eu.',
  'apac.',
  'global.',
  'anthropic.',
  'amazon.',
  'meta.',
  'ai21.',
  'cohere.',
  'deepseek.',
  'mistral.',
  'stability.',
  // Both spellings: AWS ships Kimi K2.5 as `moonshotai.` and K2 Thinking as
  // `moonshot.` on bedrock-runtime.
  'moonshot.',
  'moonshotai.',
];

/**
 * Human-readable provider path for a model id, used to disambiguate cross-path fallbacks where
 * the two twins share a display name (e.g. Bedrock and Anthropic-direct Claude both render as
 * "Claude 4.8 Opus"). Returns undefined when no label can be derived, so the annotation is omitted.
 *
 * `backend` wins over every id heuristic below when it is known, the same precedence
 * ModelSelection's getModelBackend applies: an Ollama pull is named `deepseek-r1:latest` or
 * `llama3.3`, which the vendor prefixes here would otherwise claim for the direct API. Absent
 * on a FallbackInfo written by an older build, in which case the id is all there is.
 */
export function getModelProviderLabel(modelId: string | undefined, backend?: string): string | undefined {
  if (!modelId) return undefined;
  const id = modelId.toLowerCase();

  if (backend === ModelBackend.Ollama) return 'Ollama';
  if (BEDROCK_ID_PREFIXES.some(prefix => id.startsWith(prefix))) return 'Bedrock';
  if (id.startsWith('claude')) return 'Anthropic direct';
  if (id.startsWith('gpt') || id.startsWith('chatgpt') || /^o\d/.test(id)) return 'OpenAI';
  if (id.startsWith('gemini')) return 'Google';
  if (id.startsWith('grok')) return 'xAI';
  // Direct Moonshot ids are bare `kimi-*`; the `moonshot*.` prefixed forms are
  // Bedrock-hosted and already caught above.
  if (id.startsWith('kimi')) return 'Moonshot direct';
  // Bare (non-Bedrock) ids for other direct providers. The `<vendor>.` prefixed forms are
  // Bedrock-hosted and already caught above; these dash-slug forms are the direct APIs.
  if (id.startsWith('deepseek')) return 'DeepSeek';
  if (id.startsWith('mistral') || id.startsWith('mixtral') || id.startsWith('ministral')) return 'Mistral';
  if (id.startsWith('command') || id.startsWith('cohere')) return 'Cohere';
  return undefined;
}

function withProvider(name: string, modelId: string | undefined, backend?: string): string {
  const provider = getModelProviderLabel(modelId, backend);
  return provider ? `${name} (${provider})` : name;
}

/**
 * Compose the fallback badge tooltip, annotating each model with its provider path so a
 * cross-path fallback between identically-named twins reads clearly, e.g.
 * "Claude 4.8 Opus (Bedrock) was unavailable, response generated by Claude 4.8 Opus (Anthropic direct)".
 */
export function formatFallbackTooltip(fallbackInfo: FallbackInfo): string {
  const primary = withProvider(
    fallbackInfo.primaryModelName,
    fallbackInfo.primaryModel,
    fallbackInfo.primaryModelBackend
  );
  const fallback = withProvider(
    fallbackInfo.fallbackModelName,
    fallbackInfo.fallbackModel,
    fallbackInfo.fallbackModelBackend
  );
  return `${primary} was unavailable, response generated by ${fallback}`;
}
