import type { FallbackInfo } from '@bike4mind/common';

// Bedrock-hosted model ids carry a region scope (us./eu./apac./global.) or a bare vendor-dot
// prefix; direct-provider ids are bare slugs (e.g. claude-opus-4-8, gpt-5). Keep in sync with
// the id conventions in b4m-core/common/src/models.ts.
const BEDROCK_ID_PREFIXES = [
  'us.',
  'eu.',
  'apac.',
  'global.',
  'anthropic.',
  'amazon.',
  'meta.',
  'ai21.',
  'cohere.',
  'deepseek.',
  'mistral.',
  'stability.',
];

/**
 * Human-readable provider path for a model id, used to disambiguate cross-path fallbacks where
 * the two twins share a display name (e.g. Bedrock and Anthropic-direct Claude both render as
 * "Claude 4.8 Opus"). Returns undefined when no label can be derived, so the annotation is omitted.
 */
export function getModelProviderLabel(modelId: string | undefined): string | undefined {
  if (!modelId) return undefined;
  const id = modelId.toLowerCase();

  if (BEDROCK_ID_PREFIXES.some(prefix => id.startsWith(prefix))) return 'Bedrock';
  if (id.startsWith('claude')) return 'Anthropic direct';
  if (id.startsWith('gpt') || id.startsWith('chatgpt') || /^o\d/.test(id)) return 'OpenAI';
  if (id.startsWith('gemini')) return 'Google';
  if (id.startsWith('grok')) return 'xAI';
  return undefined;
}

function withProvider(name: string, modelId: string | undefined): string {
  const provider = getModelProviderLabel(modelId);
  return provider ? `${name} (${provider})` : name;
}

/**
 * Compose the fallback badge tooltip, annotating each model with its provider path so a
 * cross-path fallback between identically-named twins reads clearly, e.g.
 * "Claude 4.8 Opus (Bedrock) was unavailable, response generated by Claude 4.8 Opus (Anthropic direct)".
 */
export function formatFallbackTooltip(fallbackInfo: FallbackInfo): string {
  const primary = withProvider(fallbackInfo.primaryModelName, fallbackInfo.primaryModel);
  const fallback = withProvider(fallbackInfo.fallbackModelName, fallbackInfo.fallbackModel);
  return `${primary} was unavailable, response generated by ${fallback}`;
}
