import { describe, it, expect } from 'vitest';
import type { FallbackInfo } from '@bike4mind/common';
import { getModelProviderLabel, formatFallbackTooltip } from './fallbackProviderLabel';

describe('getModelProviderLabel', () => {
  it.each([
    ['global.anthropic.claude-opus-4-8', 'Bedrock'],
    ['us.anthropic.claude-haiku-4-5-20251001-v1:0', 'Bedrock'],
    ['anthropic.claude-3-haiku-20240307-v1:0', 'Bedrock'],
    ['us.meta.llama4-v1:0', 'Bedrock'],
    ['amazon.titan-text-v1', 'Bedrock'],
    ['claude-opus-4-8', 'Anthropic direct'],
    ['claude-sonnet-5', 'Anthropic direct'],
    ['gpt-5', 'OpenAI'],
    ['gpt-4o-mini', 'OpenAI'],
    ['o1-preview', 'OpenAI'],
    ['gemini-2.5-pro-preview-05-06', 'Google'],
    ['grok-2', 'xAI'],
    ['deepseek-chat', 'DeepSeek'],
    ['us.deepseek.r1-v1:0', 'Bedrock'], // Bedrock-hosted DeepSeek: region prefix wins
    ['mistral-large-latest', 'Mistral'],
    ['command-r-plus', 'Cohere'],
  ])('maps %s -> %s', (id, expected) => {
    expect(getModelProviderLabel(id)).toBe(expected);
  });

  it('returns undefined for an unknown id or empty input', () => {
    expect(getModelProviderLabel('some-unknown-model')).toBeUndefined();
    expect(getModelProviderLabel('')).toBeUndefined();
    expect(getModelProviderLabel(undefined)).toBeUndefined();
  });
});

describe('formatFallbackTooltip', () => {
  const base = { sessionId: 's1', timestamp: 0 };

  it('disambiguates identically-named twins by provider path (the core case)', () => {
    const info: FallbackInfo = {
      ...base,
      primaryModel: 'global.anthropic.claude-opus-4-8',
      primaryModelName: 'Claude 4.8 Opus',
      fallbackModel: 'claude-opus-4-8',
      fallbackModelName: 'Claude 4.8 Opus',
    };
    expect(formatFallbackTooltip(info)).toBe(
      'Claude 4.8 Opus (Bedrock) was unavailable, response generated by Claude 4.8 Opus (Anthropic direct)'
    );
  });

  it('annotates a cross-provider fallback', () => {
    const info: FallbackInfo = {
      ...base,
      primaryModel: 'global.anthropic.claude-opus-4-8',
      primaryModelName: 'Claude 4.8 Opus',
      fallbackModel: 'gpt-5',
      fallbackModelName: 'GPT-5',
    };
    expect(formatFallbackTooltip(info)).toBe(
      'Claude 4.8 Opus (Bedrock) was unavailable, response generated by GPT-5 (OpenAI)'
    );
  });

  it('omits the parenthetical when a provider cannot be derived', () => {
    const info: FallbackInfo = {
      ...base,
      primaryModel: 'mystery-model',
      primaryModelName: 'Mystery',
      fallbackModel: 'gpt-5',
      fallbackModelName: 'GPT-5',
    };
    expect(formatFallbackTooltip(info)).toBe('Mystery was unavailable, response generated by GPT-5 (OpenAI)');
  });
});
