import React from 'react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { CssVarsProvider, extendTheme } from '@mui/joy/styles';
import { getThemeConfig } from '@client/app/utils/themes';
import type { FallbackInfo } from '@bike4mind/common';

vi.mock('@client/app/contexts/WebsocketContext', () => ({
  useWebsocket: () => ({ subscribeToAction: vi.fn(() => vi.fn()) }),
}));

import FallbackModelBadge from './FallbackModelBadge';

const appTheme = extendTheme({ ...getThemeConfig() });
const TestWrapper = ({ children }: { children: React.ReactNode }) => (
  <CssVarsProvider theme={appTheme}>{children}</CssVarsProvider>
);

const SESSION_ID = 'session-1';

function seedFallback(overrides: Partial<FallbackInfo> = {}): void {
  const info: FallbackInfo = {
    sessionId: SESSION_ID,
    // Cross-path twins: identical display names, different provider paths (the case the
    // provider-path annotation exists to disambiguate).
    primaryModel: 'global.anthropic.claude-opus-4-8',
    primaryModelName: 'Claude 4.8 Opus',
    fallbackModel: 'claude-opus-4-8',
    fallbackModelName: 'Claude 4.8 Opus',
    timestamp: Date.now(),
    ...overrides,
  };
  localStorage.setItem('lastFallbackInfo', JSON.stringify(info));
}

describe('FallbackModelBadge', () => {
  beforeEach(() => {
    localStorage.clear();
  });

  it('renders the badge and disambiguates identically-named twins by provider path in the tooltip', async () => {
    seedFallback();
    render(
      <TestWrapper>
        <FallbackModelBadge sessionId={SESSION_ID} />
      </TestWrapper>
    );

    const chip = await screen.findByTestId('fallback-model-badge-chip');
    fireEvent.mouseOver(chip);

    const tooltip = await screen.findByText(
      'Claude 4.8 Opus (Bedrock) was unavailable, response generated by Claude 4.8 Opus (Anthropic direct)'
    );
    expect(tooltip).toBeInTheDocument();
  });

  it('does not render when the stored fallback belongs to a different session', async () => {
    seedFallback({ sessionId: 'other-session' });
    render(
      <TestWrapper>
        <FallbackModelBadge sessionId={SESSION_ID} />
      </TestWrapper>
    );

    await waitFor(() => {
      expect(screen.queryByTestId('fallback-model-badge-chip')).not.toBeInTheDocument();
    });
  });
});
