#!/usr/bin/env bash
# Generates .changeset/pr-<N>.md from a conventional-commit PR title and the PR diff, and
# commits + pushes it to the checked-out branch. Run by .github/workflows/auto-changeset.yml.
#
# .github/scripts/verify-changeset.sh re-runs this exact script against a PR head with the
# push redirected to a throwaway remote: if it would commit anything, the head's changeset
# is wrong and the required `validate` check fails. So any change here changes both what
# the bot writes and what merge requires.
#
# Env: PR_TITLE, PR_NUMBER, REPO (owner/name), GH_TOKEN (for best-effort PR comments).
# Runs from the repo root, with origin/main fetched. Sibling scripts resolve from this
# script's own dir: CI runs copies staged from main, not the PR head's.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CHANGESET_FILE=".changeset/pr-${PR_NUMBER}.md"
AUTO_MARKER="<!-- auto-generated by auto-changeset workflow -->"
BOT_NAME="b4m-release-bot[bot]"

echo "PR Title: $PR_TITLE"
echo "PR Number: $PR_NUMBER"

# Comment upkeep is best effort throughout: under `set -e` a failing `gh api` would
# otherwise abort the step, and the calls that run before the changeset is written would
# then leave the PR with no changeset at all. The required `validate` check re-runs this
# script (verify-changeset.sh), so a missing changeset blocks merge rather than shipping
# an unbumped package - but the author still has to notice and re-run.
find_comment() {
  gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" \
    --jq ".[] | select(.body | contains(\"$1\")) | .id" 2>/dev/null | head -1 || true
}

upsert_comment() {
  local id
  id=$(find_comment "$1")
  if [ -n "$id" ]; then
    gh api "repos/${REPO}/issues/comments/${id}" -X PATCH -f body="$2" > /dev/null 2>&1 || true
  else
    gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" -f body="$2" > /dev/null 2>&1 || true
  fi
}

delete_comment() {
  local id
  id=$(find_comment "$1")
  if [ -n "$id" ]; then
    gh api "repos/${REPO}/issues/comments/${id}" -X DELETE > /dev/null 2>&1 || true
  fi
}

MERGE_BASE=$(git merge-base HEAD origin/main)

# -- 0. Honour a deleted auto-changeset as an opt-out --
# The bot used to re-add a changeset the author had deliberately deleted,
# because a pr-*.md file is skipped by the manual-changeset scan in step 6
# and so looked like it had never existed. A human deletion on this branch
# is durable; the bot's own cleanup deletions are not.
if [ ! -f "$CHANGESET_FILE" ]; then
  HUMAN_DELETER=$(git log "$MERGE_BASE..HEAD" --diff-filter=D --format='%an' \
    -- "$CHANGESET_FILE" | grep -vxF "$BOT_NAME" | head -1 || true)
  if [ -n "$HUMAN_DELETER" ]; then
    echo "::notice::Auto-changeset for PR #${PR_NUMBER} was deleted by ${HUMAN_DELETER}. Treating as opt-out."
    exit 0
  fi
fi

# -- 1. Parse conventional commit from PR title --
# Pattern: type(scope): description  OR  type(scope)!: description
if [[ ! "$PR_TITLE" =~ ^([a-z]+)(\(([a-zA-Z0-9,/_-]+)\))?(!)?\:\ (.+)$ ]]; then
  echo "::warning::PR title does not match conventional commit format (type(scope): description)."

  # Remove stale auto-changeset if present
  if [ -f "$CHANGESET_FILE" ] && grep -q "$AUTO_MARKER" "$CHANGESET_FILE" 2>/dev/null; then
    git rm "$CHANGESET_FILE"
    git commit -m "chore: remove auto-changeset for PR #${PR_NUMBER} (non-conventional title)"
    git push
  fi

  # Post PR comment with guidance
  COMMENT_MARKER="<!-- auto-changeset-comment -->"
  COMMENT_BODY="${COMMENT_MARKER}
**Auto-Changeset:** PR title does not follow conventional commit format (\`type(scope): description\`).

No changeset was auto-generated. If this PR changes published packages, either:
- Update the PR title (e.g., \`feat(common): add new feature\`)
- Or run \`pnpm changeset\` manually

Valid types: \`feat\` (minor), \`fix\`/\`perf\` (patch), \`refactor\` (patch), or append \`!\` for major."

  upsert_comment "$COMMENT_MARKER" "$COMMENT_BODY"

  exit 0
fi

TYPE="${BASH_REMATCH[1]}"
SCOPE="${BASH_REMATCH[3]:-}"
BREAKING="${BASH_REMATCH[4]:-}"
DESCRIPTION="${BASH_REMATCH[5]}"

echo "Type: $TYPE | Scope: $SCOPE | Breaking: $BREAKING"

# -- 2. Determine bump level --
if [ -n "$BREAKING" ]; then
  BUMP="major"
elif [ "$TYPE" = "feat" ]; then
  BUMP="minor"
elif [ "$TYPE" = "fix" ] || [ "$TYPE" = "perf" ] || [ "$TYPE" = "refactor" ]; then
  BUMP="patch"
else
  echo "::notice::Type '$TYPE' does not require a changeset. Skipping."

  # Remove stale auto-changeset if title changed from publishable to non-publishable
  if [ -f "$CHANGESET_FILE" ] && grep -q "$AUTO_MARKER" "$CHANGESET_FILE" 2>/dev/null; then
    git rm "$CHANGESET_FILE"
    git commit -m "chore: remove auto-changeset for PR #${PR_NUMBER} (type: $TYPE)"
    git push
  fi

  # Delete the guidance comment if it exists (title is now valid, just non-publishable)
  delete_comment "<!-- auto-changeset-comment -->"
  delete_comment "<!-- auto-changeset-scope-comment -->"

  exit 0
fi

echo "Bump level: $BUMP"

# -- 3. Resolve target packages from the changed files --
# The diff is the only source of truth. The PR title scope is passed in for
# reporting only: a scope that names a publishable package the diff never
# touches used to be unioned in here, bumping and changelogging packages the
# PR did not change. See .github/scripts/resolve-changeset-packages.sh.
RESOLVE_LOG=$(mktemp)
TARGET_PKGS=$(git diff --name-only "$MERGE_BASE" HEAD |
  bash "$SCRIPT_DIR/resolve-changeset-packages.sh" "$SCOPE" 2>"$RESOLVE_LOG")
cat "$RESOLVE_LOG"

# -- 4. Tell the author about a scope with nothing behind it --
SCOPE_COMMENT_MARKER="<!-- auto-changeset-scope-comment -->"
UNMATCHED=$(sed -n 's/^unmatched-scope: //p' "$RESOLVE_LOG")
if [ -n "$UNMATCHED" ]; then
  UNMATCHED_LIST=$(printf '%s\n' "$UNMATCHED" | sed 's/^/- `/; s/$/`/')
  upsert_comment "$SCOPE_COMMENT_MARKER" "${SCOPE_COMMENT_MARKER}
**Auto-Changeset:** the PR title scope names published package(s) that this diff does not touch:

${UNMATCHED_LIST}

No version bump was generated for them - a changeset would publish a release with no corresponding change. If the behaviour of those packages really did change (for example through a dependency or a config file outside the package), run \`pnpm changeset\` to say so explicitly. Otherwise adjust the PR title scope."
else
  delete_comment "$SCOPE_COMMENT_MARKER"
fi

if [ -z "$TARGET_PKGS" ]; then
  echo "::notice::No publishable packages changed. Skipping changeset."

  # Clean up stale auto-changeset
  if [ -f "$CHANGESET_FILE" ] && grep -q "$AUTO_MARKER" "$CHANGESET_FILE" 2>/dev/null; then
    git rm "$CHANGESET_FILE"
    git commit -m "chore: remove auto-changeset for PR #${PR_NUMBER} (no publishable changes)"
    git push
  fi
  exit 0
fi

# -- 5. Check for existing manual changesets (additive mode) --
# If a manual changeset already covers a package AT AN EQUAL OR HIGHER bump level, skip
# auto-generating for it. The level comparison is the point: this check used to match on
# package NAME alone, so a pending manual `patch` would swallow this PR's `minor` or
# `major` and the release would understate the change - a breaking change could ship as a
# patch with every check green. Additive mode is preserved; it just no longer discards a
# bump that the manual changeset does not actually cover.
# One "<pkg> <level>" line per frontmatter entry; duplicates are resolved at lookup.
MANUAL_COVERED=""

# patch < minor < major. Unknown/empty ranks 0 so it never suppresses a real bump.
bump_rank() {
  case "${1:-}" in
    major) echo 3 ;;
    minor) echo 2 ;;
    patch) echo 1 ;;
    *) echo 0 ;;
  esac
}

for cs_file in .changeset/*.md; do
  [ -f "$cs_file" ] || continue
  filename=$(basename "$cs_file")

  # Skip README and auto-generated files
  [ "$filename" = "README.md" ] && continue
  [[ "$filename" == pr-*.md ]] && continue

  # Parse packages from the changeset frontmatter
  in_frontmatter=false
  while IFS= read -r line; do
    if [ "$line" = "---" ]; then
      if [ "$in_frontmatter" = true ]; then
        break
      else
        in_frontmatter=true
        continue
      fi
    fi
    if [ "$in_frontmatter" = true ]; then
      # Extract package name AND level: "@bike4mind/common": minor  OR  @bike4mind/common: minor
      pkg=$(echo "$line" | sed -n 's/^"\{0,1\}\(@[^"]*\)"\{0,1\}:.*/\1/p')
      lvl=$(echo "$line" | sed -n 's/^"\{0,1\}@[^"]*"\{0,1\}:[[:space:]]*\([a-z]\{1,\}\).*/\1/p')
      if [ -n "$pkg" ]; then
        MANUAL_COVERED="${MANUAL_COVERED}${pkg} ${lvl}"$'\n'
      fi
    fi
  done < "$cs_file"
done

# Drop packages already covered by a manual changeset at an equal or higher level.
if [ -n "$MANUAL_COVERED" ]; then
  AUTO_RANK=$(bump_rank "$BUMP")
  REMAINING=""
  while IFS= read -r pkg; do
    [ -n "$pkg" ] || continue
    # Several manual changesets may name the same package; the highest level wins,
    # matching what `changeset version` itself does across multiple files. A package with
    # no manual changeset, or one whose level is unparseable, ranks 0 and is always kept.
    manual_rank=0
    manual_lvl=""
    while IFS=' ' read -r m_pkg m_lvl; do
      [ "$m_pkg" = "$pkg" ] || continue
      if [ "$(bump_rank "$m_lvl")" -gt "$manual_rank" ]; then
        manual_rank=$(bump_rank "$m_lvl")
        manual_lvl="$m_lvl"
      fi
    done <<< "$MANUAL_COVERED"

    if [ "$manual_rank" -ge "$AUTO_RANK" ]; then
      echo "  Package $pkg already covered by manual changeset ($manual_lvl >= $BUMP). Skipping."
    else
      if [ "$manual_rank" -gt 0 ]; then
        echo "  Package $pkg has a manual changeset ($manual_lvl) below this PR's $BUMP. Keeping it."
      fi
      REMAINING="${REMAINING}${pkg}"$'\n'
    fi
  done <<< "$TARGET_PKGS"
  TARGET_PKGS=$(printf '%s' "$REMAINING" | sed '/^$/d')
fi

if [ -z "$TARGET_PKGS" ]; then
  echo "::notice::All changed packages covered by manual changesets. Skipping auto-generation."
  exit 0
fi

echo "Packages to bump: $(printf '%s' "$TARGET_PKGS" | tr '\n' ' ')"

# A hand-edited pr-<N>.md is a trap in both directions: the write below overwrites it
# unconditionally, and step 5 skips pr-*.md when scanning for manual changesets, so the
# edit is neither kept nor honored - it just vanishes with CI green. The removal paths
# above already gate on AUTO_MARKER so this workflow never DELETES human content; this is
# the same check on the write side. Detect only here and report in step 8, AFTER the
# changeset is safely committed.
HAND_EDITED=false
if [ -f "$CHANGESET_FILE" ] && ! grep -q "$AUTO_MARKER" "$CHANGESET_FILE" 2>/dev/null; then
  HAND_EDITED=true
  echo "::warning::${CHANGESET_FILE} looks hand-edited and is being overwritten. Run 'pnpm changeset' to author an override."
fi

# -- 6. Generate changeset file --
{
  echo "$AUTO_MARKER"
  echo "---"
  while IFS= read -r pkg; do
    [ -n "$pkg" ] || continue
    echo "\"$pkg\": $BUMP"
  done <<< "$TARGET_PKGS"
  echo "---"
  echo ""
  echo "$DESCRIPTION"
} > "$CHANGESET_FILE"

echo "Generated changeset:"
cat "$CHANGESET_FILE"

# -- 7. Commit and push if the content actually changed --
# Deliberately not an early `exit 0`: step 8 must still reconcile the PR comments, or a
# stale hand-edit warning would survive the very push that fixed the file (that push
# regenerates identical content, so this branch is exactly when cleanup is needed).
git add "$CHANGESET_FILE"
if git diff --cached --quiet; then
  echo "::notice::Changeset already up-to-date. No commit needed."
else
  git commit -m "chore: auto-generate changeset for PR #${PR_NUMBER}"
  git push
fi

# -- 8. Reconcile PR comments (best effort - must never fail the run) --
# Runs only after the changeset is committed, and the comment helpers swallow API errors,
# so a GitHub hiccup can cost at most a comment, never the changeset.
delete_comment "<!-- auto-changeset-comment -->"

# Hand-edit warning: post while the condition holds, clear it once the file is ours again.
EDIT_MARKER="<!-- auto-changeset-handedit -->"
if [ "$HAND_EDITED" = true ]; then
  upsert_comment "$EDIT_MARKER" "${EDIT_MARKER}
**Auto-Changeset:** \`${CHANGESET_FILE}\` looked hand-edited, and this workflow has overwritten it.

That file is generated from the PR title and rewritten on every push, so edits to it are always lost. It is also skipped when scanning for manual changesets, so it never counts as an override either.

To override the generated bump, run \`pnpm changeset\` and commit the file it creates under any other name. Those are respected: a manual changeset at or above this PR's bump level replaces the auto-generated one, and a lower one is kept alongside it."
else
  delete_comment "$EDIT_MARKER"
fi

echo "::notice::Changeset committed for PR #${PR_NUMBER}"
