services:
  db:
    image: mongo
    container_name: mongo1
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    ports:
      - 27017:27017
    entrypoint: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
