/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ANTHROPIC_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AgentExecutor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AppEventBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "B4M_ANALYTICS_ENABLED": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "B4M_PROD_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CliToolHandler": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "CliWsCompletionHandler": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "DataSyncer": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DatabaseMigrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DatabaseSeeder": {
      "name": string
      "type": "sst.aws.Function"
    }
    "E2E_CLEANUP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EMERGENCY_LOGIN_ENABLED": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GA_IMPERSONATE_SUBJECT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GA_SERVICE_ACCOUNT_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GEMINI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_ZAP_REF": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HistoryUploadCompleteFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "IS_SOURCE_DEPLOYMENT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ImageProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "JWT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LINKEDIN_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LINKEDIN_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MAIL_FROM": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MAIL_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MAIL_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MAIL_PORT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MAIL_USERNAME": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MONGODB_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NPM_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NotebookImportCompleteFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OAUTH_RSA_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OKTA_AUDIENCE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OKTA_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OKTA_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OKTA_USE_ORG_AUTH_SERVER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OVERWATCH_INGEST_ENABLED": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OVERWATCH_INGEST_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OVERWATCH_INGEST_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OVERWATCH_PSEUDONYM_SALT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PDFJS_EXPRESS_VIEWER_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPTIHASHI_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPTIHASHI_API_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPTIHASHI_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPTIHASHI_WEBHOOK_SECRET_PREVIOUS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ChatCompletion": {
      "type": "sst.aws.Service"
      "url": string
    }
    "RATE_LIMIT_INGEST_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "RouterDistributionId": {
      "id": string
      "type": "sst.sst.Linkable"
    }
    "SECOPS_ATTACK_SIMULATION_INGEST_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_CODE_INGEST_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_CODE_INGEST_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_PACKAGES_DISPATCH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_PACKAGES_INGEST_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_PACKAGES_INGEST_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_PROWLER_INGEST_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_PROWLER_WORKFLOW_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_SECRETS_DISPATCH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_SECRETS_INGEST_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_SECRETS_INGEST_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_WAF_DISTRIBUTION_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_WAF_WEBACL_ARN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_ZAP_DISPATCH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECOPS_ZAP_INGEST_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECRET_ENCRYPTION_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECRET_ENCRYPTION_KEY_PREVIOUS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SESSION_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_ERROR_REPORTING_WEBHOOK_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_OAUTH_REDIRECT_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_SIGNING_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_WEBHOOK_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPPORT_EMAIL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SecurityAlerts": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "SlackEventBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "SlackQuestProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WHATS_NEW_DISTRIBUTION_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "YOUTUBE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "agentContinuationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "agentContinuationQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "agentProactiveMessageQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "agentProactiveMessageQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "appFilesBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "attackSimulationFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "deepAgentWakeQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "deepAgentWakeQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "dlqUrls": {
      "agent-continuation": string
      "agent-proactive-message": string
      "deep-agent-wake": string
      "email-analysis": string
      "email-batch": string
      "email-ingestion": string
      "email-job": string
      "fab-file-chunk": string
      "fab-file-vectorize": string
      "github-webhook": string
      "image-edit": string
      "image-generation": string
      "liveops-triage": string
      "notebook-curation": string
      "overwatch-analytics": string
      "quest-export": string
      "qwork-run-completion": string
      "research-engine": string
      "secops-triage": string
      "slack-export": string
      "sre-fix": string
      "sre-job": string
      "tavern-heartbeat": string
      "type": "sst.sst.Linkable"
      "video-generation": string
      "webhook-delivery": string
      "whats-new-generation": string
      "whats-new-highlights": string
    }
    "emailAnalysisQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "emailAnalysisQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "emailBatchQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "emailBatchQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "emailIngestionBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "emailIngestionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "emailIngestionQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "emailJobQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "emailJobQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "fabFileBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "fabFileChunkQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "fabFileChunkQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "fabFileVectorizeQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "fabFileVectorizeQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "frontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "generatedImagesBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "githubWebhookQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "githubWebhookQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "historyImportBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "imageEditDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "imageEditQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "imageGenerationDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "imageGenerationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "lambdaFunctionNames": {
      "attackSimulation": string
      "type": "sst.sst.Linkable"
    }
    "liveOpsTriageQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "liveOpsTriageQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "logHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "mcpHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "notebookCurationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "notebookCurationQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "overwatchAnalyticsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "overwatchAnalyticsQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "publishedArtifactsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "questExportQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "questExportQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "qworkRunCompletionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "qworkRunCompletionQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "researchEngineQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "researchEngineQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "secopsTriageQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "secopsTriageQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "slackExportBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "slackExportQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "slackExportQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "sourceQueueUrls": {
      "agentContinuationQueue": string
      "agentProactiveMessageQueue": string
      "deepAgentWakeQueue": string
      "emailAnalysisQueue": string
      "emailBatchQueue": string
      "emailIngestionQueue": string
      "emailJobQueue": string
      "fabFileChunkQueue": string
      "fabFileVectorizeQueue": string
      "githubWebhookQueue": string
      "imageEditQueue": string
      "imageGenerationQueue": string
      "liveOpsTriageQueue": string
      "notebookCurationQueue": string
      "overwatchAnalyticsQueue": string
      "questExportQueue": string
      "qworkRunCompletionQueue": string
      "researchEngineQueue": string
      "secopsTriageQueue": string
      "slackExportQueue": string
      "sreFixQueue": string
      "sreJobQueue": string
      "tavernHeartbeatQueue": string
      "type": "sst.sst.Linkable"
      "videoGenerationQueue": string
      "webhookDeliveryQueue": string
      "whatsNewGenerationQueue": string
      "whatsNewHighlightsQueue": string
    }
    "sreFixQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "sreFixQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "sreJobQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "sreJobQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "subscriberFanoutV2": {
      "type": "sst.aws.Service"
    }
    "tavernHeartbeatQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "tavernHeartbeatQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "userActivityReportFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "videoGenerationDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "videoGenerationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "webhookDeliveryQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "webhookDeliveryQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "websocket": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "whatsNewDistributionId": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "whatsNewGenerationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "whatsNewGenerationQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "whatsNewHighlightsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "whatsNewHighlightsQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}

import "sst"
export {}