/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: process.env.SEED_APP_NAME || 'bike4mind',
      removal: ['production', 'shared-dev'].includes(input?.stage) ? 'retain' : 'remove',
      protect: ['production', 'shared-dev'].includes(input?.stage),
      home: 'aws',
      watch: ['infra', 'apps', 'packages', 'b4m-core'],
      providers: {
        aws: {
          region: 'us-east-2',
        },
      },
    };
  },
  async run() {
    // Optional native/heavy peer deps that libraries lazy-import but which no
    // runtime path exercises today — marked external for EVERY Lambda Function
    // so esbuild never tries to bundle/resolve them (external-only, no
    // `install`; if a runtime path is later activated, the specific Function
    // must add `install: [...]` to ship the prebuild — pattern: infra/mcp.ts):
    //  - isolated-vm: @bike4mind/agents native addon, imported transitively via
    //    packages/database into nearly every Function. Loaded lazily
    //    (createRequire) only when an IsolatedVmExecutor is constructed, which
    //    no runtime path does today; an eager bundle broke DatabaseMigrator/
    //    Seeder at cold start with `No native build was found` (#8113).
    //  - @huggingface/transformers / onnxruntime-node: voyageai's optional
    //    local tokenizer/embedder peers (peerDependenciesMeta.optional). We only
    //    use the hosted VoyageAIClient.embed() API, so voyageai's guarded
    //    `await import('@huggingface/transformers')` never runs. Without this,
    //    esbuild fails every voyageai-bundling Function with
    //    `Could not resolve "@huggingface/transformers"`.
    // (Registered before any Function is created so the transform applies to all.)
    const ALWAYS_EXTERNAL = ['isolated-vm', '@huggingface/transformers', 'onnxruntime-node'];
    $transform(sst.aws.Function, args => {
      args.nodejs = $output(args.nodejs).apply(nodejs => {
        const esbuild = { ...(nodejs?.esbuild ?? {}) };
        const external = Array.isArray(esbuild.external) ? [...esbuild.external] : [];
        for (const dep of ALWAYS_EXTERNAL) {
          if (!external.includes(dep)) external.push(dep);
        }
        return { ...nodejs, esbuild: { ...esbuild, external } };
      });
    });

    // Watch for changes in the core packages and rebuild them.
    // This only runs in dev mode.
    // Note: Ensure that the core packages are built(pnpm core:build) before starting the dev command.
    new sst.x.DevCommand('core', {
      link: [],
      dev: {
        autostart: true,
        command: 'pnpm core:dev',
      },
    });

    const {
      fabFileBucket,
      generatedImagesBucket,
      appFilesBucket,
      routePrefix,
      isSharedRouterConsumer,
      historyImportBucket,
      emailIngestionBucket,
      emailIngestionQueue,
      slackExportBucket,
      slackExportQueue,
      githubWebhookQueue,
      whatsNewDistributionBucket,
      vpc,
      vpcId,
      mcpHandler,
      cliToolHandler,
      router,
      web,
      websocketApi,
      eventBus,
      secrets,
      subscriberFanout,
      scheduleTaskCron,
      allSecrets,
      lambdaVpc,
      DEFAULT_LAMBDA_ENVIRONMENT,
      tavernHeartbeatQueue,
    } = await import('./infra');

    // Contribute premium package infra (crons, alarms, Slack fan-out, EventBridge
    // subscriptions). Imported from generated glue files under infra/premium-generated/
    // so this path is stable whether or not the overlay is present (open-core fork).
    //
    // The glue files are generated by `pnpm codegen` (scripts/generate-premium-glue.mjs):
    //   overlay PRESENT → re-exports contributeInfra from the source via a relative import
    //   overlay ABSENT  → exports a no-op stub (open-core fork / CI fork simulation)
    //
    // Why relative (not bare @bike4mind/premium-* specifier): esbuild treats symlinked
    // workspace packages as EXTERNAL (evanw/esbuild#2483), so a bare specifier fails at
    // runtime from .sst/platform/. A relative .ts import is bundled+transpiled inline.
    // The generated file uses the same relative pattern for the same reason.
    const { contributeInfra } = await import('./infra/premium-generated/overwatch-infra.generated');
    contributeInfra({
      lambdaVpc,
      allSecrets,
      defaultLambdaEnvironment: DEFAULT_LAMBDA_ENVIRONMENT,
      slackErrorWebhookUrl: secrets.SLACK_ERROR_REPORTING_WEBHOOK_URL,
    });

    const { contributeInfra: contributePiInfra } = await import('./infra/premium-generated/pi-infra.generated');
    contributePiInfra({
      lambdaVpc,
      allSecrets,
      defaultLambdaEnvironment: DEFAULT_LAMBDA_ENVIRONMENT,
      eventBus,
      websocketApi,
    });

    // Tavern premium infra: heartbeat subscription Lambda, heartbeat cron,
    // tavern_scene_command websocket route, /tavern-sounds and /tavern-icons bucket routes.
    // Queue and DLQ resources stay in infra/queues.ts so web.ts Linkables and dlqAlarms.ts
    // can reference them at module-level. The subscription handler path points to the
    // generated server/premium-generated/ stub. Imported from the generated infra glue
    // (infra/premium-generated/tavern-infra.generated) so this path is stable whether or
    // not the overlay is present — same pattern as Overwatch/Pi above.
    //
    // NOTE (observability): unlike core queue subscriptions, the tavern heartbeat Lambda
    // is NOT wired into infra/logMonitor.ts (CloudWatch-log-line → Slack forwarding).
    // That forwarding can't see overlay-created Lambdas fork-safely, and no overlay
    // (overwatch/pi) wires its Lambdas into logMonitor either — this conforms to the
    // overlay pattern. Retry-exhaustion failures are still alarmed to Slack via the
    // retained tavern-heartbeat DLQ alarm (infra/dlqAlarms.ts).
    const { contributeInfra: contributeTavernInfra } = await import('./infra/premium-generated/tavern-infra.generated');
    contributeTavernInfra({
      lambdaVpc,
      allSecrets,
      defaultLambdaEnvironment: DEFAULT_LAMBDA_ENVIRONMENT,
      websocketApi,
      fabFileBucket,
      generatedImagesBucket,
      tavernHeartbeatQueue,
      router,
      routePrefix,
      appFilesBucket,
      isSharedRouterConsumer,
    });

    // OptiHashi premium infra: compute alarm topics, MetricAlarms, run-poller cron.
    // Handler path uses generated stub (server/premium-generated/qworkRunPoller.ts) so
    // the Lambda URN is stable even as the source moves between core and the package.
    const { contributeInfra: contributeOptiInfra } =
      await import('./infra/premium-generated/optihashi-infra.generated');
    contributeOptiInfra({
      lambdaVpc,
      allSecrets,
      defaultLambdaEnvironment: DEFAULT_LAMBDA_ENVIRONMENT,
      websocketApi,
    });

    return {
      appName: $app.name,
      stage: $app.stage,
      vpc: vpc?.id || vpcId,
      router: router?.distributionID,
      routerUrl: router?.url,
      // CloudFront distribution hostname for External DNS CNAME setup (e.g., d1234abc.cloudfront.net)
      routerDistributionDomain: router?.nodes.cdn.nodes.distribution.domainName,
      web: web.url,
      fabFileBucket: fabFileBucket.name,
      generatedImagesBucket: generatedImagesBucket.name,
      appFilesBucket: appFilesBucket.name,
      historyImportBucket: historyImportBucket.name,
      emailIngestionBucket: emailIngestionBucket.name,
      emailIngestionQueue: emailIngestionQueue.url,
      slackExportBucket: slackExportBucket.name,
      slackExportQueue: slackExportQueue.url,
      githubWebhookQueue: githubWebhookQueue.url,
      whatsNewDistributionBucket: whatsNewDistributionBucket?.name,
      mcpHandler: mcpHandler.name,
      cliToolHandler: cliToolHandler.name,
      websocket: websocketApi.url,
      websocketEndpoint: websocketApi.managementEndpoint,
      mongoDbUri: $dev ? secrets.MONGODB_URI.value : undefined,
      subscriberFanout: subscriberFanout.urn,
      scheduleTaskCron: scheduleTaskCron.urn,
    };
  },
});
