/**
 * Audit-log event enums.
 *
 * Kept in a dedicated, dependency-free module so that `analytics/index.ts`
 * can spread them into `ANALYTICS_EVENTS` without creating an import cycle
 * with `auditLog.ts` (which imports `logEvent` from `analyticsLog.ts`, which
 * in turn imports from `analytics/index.ts`).
 */

export enum EmailAuditEvents {
  // Email Verification Events
  EMAIL_VERIFICATION_SENT = 'EMAIL_VERIFICATION_SENT',
  EMAIL_VERIFICATION_RESENT = 'EMAIL_VERIFICATION_RESENT',
  EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS',
  EMAIL_VERIFICATION_FAILED = 'EMAIL_VERIFICATION_FAILED',
  EMAIL_VERIFICATION_TOKEN_EXPIRED = 'EMAIL_VERIFICATION_TOKEN_EXPIRED',
  EMAIL_VERIFICATION_TOKEN_REUSED = 'EMAIL_VERIFICATION_TOKEN_REUSED',

  // Email Change Events
  EMAIL_CHANGE_REQUESTED = 'EMAIL_CHANGE_REQUESTED',
  EMAIL_CHANGE_SUCCESS = 'EMAIL_CHANGE_SUCCESS',
  EMAIL_CHANGE_FAILED = 'EMAIL_CHANGE_FAILED',
  EMAIL_CHANGE_CANCELLED = 'EMAIL_CHANGE_CANCELLED',
  EMAIL_CHANGE_TOKEN_EXPIRED = 'EMAIL_CHANGE_TOKEN_EXPIRED',
  EMAIL_CHANGE_TOKEN_REUSED = 'EMAIL_CHANGE_TOKEN_REUSED',

  // Admin Actions
  ADMIN_EMAIL_VERIFIED = 'ADMIN_EMAIL_VERIFIED',
  ADMIN_EMAIL_UNVERIFIED = 'ADMIN_EMAIL_UNVERIFIED',
  ADMIN_VERIFICATION_RESENT = 'ADMIN_VERIFICATION_RESENT',
  ADMIN_EMAIL_CHANGE_RESENT = 'ADMIN_EMAIL_CHANGE_RESENT',
}

export enum AdminConfigAuditEvents {
  // What's New Configuration Events
  WHATS_NEW_CONFIG_UPDATED = 'WHATS_NEW_CONFIG_UPDATED',
  WHATS_NEW_CONFIG_VIEWED = 'WHATS_NEW_CONFIG_VIEWED',
  WHATS_NEW_SYNC_TRIGGERED = 'WHATS_NEW_SYNC_TRIGGERED',

  // System Health Events
  ADMIN_TEST_EMAIL_SENT = 'ADMIN_TEST_EMAIL_SENT',
  ADMIN_DATABASE_TEST = 'ADMIN_DATABASE_TEST',
  ADMIN_OAUTH_TEST = 'ADMIN_OAUTH_TEST',

  // Security Scan Schedule Events
  SECURITY_SCAN_SCHEDULE_ENABLED = 'SECURITY_SCAN_SCHEDULE_ENABLED',
  SECURITY_SCAN_SCHEDULE_DISABLED = 'SECURITY_SCAN_SCHEDULE_DISABLED',
  SECURITY_SCAN_SCHEDULE_UPDATED = 'SECURITY_SCAN_SCHEDULE_UPDATED',
  SECURITY_SCAN_SCHEDULE_TRIGGERED = 'SECURITY_SCAN_SCHEDULE_TRIGGERED',
  SECURITY_SCAN_SCHEDULE_FAILED = 'SECURITY_SCAN_SCHEDULE_FAILED',
  SECURITY_SCAN_SCHEDULE_SKIPPED = 'SECURITY_SCAN_SCHEDULE_SKIPPED',
}

export enum AdminOrgAuditEvents {
  ORG_GRANTED = 'ORG_GRANTED',
  ORG_TOPPED_UP = 'ORG_TOPPED_UP',
  ORG_SEATS_CHANGED = 'ORG_SEATS_CHANGED',
  ORG_CONVERT_INITIATED = 'ORG_CONVERT_INITIATED',
  ORG_REVOKED = 'ORG_REVOKED',
}
