/**
 * Write a Quest doc to the session so an agent run shows up in chat history
 * after refresh (parity with `chat_completion`, which writes a Quest as part
 * of its natural flow). Without this, `useGetSessionQuests` returns an empty
 * list for the session and the chat middle is blank - the AgentExecution
 * doc exists in MongoDB but isn't joined by the chat-history endpoint.
 *
 * Best-effort: a Quest write failure must not roll back the execution itself
 * (the WebSocket `completed` event has already gone out and the user has
 * seen their answer). Errors are logged but swallowed.
 *
 * Shared between the Agent Executor Lambda's natural completion path and the
 * WebSocket `gate_response: stop` handler so both code paths produce
 * the same chat-history shape on refresh.
 */
import { agentExecutionRepository, Quest } from '@bike4mind/database';
import type { Logger } from '@bike4mind/observability';

export async function persistRunAsQuest(
  executionId: string,
  replyText: string,
  logger: Logger,
  /**
   * Filenames of images generated by tools during the run (in the generated-content bucket).
   * Written to `quest.images` so the inline image grid renders in chat history - the agent
   * path has no live quest to accrete these into, unlike classic chat. See agentExecutor.
   */
  generatedImages?: string[]
): Promise<void> {
  const images = generatedImages?.length ? generatedImages : undefined;
  try {
    const execution = await agentExecutionRepository.findById(executionId);
    if (!execution) {
      logger.warn('[persistRunAsQuest] execution not found — skipping Quest write', { executionId });
      return;
    }
    if (!execution.sessionId) {
      // Defensive: agent_execute always supplies a sessionId, but a Quest
      // without one would be unfindable by the chat-history endpoint.
      logger.warn('[persistRunAsQuest] execution has no sessionId — skipping Quest write', { executionId });
      return;
    }
    // Prefer patching the existing Quest created by `handleStart` so
    // we don't end up with two Quest docs for the same exchange (one prompt-
    // only from dispatch, one prompt+reply from here). Fall back to create
    // for executions started before that fix landed, or when the dispatch-
    // time Quest write failed.
    //
    // `status: 'done'` is set HERE (not at dispatch) so Slack completion
    // pollers (CommandHandler / WorkflowStepHandler) only observe `done`
    // once `replies` is populated - flipping it earlier would let pollers
    // read an empty reply array and silently drop the response.
    const updated = await Quest.findOneAndUpdate(
      { agentExecutionId: executionId },
      {
        $set: {
          replies: [replyText],
          status: 'done',
          updatedAt: new Date(),
          ...(execution.usedMementoIds?.length ? { 'promptMeta.context.mementoIds': execution.usedMementoIds } : {}),
        },
        // $addToSet (not $set) so images contributed by subagents - which write to this same
        // Quest from their own Lambdas via addImagesByAgentExecutionId - aren't clobbered.
        ...(images ? { $addToSet: { images: { $each: images } } } : {}),
      },
      { new: true }
    );
    if (!updated) {
      await Quest.create({
        sessionId: execution.sessionId,
        type: 'message',
        prompt: execution.query,
        replies: [replyText],
        timestamp: new Date(),
        status: 'done',
        ...(images ? { images } : {}),
        // Link back to the AgentExecution so the client can lazy-load the
        // iteration trace on a "Show reasoning" disclosure under the reply.
        agentExecutionId: executionId,
        ...(execution.usedMementoIds?.length
          ? { promptMeta: { context: { mementoIds: execution.usedMementoIds } } }
          : {}),
      });
    }

    // Kick off async session auto-name + summary+tag generation (parity with
    // the chat_completion flow's questProcessor, which publishes BOTH events:
    // - `AutoName` generates the notebook *name* from early prompts.
    // - `Summarize` generates the session summary + downstream tagging job.
    //
    // I initially wired only `summarizeSession` and the notebook stayed on
    // the truncated-prompt name forever; the actual name comes from the
    // AutoName handler. Both handlers are idempotent / no-op when the work
    // is already done, so re-firing on every run is cheap. Dynamic import
    // on the event-bus module avoids a top-level dependency cycle with
    // queue-handler imports.
    try {
      const { SessionEvents } = await import('@server/utils/eventBus');
      await Promise.all([
        SessionEvents.AutoName.publish({ sessionId: execution.sessionId, userId: execution.userId }),
        SessionEvents.Summarize.publish({
          sessionId: execution.sessionId,
          userId: execution.userId,
          callTagging: true,
          trigger: 'earlyMilestone',
        }),
      ]);
    } catch (summarizeErr) {
      logger.warn('[persistRunAsQuest] session naming/summary dispatch failed — non-fatal', {
        executionId,
        sessionId: execution.sessionId,
        error: summarizeErr instanceof Error ? summarizeErr.message : String(summarizeErr),
      });
    }
  } catch (err) {
    logger.error('[persistRunAsQuest] failed to write Quest — chat history will be missing this run', {
      executionId,
      error: err instanceof Error ? err.message : String(err),
    });
  }
}
