import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The sidebar is generated from the docs/ filesystem. Ordering and labels are
// controlled by each directory's _category_.json and per-file sidebar_position
// frontmatter.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
