import {
  Schedule as DateTimeIcon,
  Casino as DiceIcon,
  Image as ImageIcon,
  Calculate as MathIcon,
  Schema as MermaidIcon,
  Search as SearchIcon,
  Language as WebFetchIcon,
  WbSunny as WeatherIcon,
  BarChart as RechartsIcon,
  History as HistoryIcon,
  NightsStay as MoonIcon,
  WbTwilight as SunriseIcon,
  Satellite as SatelliteIcon,
  Explore as PlanetIcon,
} from '@mui/icons-material';

export const TOOLS_MAP = {
  web_search: {
    name: 'Web Search',
    description: 'Search the web for information',
    icon: <SearchIcon />,
  },
  web_fetch: {
    name: 'Web Fetch',
    description: 'Fetch and read full content from a URL',
    icon: <WebFetchIcon />,
  },
  image_generation: {
    name: 'Image Generation',
    description: 'Generate an image',
    icon: <ImageIcon />,
  },
  mermaid_chart: {
    name: 'Mermaid Chart',
    description: 'Generate a mermaid chart',
    icon: <MermaidIcon />,
  },
  weather_info: {
    name: 'Weather Info',
    description: 'Get the weather',
    icon: <WeatherIcon />,
  },
  math_evaluate: {
    name: 'Math Evaluation',
    description: 'Evaluate a math expression',
    icon: <MathIcon />,
  },
  current_datetime: {
    name: 'Current Date/Time',
    description: 'Get the current date and time',
    icon: <DateTimeIcon />,
  },
  dice_roll: {
    name: 'Dice Roll',
    description: 'Roll a dice',
    icon: <DiceIcon />,
  },
  recharts: {
    name: 'Charts',
    description: 'Generate interactive charts',
    icon: <RechartsIcon />,
  },
  wikipedia_on_this_day: {
    name: 'On This Day',
    description: 'Historical events, births, deaths from Wikipedia',
    icon: <HistoryIcon />,
  },
  moon_phase: {
    name: 'Moon Phase',
    description: 'Current moon phase, illumination, and lunar calendar',
    icon: <MoonIcon />,
  },
  sunrise_sunset: {
    name: 'Sunrise/Sunset',
    description: 'Sun times, twilight, golden hour for any location',
    icon: <SunriseIcon />,
  },
  iss_tracker: {
    name: 'ISS Tracker',
    description: 'Track the International Space Station position and crew',
    icon: <SatelliteIcon />,
  },
  planet_visibility: {
    name: 'Planet Visibility',
    description: 'Which planets are visible tonight and where to look',
    icon: <PlanetIcon />,
  },
} as const;

export const emojis = [
  '😀',
  '😃',
  '😄',
  '😁',
  '😅',
  '😂',
  '🤣',
  '😊',
  '😇',
  '🙂',
  '😉',
  '😌',
  '😍',
  '🥰',
  '😘',
  '🐶',
  '🐱',
  '🐭',
  '🐹',
  '🐰',
  '🦊',
  '🐻',
  '🐼',
  '🐨',
  '🐯',
  '🦁',
  '🐮',
  '🐷',
  '🐸',
  '🌟',
  '⭐',
  '✨',
  '💫',
  '🌙',
  '☀️',
  '⚡️',
  '🌈',
  '🌺',
  '🌸',
  '🌼',
  '🌻',
  '🌹',
  '🍀',
  '❤️',
  '🧡',
  '💛',
  '💚',
  '💙',
  '💜',
  '🖤',
  '🤍',
  '🤎',
  '💔',
  '❣️',
  '💕',
  '💞',
  '💓',
  '🎯',
  '🎲',
  '🎮',
  '🎨',
  '🎭',
  '🎪',
  '🎫',
  '🎟️',
  '🎪',
  '🎭',
  '🎨',
  '🎬',
  '🎤',
] as const;

export const colorPalettes = [
  { name: 'Grey', key: 'grey' },
  { name: 'Blue', key: 'blue' },
  { name: 'Red', key: 'red' },
  { name: 'Green', key: 'green' },
  { name: 'Yellow', key: 'yellow' },
] as const;

export const shades = [100, 200, 300, 400, 500, 600, 700, 800] as const;
