import { baseApi } from '@server/middlewares/baseApi';
import { getImageGeneration } from '@server/queueHandlers/imageGeneration';

import { Request } from 'express';
import { z } from 'zod';
import { GenerateImageRequestBodySchema, GenerateImageIvokeParams, ApiKeyScope } from '@bike4mind/common';
import { getOrCreateSession } from '@server/managers/sessionManager';
import { questRepository } from '@bike4mind/database';
import { resolveImagePrompt, HISTORY_LOOKBACK, type PromptResolution } from '@server/utils/resolveImagePrompt';

type GenerateImageRequestBody = z.infer<typeof GenerateImageRequestBodySchema>;
type GenerateImageRequest = Request<unknown, unknown, GenerateImageRequestBody>;

// Gate API-key callers on `ai:generate` so this billable action is auditable and a
// least-privilege image-only key can drive the whole POST -> poll GET /api/quests/{id} flow
// (the poll endpoint already accepts ai:generate). Scope checks apply only to API-key
// requests; browser/JWT sessions fall through untouched (see apiKeyAuth).
const handler = baseApi({ requiredScopes: [ApiKeyScope.AI_GENERATE] }).post(async (req: GenerateImageRequest, res) => {
  req.logger.updateMetadata({
    userId: req.user?.id,
    userEmail: req.user?.email,
    bodyKeys: Object.keys(req.body || {}).join(', '),
    model: req.body.model,
    size: req.body.size,
    width: req.body.width,
    height: req.body.height,
    aspectRatio: req.body.aspect_ratio,
    sessionId: req.body.sessionId,
    questId: req.body.questId,
    n: req.body.n,
    quality: req.body.quality,
    style: req.body.style,
    responseFormat: req.body.response_format,
    promptPreview: req.body?.prompt?.substring(0, 100) + '...',
  });

  const { sessionId: reqSessionId, sessionName, ...invokeParams } = req.body;

  const { sessionId, asyncPromises, session } = await getOrCreateSession({
    sessionId: reqSessionId,
    sessionName: sessionName,
    projectId: invokeParams.projectId,
    user: req.user,
    ability: req.ability,
    logger: req.logger,
  });

  try {
    // organizationId: null means personal account (no org), undefined means not sent (fall back to user's org)
    const effectiveOrgId =
      invokeParams.organizationId !== undefined
        ? invokeParams.organizationId
        : (req.user.organizationId?.toString() ?? null);

    const originalPrompt = req.body?.prompt;

    // Resolve the prompt against session history (text + image). Runs whenever the session has any
    // prior turn so coreference ("different variant", "make it darker") and text-grounded follow-ups
    // ("now generate the logo we discussed") both bind correctly. The pre-computed session summary
    // is included as long-term context - it's generated by the chat path's SummarizeNotebookFeature
    // and stored on the Session doc, so passing it costs zero extra DB calls or LLM calls.
    const recentMessages = originalPrompt
      ? await questRepository.getMostRecentChatHistory(sessionId, HISTORY_LOOKBACK)
      : [];
    const sessionSummary = session?.contextSummary || session?.summary || null;
    const resolution: PromptResolution = originalPrompt
      ? await resolveImagePrompt({
          originalPrompt,
          recentMessages,
          sessionSummary,
          logger: req.logger,
          endUserId: req.user?.id,
        })
      : { rewrittenPrompt: originalPrompt ?? '', intent: 'fresh' };

    // For continuation prompts ("different variant", "the logo we discussed"), the rewrite is
    // non-optional - the user's literal text doesn't carry the subject and the image model would
    // hallucinate without it. So we always use the rewrittenPrompt for continuations, regardless of
    // the prompt_enhancement tool toggle. The toggle only controls rewriting of self-contained
    // 'fresh' prompts, where opting out to keep literal words is a valid user choice.
    const promptEnhancementEnabled = req.body?.tools?.includes('prompt_enhancement') ?? false;
    const shouldUseRewrittenPrompt =
      !!originalPrompt && (resolution.intent === 'continuation' || promptEnhancementEnabled);
    const effectivePrompt = shouldUseRewrittenPrompt ? resolution.rewrittenPrompt : (originalPrompt ?? '');
    const promptWasEnhanced = shouldUseRewrittenPrompt && effectivePrompt !== originalPrompt;

    // INVARIANT: the top-level `intent` and `promptEnhancement.intent` must always reflect the same
    // resolver decision. They serve different lifecycles - top-level is the transit value carried
    // through the SQS queue into `process()` for image carryforward gating; the nested copy is the
    // persisted value on the Quest used by the UI banner. Both are derived from `resolution.intent`
    // here at construction time and must not be mutated independently downstream.
    const enhancedBody: GenerateImageIvokeParams = {
      ...invokeParams,
      sessionId,
      organizationId: effectiveOrgId,
      prompt: effectivePrompt,
      intent: resolution.intent,
      promptEnhancement: originalPrompt
        ? {
            originalPrompt,
            enhancedPrompt: effectivePrompt,
            promptWasEnhanced,
            intent: resolution.intent,
          }
        : undefined,
    };

    req.logger.log(`[DEBUG API] Calling imageGeneration.invoke...`);
    const startTime = performance.now();

    const quest = await getImageGeneration().invoke({
      userId: req.user.id,
      body: enhancedBody,
    });

    const endTime = performance.now();

    req.logger.updateMetadata({
      duration: `${endTime - startTime}ms`,
      questStatus: quest?.status,
      questType: quest?.type,
      hasReply: !!quest?.reply,
      hasImages: !!quest?.images?.length,
      intent: resolution.intent,
      promptEnhancementEnabled,
      promptWasEnhanced,
      usedRewrittenPrompt: shouldUseRewrittenPrompt,
    });

    req.logger.log(`[DEBUG API] ✅ imageGeneration.invoke completed in ${endTime - startTime}ms`);

    await Promise.all(asyncPromises);

    const response = {
      quest,
      session,
      originalPrompt,
      enhancedPrompt: effectivePrompt,
      promptWasEnhanced,
      intent: resolution.intent,
    };

    return res.json(response);
  } catch (error) {
    req.logger.error(`[DEBUG API] ❌ Error in generate-image endpoint:`, {
      error,
      errorMessage: error instanceof Error ? error.message : 'Unknown error',
      userId: req.user?.id,
    });
    throw error;
  }
});

export default handler;
