#!/usr/bin/env node

import { execSync } from 'child_process';
import { existsSync, readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createInterface } from 'readline';

const __dirname = dirname(fileURLToPath(import.meta.url));
const clientDir = resolve(__dirname, '..');
const envFile = resolve(clientDir, '.env.e2e');
const envExample = resolve(clientDir, '.env.e2e.example');

function ask(question) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function main() {
  console.log('\n🎭 Playwright E2E Test Setup\n');

  // Step 1: Install Chromium
  console.log('Step 1: Installing Chromium browser...\n');
  try {
    execSync('pnpm exec playwright install chromium', {
      cwd: clientDir,
      stdio: 'inherit',
    });
    console.log('\n✅ Chromium installed\n');
  } catch {
    console.error('❌ Failed to install Chromium. Make sure you ran pnpm install first.\n');
    process.exit(1);
  }

  // Step 2: Set up .env.e2e
  if (existsSync(envFile)) {
    console.log('Step 2: .env.e2e already exists — skipping.\n');
    console.log('   To reconfigure, delete .env.e2e and run this script again.\n');
  } else {
    console.log('Step 2: Configuring test environment\n');
    console.log('   This creates .env.e2e with your test configuration.');
    console.log('   Admin and per-spec test users are created automatically at runtime.');
    console.log('   Press Enter to keep the default value shown in [brackets].\n');

    const defaults = {};
    const lines = readFileSync(envExample, 'utf-8').split('\n');
    for (const line of lines) {
      const match = line.match(/^(\w+)=(.*)$/);
      if (match) {
        defaults[match[1]] = match[2];
      }
    }

    const vars = {};
    vars.API_URL = (await ask(`   API_URL [${defaults.API_URL || 'http://localhost:3000'}]: `)) || defaults.API_URL || 'http://localhost:3000';

    console.log('\n   E2E_TEST_ID is an optional prefix added to test user emails to isolate');
    console.log('   your test data from other testers on the same environment.');
    console.log('   For example, if you set it to "alice", test users will be created as');
    console.log('   "setup-admin-alice-12345678-e2e@test.com" instead of "setup-admin-12345678-e2e@test.com".');
    console.log('   This is useful when multiple people run E2E tests against a shared');
    console.log('   preview/staging build — it prevents test data collisions and ensures');
    console.log('   cleanup only removes your own test data.\n');
    vars.E2E_TEST_ID = (await ask('   E2E_TEST_ID (optional, e.g. your name or initials): ')) || '';

    console.log('\n   E2E_CLEANUP_SECRET is the shared secret used by the test cleanup API');
    console.log('   to create and remove e2e test users. It is required when running tests');
    console.log('   against staging or preview builds without SST context.');
    console.log('   Ask your team lead for the value, or check the GitHub Actions secrets.\n');
    vars.E2E_CLEANUP_SECRET = (await ask('   E2E_CLEANUP_SECRET (required for staging/preview): ')) || '';

    console.log('\n   PW_WORKERS controls how many test specs run in parallel (1-3).');
    console.log('   Higher values run tests faster but use more CPU and memory.');
    console.log('   Use 1 for sequential execution (easier to debug, less resource-intensive).');
    console.log('   Use 2-3 for faster runs on machines with enough resources.\n');
    let workers;
    do {
      const input = await ask(`   PW_WORKERS [${defaults.PW_WORKERS || '1'}]: `);
      workers = Number(input || defaults.PW_WORKERS || '1');
      if (isNaN(workers) || workers < 1 || workers > 3) {
        console.log('   ⚠️  Please enter a number between 1 and 3.\n');
      }
    } while (isNaN(workers) || workers < 1 || workers > 3);
    vars.PW_WORKERS = String(workers);

    const content = [
      '# E2E Test Environment Variables',
      '# Generated by: pnpm test:e2e:setup',
      '',
      `API_URL=${vars.API_URL}`,
      '',
      `# Optional prefix for test user isolation (e.g. your name or initials)`,
      `# Prevents test data collisions when multiple testers share the same environment`,
      `E2E_TEST_ID=${vars.E2E_TEST_ID}`,
      '',
      `# Secret used by the test cleanup API to remove stale e2e test data`,
      `# Required for running tests against staging or preview builds without SST context`,
      `E2E_CLEANUP_SECRET=${vars.E2E_CLEANUP_SECRET}`,
      '',
      `# Number of parallel Playwright workers (1-3)`,
      `# 1 = sequential (easier to debug), 2-3 = faster but more resource-intensive`,
      `PW_WORKERS=${vars.PW_WORKERS}`,
      '',
    ].join('\n');

    const { writeFileSync } = await import('fs');
    writeFileSync(envFile, content);
    console.log('\n✅ .env.e2e created\n');
  }

  // Step 3: Verify
  console.log('Step 3: Verifying setup...\n');
  try {
    execSync('pnpm exec playwright test --list', {
      cwd: clientDir,
      stdio: 'inherit',
    });
    console.log('\n✅ Setup complete! You can now run:\n');
  } catch {
    console.log('\n✅ Setup complete! You can now run:\n');
  }

  console.log('   pnpm test:e2e          — Run all E2E tests');
  console.log('   pnpm test:e2e:ui       — Open Playwright UI mode');
  console.log('   pnpm test:e2e:headed   — Run tests in a visible browser');
  console.log('   pnpm test:e2e:report   — View the last test report\n');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
