/**
 * What a GitHub-fed lake ingests. The one place the allowlist, denylists and caps live: the ingest
 * enforces them (lakeFileFilter.ts classifyTreeEntry) and the lake's source card shows them.
 */
export const GITHUB_LAKE_FILE_RULES = {
  extensions: [
    'md',
    'mdx',
    'txt',
    'rst',
    'adoc',
    'ts',
    'tsx',
    'js',
    'jsx',
    'mjs',
    'cjs',
    'py',
    'go',
    'rs',
    'java',
    'kt',
    'rb',
    'php',
    'cs',
    'c',
    'h',
    'cpp',
    'hpp',
    'swift',
    'scala',
    'sh',
    'sql',
    'json',
    'yaml',
    'yml',
    'toml',
    'ini',
  ],
  extensionlessNames: ['README', 'LICENSE', 'Dockerfile', 'Makefile'],
  deniedPathSegments: [
    'node_modules',
    'vendor',
    'dist',
    'build',
    '.git',
    'third_party',
    '.next',
    'target',
    '__pycache__',
  ],
  deniedFileNames: [
    'pnpm-lock.yaml',
    'package-lock.json',
    'yarn.lock',
    'Cargo.lock',
    'poetry.lock',
    'Gemfile.lock',
    'go.sum',
    'composer.lock',
  ],
  maxFileBytes: 1024 * 1024,
  maxCandidates: 5000,
} as const;
