// brand externalized
import { getBrandName } from '@client/config/general';

export interface CookbookRecipe {
  id: string;
  title: string;
  description: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  content: string; // markdown
}

export const API_COOKBOOK_INTRO: string =
  `${getBrandName()}'s API Cookbook is a collection of practical, copy-paste-ready recipes ` +
  'for common integration tasks. Each recipe walks through a real workflow end-to-end ' +
  'with curl examples, expected responses, and tips for production use. ' +
  'Set `B4M_API_KEY` and `B4M_BASE_URL` in your environment before running any recipe.';

export const COOKBOOK_RECIPES: CookbookRecipe[] = [
  {
    id: 'start-chat-session',
    title: 'Start a Chat Session',
    description: 'Send a message to the LLM via the Chat API, with model selection and streaming options.',
    difficulty: 'beginner',
    content: [
      '## Start a Chat Session',
      '',
      `The Chat API is the primary way to interact with LLMs through ${getBrandName()}.`,
      'You can choose a model, send a user message, and optionally stream the response.',
      '',
      '### 1. Send a non-streaming chat message',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/chat" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "message": "Summarize the key benefits of RAG pipelines.",',
      '    "model": "gpt-4o",',
      '    "stream": false',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "sessionId": "sess_abc123",',
      '    "messageId": "msg_def456",',
      '    "content": "RAG pipelines combine retrieval with generation to...",',
      '    "model": "gpt-4o",',
      '    "usage": {',
      '      "promptTokens": 24,',
      '      "completionTokens": 180,',
      '      "totalTokens": 204',
      '    }',
      '  }',
      '}',
      '```',
      '',
      '### 2. Stream a chat response',
      '',
      '```bash',
      'curl -N -X POST "$B4M_BASE_URL/api/chat" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "message": "Write a haiku about distributed systems.",',
      '    "model": "gpt-4o",',
      '    "stream": true',
      "  }'",
      '```',
      '',
      'Streamed responses arrive as Server-Sent Events (SSE). Each chunk looks like:',
      '',
      '```',
      'data: {"delta":"Packets ","messageId":"msg_xyz"}',
      'data: {"delta":"travel far\\n","messageId":"msg_xyz"}',
      'data: [DONE]',
      '```',
      '',
      '### 3. Continue a conversation',
      '',
      'Pass the `sessionId` from the first response to continue the thread:',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/chat" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "sessionId": "sess_abc123",',
      '    "message": "Now explain that in simpler terms.",',
      '    "model": "gpt-4o",',
      '    "stream": false',
      "  }'",
      '```',
      '',
      '### Tips',
      '',
      '- Omit `model` to use the system default.',
      '- Set `stream: true` for real-time UX in user-facing applications.',
      '- The `sessionId` persists conversation history server-side.',
    ].join('\n'),
  },
  {
    id: 'upload-vectorize-document',
    title: 'Upload and Vectorize a Document',
    description: 'Create a presigned upload URL, push a file to S3, trigger chunking, and verify vectorization.',
    difficulty: 'beginner',
    content: [
      '## Upload and Vectorize a Document',
      '',
      `${getBrandName()} ingests documents by uploading to S3, then automatically chunking and`,
      'vectorizing the content so it can be used for RAG queries.',
      '',
      '### 1. Request a presigned upload URL',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/files/presigned-url" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "fileName": "quarterly-report.pdf",',
      '    "contentType": "application/pdf"',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "uploadUrl": "https://s3.amazonaws.com/...",',
      '    "fileId": "file_abc123",',
      '    "key": "uploads/user_xyz/file_abc123/quarterly-report.pdf"',
      '  }',
      '}',
      '```',
      '',
      '### 2. Upload the file to S3',
      '',
      '```bash',
      'curl -X PUT "<uploadUrl from step 1>" \\',
      '  -H "Content-Type: application/pdf" \\',
      '  --data-binary @quarterly-report.pdf',
      '```',
      '',
      '### 3. Trigger ingestion (chunking + vectorization)',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/files/$FILE_ID/ingest" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json"',
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "fileId": "file_abc123",',
      '    "status": "processing",',
      '    "message": "File queued for chunking and vectorization."',
      '  }',
      '}',
      '```',
      '',
      '### 4. Check vectorization status',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/files/$FILE_ID" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '**Response when complete:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "fileId": "file_abc123",',
      '    "fileName": "quarterly-report.pdf",',
      '    "status": "vectorized",',
      '    "chunkCount": 47,',
      '    "vectorized": true',
      '  }',
      '}',
      '```',
      '',
      '### Tips',
      '',
      '- Supported formats: PDF, TXT, CSV, JSON, DOCX, and more.',
      '- Large files are automatically split into chunks for efficient retrieval.',
      '- Vectorization runs asynchronously; poll the file status or listen for WebSocket events.',
      '- Once vectorized, the file is available for RAG queries in any chat session.',
    ].join('\n'),
  },
  {
    id: 'build-project-with-files-agents',
    title: 'Build a Project with Files and Agents',
    description: 'Create a project, attach files, configure an agent, and start a chat grounded in project context.',
    difficulty: 'intermediate',
    content: [
      '## Build a Project with Files and Agents',
      '',
      'Projects bundle files and agents into a shared context for focused AI interactions.',
      '',
      '### 1. Create a project',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/projects" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "name": "Q4 Analysis",',
      '    "description": "Quarterly financial analysis workspace"',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "projectId": "proj_abc123",',
      '    "name": "Q4 Analysis",',
      '    "description": "Quarterly financial analysis workspace",',
      '    "createdAt": "2026-03-11T00:00:00.000Z"',
      '  }',
      '}',
      '```',
      '',
      '### 2. Attach files to the project',
      '',
      'Upload files first (see the Upload recipe), then attach them:',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/projects/$PROJECT_ID/files" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "fileIds": ["file_abc123", "file_def456"]',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "projectId": "proj_abc123",',
      '    "attachedFiles": 2,',
      '    "totalFiles": 2',
      '  }',
      '}',
      '```',
      '',
      '### 3. Create an agent for the project',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/agents" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "name": "Financial Analyst",',
      '    "systemPrompt": "You are a financial analyst. Use the attached quarterly reports to answer questions with specific data citations.",',
      '    "model": "gpt-4o",',
      '    "projectId": "proj_abc123"',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "agentId": "agent_xyz789",',
      '    "name": "Financial Analyst",',
      '    "projectId": "proj_abc123"',
      '  }',
      '}',
      '```',
      '',
      '### 4. Chat with project context',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/chat" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "message": "What were our top 3 revenue drivers in Q4?",',
      '    "agentId": "agent_xyz789",',
      '    "projectId": "proj_abc123",',
      '    "stream": false',
      "  }'",
      '```',
      '',
      'The response will include citations from the attached files.',
      '',
      '### Tips',
      '',
      '- Files must be vectorized before they contribute to RAG responses.',
      '- Agents inherit the project file context automatically.',
      '- You can attach or detach files from a project at any time; new chats pick up the changes.',
      '- Multiple agents can share the same project.',
    ].join('\n'),
  },
  {
    id: 'export-import-notebooks',
    title: 'Export and Import Notebooks',
    description: 'Export a chat session as a portable notebook, then import it into another account.',
    difficulty: 'intermediate',
    content: [
      '## Export and Import Notebooks',
      '',
      'Notebooks are portable snapshots of chat sessions, including messages and artifacts.',
      '',
      '### 1. List available sessions',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/sessions" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "sessions": [',
      '      {',
      '        "sessionId": "sess_abc123",',
      '        "title": "Q4 Revenue Analysis",',
      '        "messageCount": 14,',
      '        "createdAt": "2026-03-10T12:00:00.000Z"',
      '      }',
      '    ]',
      '  }',
      '}',
      '```',
      '',
      '### 2. Export a session as a notebook',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/sessions/$SESSION_ID/export" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -o notebook-export.json',
      '```',
      '',
      '**Exported file structure:**',
      '',
      '```json',
      '{',
      '  "version": "1.0",',
      '  "exportedAt": "2026-03-11T00:00:00.000Z",',
      '  "session": {',
      '    "title": "Q4 Revenue Analysis",',
      '    "messages": [',
      '      {',
      '        "role": "user",',
      '        "content": "What drove Q4 revenue?",',
      '        "timestamp": "2026-03-10T12:01:00.000Z"',
      '      },',
      '      {',
      '        "role": "assistant",',
      '        "content": "Based on the attached reports...",',
      '        "timestamp": "2026-03-10T12:01:05.000Z",',
      '        "citations": [{ "fileId": "file_abc123", "chunk": 12 }]',
      '      }',
      '    ],',
      '    "artifacts": [',
      '      {',
      '        "artifactId": "art_001",',
      '        "type": "code",',
      '        "title": "revenue_chart.py",',
      '        "content": "import matplotlib..."',
      '      }',
      '    ]',
      '  }',
      '}',
      '```',
      '',
      '### 3. Import a notebook into another account',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/sessions/import" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      '  -d @notebook-export.json',
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "sessionId": "sess_new789",',
      '    "title": "Q4 Revenue Analysis",',
      '    "messageCount": 14,',
      '    "artifactCount": 1,',
      '    "importedAt": "2026-03-11T00:05:00.000Z"',
      '  }',
      '}',
      '```',
      '',
      '### 4. List artifacts in an imported session',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/sessions/$SESSION_ID/artifacts" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '### Tips',
      '',
      '- Exported notebooks are self-contained JSON; they can be version-controlled or shared.',
      '- Artifacts (code, charts, tables) are included in the export automatically.',
      '- File attachments are referenced by ID; the recipient needs access to the same files or must re-upload.',
      '- Import creates a new session; it never overwrites existing data.',
    ].join('\n'),
  },
  {
    id: 'api-key-management',
    title: 'Full API Key Management',
    description:
      'Create API keys with scoped permissions, use them for programmatic access, monitor usage, and rotate keys.',
    difficulty: 'advanced',
    content: [
      '## Full API Key Management',
      '',
      `API keys provide programmatic access to ${getBrandName()}. This recipe covers the full`,
      'lifecycle: creation, scoping, usage monitoring, and rotation.',
      '',
      '### 1. Create an API key with scoped permissions',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/api-keys" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "name": "CI Pipeline Key",',
      '    "scopes": ["chat:write", "files:read", "files:write", "projects:read"],',
      '    "expiresInDays": 90',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "apiKeyId": "key_abc123",',
      '    "name": "CI Pipeline Key",',
      '    "key": "b4m_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",',
      '    "scopes": ["chat:write", "files:read", "files:write", "projects:read"],',
      '    "expiresAt": "2026-06-09T00:00:00.000Z",',
      '    "createdAt": "2026-03-11T00:00:00.000Z"',
      '  }',
      '}',
      '```',
      '',
      '> **Important:** The full key value is only returned at creation time. Store it securely.',
      '',
      '### 2. Use the new key for programmatic access',
      '',
      '```bash',
      'export B4M_CI_KEY="b4m_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"',
      '',
      'curl -s "$B4M_BASE_URL/api/settings/serverStatus" \\',
      '  -H "X-API-Key: $B4M_CI_KEY"',
      '```',
      '',
      'If the key lacks the required scope, you get:',
      '',
      '```json',
      '{',
      '  "success": false,',
      '  "error": "Insufficient permissions. Required scope: admin:read"',
      '}',
      '```',
      '',
      '### 3. List all API keys',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/api-keys" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "keys": [',
      '      {',
      '        "apiKeyId": "key_abc123",',
      '        "name": "CI Pipeline Key",',
      '        "scopes": ["chat:write", "files:read", "files:write", "projects:read"],',
      '        "lastUsedAt": "2026-03-11T08:30:00.000Z",',
      '        "usageCount": 142,',
      '        "expiresAt": "2026-06-09T00:00:00.000Z"',
      '      }',
      '    ]',
      '  }',
      '}',
      '```',
      '',
      '### 4. Monitor key usage',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/api-keys/$KEY_ID/usage" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "apiKeyId": "key_abc123",',
      '    "totalRequests": 142,',
      '    "last24h": 37,',
      '    "last7d": 98,',
      '    "topEndpoints": [',
      '      { "endpoint": "POST /api/chat", "count": 89 },',
      '      { "endpoint": "GET /api/files", "count": 31 },',
      '      { "endpoint": "POST /api/files/presigned-url", "count": 22 }',
      '    ]',
      '  }',
      '}',
      '```',
      '',
      '### 5. Rotate a key',
      '',
      'Rotation creates a new key and invalidates the old one:',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/api-keys/$KEY_ID/rotate" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json"',
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "apiKeyId": "key_new456",',
      '    "name": "CI Pipeline Key",',
      '    "key": "b4m_live_yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",',
      '    "previousKeyId": "key_abc123",',
      '    "previousKeyInvalidatedAt": "2026-03-11T12:00:00.000Z",',
      '    "scopes": ["chat:write", "files:read", "files:write", "projects:read"],',
      '    "expiresAt": "2026-06-09T00:00:00.000Z"',
      '  }',
      '}',
      '```',
      '',
      '### 6. Revoke a key',
      '',
      '```bash',
      'curl -X DELETE "$B4M_BASE_URL/api/api-keys/$KEY_ID" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '### Tips',
      '',
      '- Use the principle of least privilege: only grant scopes each key actually needs.',
      '- Set expiration dates on all keys; avoid permanent keys in production.',
      '- Monitor usage regularly; unexpected spikes may indicate a compromised key.',
      '- Rotate keys on a schedule (e.g., every 90 days) and immediately after any suspected leak.',
      '- The full key value is only shown once at creation or rotation. Store it in a secrets manager.',
    ].join('\n'),
  },
];
