// brand externalized
import { getBrandName } from '@client/config/general';

export interface CookbookRecipe {
  id: string;
  title: string;
  description: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  content: string; // markdown
}

export const API_COOKBOOK_INTRO: string =
  `${getBrandName()}'s API Cookbook is a collection of practical, copy-paste-ready recipes ` +
  'for common integration tasks. Each recipe walks through a real workflow end-to-end ' +
  'with curl examples, expected responses, and tips for production use. ' +
  'Set `B4M_API_KEY` and `B4M_BASE_URL` in your environment before running any recipe.';

export const COOKBOOK_RECIPES: CookbookRecipe[] = [
  // Keep in sync with the "Grounded answer" section of apps/client/public/llms.txt.
  {
    id: 'lake-grounded-answer',
    title: 'Get a Lake-Grounded Answer',
    description: 'Four calls: list your data lakes, open a session on one, ask a question, and poll for the answer.',
    difficulty: 'beginner',
    content: [
      '## Get a Lake-Grounded Answer',
      '',
      'Answer a question from the files in a data lake. The key needs `datalake:read`, `notebooks:write`',
      'and `ai:chat` (`ai:chat` also covers the poll). Send it as `Authorization: Bearer $B4M_API_KEY`.',
      '',
      '### 1. List your data lakes',
      '',
      '```bash',
      'curl "$B4M_BASE_URL/api/v1/data-lakes" \\',
      '  -H "Authorization: Bearer $B4M_API_KEY"',
      '```',
      '',
      '```json',
      '{',
      '  "data": [{ "id": "665f1c...", "name": "Product docs", "slug": "product-docs", "status": "active" }],',
      '  "next_cursor": null',
      '}',
      '```',
      '',
      'Pick the lake `id`. When `next_cursor` is not `null`, pass it back as `?cursor=` for the next page.',
      'A 403 means the key lacks `datalake:read` or Data Lakes are disabled on this deployment.',
      '',
      '### 2. Create a session on that lake',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/v1/sessions" \\',
      '  -H "Authorization: Bearer $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      '  -d \'{"name": "Lake Q&A", "dataLakeId": "665f1c..."}\'',
      '```',
      '',
      'Keep the response `id`: it is the session id. `dataLakeId` scopes retrieval to the lake and turns on',
      'forced retrieval, so there is no need to send `forceKnowledgeRetrieval`. A lake you cannot reach is a 404.',
      '',
      '### 3. Ask the question',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/chat" \\',
      '  -H "Authorization: Bearer $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      '  -d \'{"sessionId": "<session id>", "message": "What does the refund policy say?"}\'',
      '```',
      '',
      '```json',
      '{ "id": "quest_123", "status": "queued", "sessionId": "<session id>", "tracking_info": { "quest_id": "quest_123" } }',
      '```',
      '',
      'Read `tracking_info.quest_id`.',
      '',
      '### 4. Poll for the answer',
      '',
      '```bash',
      'curl "$B4M_BASE_URL/api/v1/quests/<quest_id>" \\',
      '  -H "Authorization: Bearer $B4M_API_KEY"',
      '```',
      '',
      '```json',
      '{ "id": "quest_123", "status": "done", "type": "message", "reply": null, "replies": ["<think>...</think>", "The refund policy allows..."] }',
      '```',
      '',
      '- `pending` or `running`: wait a second or two and poll again. `done` or `stopped`: stop polling.',
      '- Check for failure first: `type: "error"` (with `errorCode` when it is classified) or a `stopped`',
      '  status is a failed turn, not an answer. A run that died part-way still polls back as `done`, with',
      '  `promptMeta.finishReason` set to `timeout` or `abandoned`: treat that text as partial.',
      '- `replies[]` holds content slots, not separate answers. The answer is every entry concatenated in order (no separator),',
      '  with any `<think>...</think>` blocks removed. If `replies` is empty, use `reply` (it can be `null`).',
      '- Polling does not count against the daily key quota.',
      '',
      '### Tips',
      '',
      '- Every other field is optional. Worth knowing on `POST /api/chat`: `model`, `max_tokens`, and',
      '  `toolMode` (`fast` or `smart`).',
      '- On session create, `knowledgeIds` attaches individual files but does not force retrieval on its',
      '  own; pair it with `forceKnowledgeRetrieval: true`. For a whole lake, use `dataLakeId` as above.',
    ].join('\n'),
  },
  {
    id: 'start-chat-session',
    title: 'Start a Chat Session',
    description: 'Send a message to the LLM via the Chat API, with model selection and streaming options.',
    difficulty: 'beginner',
    content: [
      '## Start a Chat Session',
      '',
      `The Chat API is the primary way to interact with LLMs through ${getBrandName()}.`,
      'You can choose a model, send a user message, and optionally stream the response.',
      '',
      '### 1. Send a non-streaming chat message',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/chat" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "message": "Summarize the key benefits of RAG pipelines.",',
      '    "model": "gpt-4o",',
      '    "stream": false',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "sessionId": "sess_abc123",',
      '    "messageId": "msg_def456",',
      '    "content": "RAG pipelines combine retrieval with generation to...",',
      '    "model": "gpt-4o",',
      '    "usage": {',
      '      "promptTokens": 24,',
      '      "completionTokens": 180,',
      '      "totalTokens": 204',
      '    }',
      '  }',
      '}',
      '```',
      '',
      '### 2. Stream a chat response',
      '',
      '```bash',
      'curl -N -X POST "$B4M_BASE_URL/api/chat" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "message": "Write a haiku about distributed systems.",',
      '    "model": "gpt-4o",',
      '    "stream": true',
      "  }'",
      '```',
      '',
      'Streamed responses arrive as Server-Sent Events (SSE). Each chunk looks like:',
      '',
      '```',
      'data: {"delta":"Packets ","messageId":"msg_xyz"}',
      'data: {"delta":"travel far\\n","messageId":"msg_xyz"}',
      'data: [DONE]',
      '```',
      '',
      '### 3. Continue a conversation',
      '',
      'Pass the `sessionId` from the first response to continue the thread:',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/chat" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "sessionId": "sess_abc123",',
      '    "message": "Now explain that in simpler terms.",',
      '    "model": "gpt-4o",',
      '    "stream": false',
      "  }'",
      '```',
      '',
      '### Tips',
      '',
      '- Omit `model` to use the system default.',
      '- Set `stream: true` for real-time UX in user-facing applications.',
      '- The `sessionId` persists conversation history server-side.',
    ].join('\n'),
  },
  {
    id: 'upload-vectorize-document',
    title: 'Upload and Vectorize a Document',
    description: 'Create a presigned upload URL, push a file to S3, and verify chunking and vectorization.',
    difficulty: 'beginner',
    content: [
      '## Upload and Vectorize a Document',
      '',
      `${getBrandName()} ingests documents by uploading to S3, then automatically chunking and`,
      'vectorizing the content so it can be used for RAG queries.',
      '',
      '### 1. Request a presigned upload URL',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/v1/files" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "file_name": "quarterly-report.pdf",',
      '    "mime_type": "application/pdf",',
      '    "file_size": 482133',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "id": "file_abc123",',
      '  "upload_url": "https://s3.amazonaws.com/...",',
      '  "upload_url_expires_at": "2026-01-01T00:15:00.000Z"',
      '}',
      '```',
      '',
      'Use `id` as `$FILE_ID` in the steps below.',
      '',
      '### 2. Upload the file to S3',
      '',
      'Send no `Authorization` header; the URL signature is the credential. The `Content-Type`',
      'must match the `mime_type` from step 1.',
      '',
      '```bash',
      'curl -X PUT "<upload_url from step 1>" \\',
      '  -H "Content-Type: application/pdf" \\',
      '  --data-binary @quarterly-report.pdf',
      '```',
      '',
      'Chunking and vectorization start automatically once the upload lands. There is no separate',
      'ingest call.',
      '',
      '### 3. Check vectorization status',
      '',
      'This uses `/api/files/$FILE_ID`, not `/api/v1/files/$FILE_ID`: the v1 endpoint reports only',
      'moderation and download state, not chunking. The same `id` works on both, but this route',
      'returns the full file record, so its fields are camelCase.',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/files/$FILE_ID" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '**Response when complete** (abridged; the full file record is returned):',
      '',
      '```json',
      '{',
      '  "id": "file_abc123",',
      '  "fileName": "quarterly-report.pdf",',
      '  "isChunking": false,',
      '  "isVectorizing": false,',
      '  "chunkCount": 47,',
      '  "vectorizedChunkCount": 47,',
      '  "chunkEmbeddingModelStampedAt": "2026-01-01T00:01:12.000Z"',
      '}',
      '```',
      '',
      'The file is ready for retrieval once `chunkEmbeddingModelStampedAt` is set. `vectorized: true`',
      'alone is not a completion signal: it flips as soon as the first chunk is embedded.',
      '',
      '### 4. Re-run ingestion (optional)',
      '',
      'If the deployment has auto-chunking turned off, or the file finished with `chunkCount: 0`',
      'after a failed extraction, reset and re-queue it (requires `files:write`):',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/files/reprocess" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      '  -d "{ \\"fabFileId\\": \\"$FILE_ID\\" }"',
      '```',
      '',
      'Returns `{ "messageId": "..." }` once the file is queued, then poll step 3 again.',
      '',
      '### Tips',
      '',
      '- Supported formats: PDF, TXT, CSV, JSON, DOCX, and more.',
      '- Large files are automatically split into chunks for efficient retrieval.',
      '- Vectorization runs asynchronously; poll the file status or listen for WebSocket events.',
      '- Once vectorized, the file is available for RAG queries in any chat session.',
    ].join('\n'),
  },
  {
    id: 'build-project-with-files-agents',
    title: 'Build a Project with Files and Agents',
    description: 'Create a project, attach files, configure an agent, and start a chat grounded in project context.',
    difficulty: 'intermediate',
    content: [
      '## Build a Project with Files and Agents',
      '',
      'Projects bundle files and agents into a shared context for focused AI interactions.',
      '',
      '### 1. Create a project',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/projects" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "name": "Q4 Analysis",',
      '    "description": "Quarterly financial analysis workspace"',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "projectId": "proj_abc123",',
      '    "name": "Q4 Analysis",',
      '    "description": "Quarterly financial analysis workspace",',
      '    "createdAt": "2026-03-11T00:00:00.000Z"',
      '  }',
      '}',
      '```',
      '',
      '### 2. Attach files to the project',
      '',
      'Upload files first (see the Upload recipe), then attach them:',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/projects/$PROJECT_ID/files" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "fileIds": ["file_abc123", "file_def456"]',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "projectId": "proj_abc123",',
      '    "attachedFiles": 2,',
      '    "totalFiles": 2',
      '  }',
      '}',
      '```',
      '',
      '### 3. Create an agent for the project',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/agents" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "name": "Financial Analyst",',
      '    "systemPrompt": "You are a financial analyst. Use the attached quarterly reports to answer questions with specific data citations.",',
      '    "model": "gpt-4o",',
      '    "projectId": "proj_abc123"',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "agentId": "agent_xyz789",',
      '    "name": "Financial Analyst",',
      '    "projectId": "proj_abc123"',
      '  }',
      '}',
      '```',
      '',
      '### 4. Chat with project context',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/chat" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "message": "What were our top 3 revenue drivers in Q4?",',
      '    "agentId": "agent_xyz789",',
      '    "projectId": "proj_abc123",',
      '    "stream": false',
      "  }'",
      '```',
      '',
      'The response will include citations from the attached files.',
      '',
      '### Tips',
      '',
      '- Files must be vectorized before they contribute to RAG responses.',
      '- Agents inherit the project file context automatically.',
      '- You can attach or detach files from a project at any time; new chats pick up the changes.',
      '- Multiple agents can share the same project.',
    ].join('\n'),
  },
  {
    id: 'export-import-notebooks',
    title: 'Export and Import Notebooks',
    description: 'Export a chat session as a portable notebook, then import it into another account.',
    difficulty: 'intermediate',
    content: [
      '## Export and Import Notebooks',
      '',
      'Notebooks are portable snapshots of chat sessions, including messages and artifacts.',
      '',
      '### 1. List available sessions',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/sessions" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "sessions": [',
      '      {',
      '        "sessionId": "sess_abc123",',
      '        "title": "Q4 Revenue Analysis",',
      '        "messageCount": 14,',
      '        "createdAt": "2026-03-10T12:00:00.000Z"',
      '      }',
      '    ]',
      '  }',
      '}',
      '```',
      '',
      '### 2. Export a session as a notebook',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/sessions/$SESSION_ID/export" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -o notebook-export.json',
      '```',
      '',
      '**Exported file structure:**',
      '',
      '```json',
      '{',
      '  "version": "1.0",',
      '  "exportedAt": "2026-03-11T00:00:00.000Z",',
      '  "session": {',
      '    "title": "Q4 Revenue Analysis",',
      '    "messages": [',
      '      {',
      '        "role": "user",',
      '        "content": "What drove Q4 revenue?",',
      '        "timestamp": "2026-03-10T12:01:00.000Z"',
      '      },',
      '      {',
      '        "role": "assistant",',
      '        "content": "Based on the attached reports...",',
      '        "timestamp": "2026-03-10T12:01:05.000Z",',
      '        "citations": [{ "fileId": "file_abc123", "chunk": 12 }]',
      '      }',
      '    ],',
      '    "artifacts": [',
      '      {',
      '        "artifactId": "art_001",',
      '        "type": "code",',
      '        "title": "revenue_chart.py",',
      '        "content": "import matplotlib..."',
      '      }',
      '    ]',
      '  }',
      '}',
      '```',
      '',
      '### 3. Import a notebook into another account',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/sessions/import" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      '  -d @notebook-export.json',
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "sessionId": "sess_new789",',
      '    "title": "Q4 Revenue Analysis",',
      '    "messageCount": 14,',
      '    "artifactCount": 1,',
      '    "importedAt": "2026-03-11T00:05:00.000Z"',
      '  }',
      '}',
      '```',
      '',
      '### 4. List artifacts in an imported session',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/sessions/$SESSION_ID/artifacts" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '### Tips',
      '',
      '- Exported notebooks are self-contained JSON; they can be version-controlled or shared.',
      '- Artifacts (code, charts, tables) are included in the export automatically.',
      '- File attachments are referenced by ID; the recipient needs access to the same files or must re-upload.',
      '- Import creates a new session; it never overwrites existing data.',
    ].join('\n'),
  },
  {
    id: 'api-key-management',
    title: 'Full API Key Management',
    description:
      'Create API keys with scoped permissions, use them for programmatic access, monitor usage, and rotate keys.',
    difficulty: 'advanced',
    content: [
      '## Full API Key Management',
      '',
      `API keys provide programmatic access to ${getBrandName()}. This recipe covers the full`,
      'lifecycle: creation, scoping, usage monitoring, and rotation.',
      '',
      '### 1. Create an API key with scoped permissions',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/api-keys" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json" \\',
      "  -d '{",
      '    "name": "CI Pipeline Key",',
      '    "scopes": ["chat:write", "files:read", "files:write", "projects:read"],',
      '    "expiresInDays": 90',
      "  }'",
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "apiKeyId": "key_abc123",',
      '    "name": "CI Pipeline Key",',
      '    "key": "b4m_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",',
      '    "scopes": ["chat:write", "files:read", "files:write", "projects:read"],',
      '    "expiresAt": "2026-06-09T00:00:00.000Z",',
      '    "createdAt": "2026-03-11T00:00:00.000Z"',
      '  }',
      '}',
      '```',
      '',
      '> **Important:** The full key value is only returned at creation time. Store it securely.',
      '',
      '### 2. Use the new key for programmatic access',
      '',
      '```bash',
      'export B4M_CI_KEY="b4m_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"',
      '',
      'curl -s "$B4M_BASE_URL/api/settings/serverStatus" \\',
      '  -H "X-API-Key: $B4M_CI_KEY"',
      '```',
      '',
      'If the key lacks the required scope, you get:',
      '',
      '```json',
      '{',
      '  "success": false,',
      '  "error": "Insufficient permissions. Required scope: admin:read"',
      '}',
      '```',
      '',
      '### 3. List all API keys',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/api-keys" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "keys": [',
      '      {',
      '        "apiKeyId": "key_abc123",',
      '        "name": "CI Pipeline Key",',
      '        "scopes": ["chat:write", "files:read", "files:write", "projects:read"],',
      '        "lastUsedAt": "2026-03-11T08:30:00.000Z",',
      '        "usageCount": 142,',
      '        "expiresAt": "2026-06-09T00:00:00.000Z"',
      '      }',
      '    ]',
      '  }',
      '}',
      '```',
      '',
      '### 4. Monitor key usage',
      '',
      '```bash',
      'curl -s "$B4M_BASE_URL/api/api-keys/$KEY_ID/usage" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "apiKeyId": "key_abc123",',
      '    "totalRequests": 142,',
      '    "last24h": 37,',
      '    "last7d": 98,',
      '    "topEndpoints": [',
      '      { "endpoint": "POST /api/chat", "count": 89 },',
      '      { "endpoint": "GET /api/files", "count": 31 },',
      '      { "endpoint": "POST /api/files/presigned-url", "count": 22 }',
      '    ]',
      '  }',
      '}',
      '```',
      '',
      '### 5. Rotate a key',
      '',
      'Rotation creates a new key and invalidates the old one:',
      '',
      '```bash',
      'curl -X POST "$B4M_BASE_URL/api/api-keys/$KEY_ID/rotate" \\',
      '  -H "X-API-Key: $B4M_API_KEY" \\',
      '  -H "Content-Type: application/json"',
      '```',
      '',
      '**Response shape:**',
      '',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "apiKeyId": "key_new456",',
      '    "name": "CI Pipeline Key",',
      '    "key": "b4m_live_yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",',
      '    "previousKeyId": "key_abc123",',
      '    "previousKeyInvalidatedAt": "2026-03-11T12:00:00.000Z",',
      '    "scopes": ["chat:write", "files:read", "files:write", "projects:read"],',
      '    "expiresAt": "2026-06-09T00:00:00.000Z"',
      '  }',
      '}',
      '```',
      '',
      '### 6. Revoke a key',
      '',
      '```bash',
      'curl -X DELETE "$B4M_BASE_URL/api/api-keys/$KEY_ID" \\',
      '  -H "X-API-Key: $B4M_API_KEY"',
      '```',
      '',
      '### Tips',
      '',
      '- Use the principle of least privilege: only grant scopes each key actually needs.',
      '- Set expiration dates on all keys; avoid permanent keys in production.',
      '- Monitor usage regularly; unexpected spikes may indicate a compromised key.',
      '- Rotate keys on a schedule (e.g., every 90 days) and immediately after any suspected leak.',
      '- The full key value is only shown once at creation or rotation. Store it in a secrets manager.',
    ].join('\n'),
  },
];
