// brand externalized
import { getBrandName } from '@client/config/general';

/** `baseUrl` is the deployment's origin, so the examples are runnable as copied. */
const quickstartLines = (baseUrl: string): string[] => [
  `# ${getBrandName()} API Quickstart`,
  '',
  'One-page cheat sheet for Claude Code instances (and humans) building on the B4M platform.',
  '',
  '---',
  '',
  '## Setup',
  '',
  'Add these to your `.env` (or export in your shell):',
  '',
  '```bash',
  'export B4M_API_KEY="b4m_live_your_key_here"',
  `export B4M_BASE_URL="${baseUrl}"`,
  '```',
  '',
  'Every curl example below assumes these two variables are set.',
  '',
  '---',
  '',
  '## Health Check (one-liner)',
  '',
  '```bash',
  'curl -s -H "Authorization: Bearer $B4M_API_KEY" $B4M_BASE_URL/api/settings/serverStatus',
  '```',
  '',
  'Expected response:',
  '',
  '```json',
  '{',
  '  "success": true,',
  '  "data": {',
  '    "status": "ok",',
  '    "version": "x.y.z",',
  '    "uptime": 123456',
  '  }',
  '}',
  '```',
  '',
  'If you get `401` or `403`, your API key is invalid or expired.',
  '',
  '---',
  '',
  '## The 5 APIs You Will Use Most',
  '',
  '### 1. Chat',
  '',
  'Send a message and get an LLM response.',
  '',
  '```bash',
  'curl -X POST "$B4M_BASE_URL/api/chat" \\',
  '  -H "Authorization: Bearer $B4M_API_KEY" \\',
  '  -H "Content-Type: application/json" \\',
  '  -d \'{ "message": "Hello", "model": "gpt-4o", "stream": false }\'',
  '```',
  '',
  'Key fields: `message` (required), `model` (optional, defaults to system default), `stream` (boolean), `sessionId` (to continue a conversation).',
  '',
  '### 2. Files',
  '',
  'Upload, ingest, and query documents.',
  '',
  '```bash',
  '# Register the file and get a presigned upload URL (returns `id` and `upload_url`)',
  'curl -X POST "$B4M_BASE_URL/api/v1/files" \\',
  '  -H "Authorization: Bearer $B4M_API_KEY" \\',
  '  -H "Content-Type: application/json" \\',
  '  -d \'{ "file_name": "report.pdf", "mime_type": "application/pdf", "file_size": 482133 }\'',
  '',
  '# Upload to the returned URL (no Authorization header; the URL signature is the credential)',
  'curl -X PUT "<upload_url>" -H "Content-Type: application/pdf" --data-binary @report.pdf',
  '',
  '# Check status: chunking + vectorization start on upload, and the file is',
  '# searchable once `chunkEmbeddingModelStampedAt` is set. /api/v1/files/$FILE_ID has no',
  '# chunking state, so this uses the full file record (camelCase fields) instead',
  'curl -s "$B4M_BASE_URL/api/files/$FILE_ID" -H "Authorization: Bearer $B4M_API_KEY"',
  '',
  '# Re-run chunking + vectorization (only needed if auto-chunk is off or extraction failed)',
  'curl -X POST "$B4M_BASE_URL/api/files/reprocess" \\',
  '  -H "Authorization: Bearer $B4M_API_KEY" \\',
  '  -H "Content-Type: application/json" \\',
  '  -d "{ \\"fabFileId\\": \\"$FILE_ID\\" }"',
  '```',
  '',
  '### 3. Projects',
  '',
  'Group files and agents into a shared workspace.',
  '',
  '```bash',
  '# Create a project',
  'curl -X POST "$B4M_BASE_URL/api/projects" \\',
  '  -H "Authorization: Bearer $B4M_API_KEY" \\',
  '  -H "Content-Type: application/json" \\',
  '  -d \'{ "name": "My Project", "description": "Research workspace" }\'',
  '',
  '# Attach files',
  'curl -X POST "$B4M_BASE_URL/api/projects/$PROJECT_ID/files" \\',
  '  -H "Authorization: Bearer $B4M_API_KEY" \\',
  '  -H "Content-Type: application/json" \\',
  '  -d \'{ "fileIds": ["file_abc123"] }\'',
  '```',
  '',
  '### 4. Agents',
  '',
  'Create custom AI personas with system prompts tied to projects.',
  '',
  '```bash',
  'curl -X POST "$B4M_BASE_URL/api/agents" \\',
  '  -H "Authorization: Bearer $B4M_API_KEY" \\',
  '  -H "Content-Type: application/json" \\',
  '  -d \'{ "name": "Analyst", "systemPrompt": "You are a data analyst.", "model": "gpt-4o", "projectId": "proj_abc123" }\'',
  '```',
  '',
  'Then pass `agentId` and `projectId` to the Chat API to use project-grounded responses.',
  '',
  '### 5. Settings',
  '',
  'Server status, feature flags, and configuration.',
  '',
  '```bash',
  '# Server status (health check)',
  'curl -s "$B4M_BASE_URL/api/settings/serverStatus" -H "Authorization: Bearer $B4M_API_KEY"',
  '',
  '# List available models',
  'curl -s "$B4M_BASE_URL/api/models" -H "Authorization: Bearer $B4M_API_KEY"',
  '```',
  '',
  '---',
  '',
  '## Handling Empty and Error Responses',
  '',
  'All B4M endpoints return a consistent envelope:',
  '',
  '```json',
  '{ "success": true, "data": { ... } }',
  '```',
  '',
  'or on failure:',
  '',
  '```json',
  '{ "success": false, "error": "Human-readable message" }',
  '```',
  '',
  'Common status codes:',
  '',
  '- **200** -- Success.',
  '- **400** -- Bad request. Check the `error` field for validation details.',
  '- **401** -- Unauthorized. API key missing or expired.',
  '- **403** -- Forbidden. Key lacks the required scope.',
  '- **404** -- Resource not found.',
  '- **429** -- Rate limited. Back off and retry.',
  '- **500** -- Server error. Retry with exponential backoff; report if persistent.',
  '',
  'When a list endpoint returns no results, `data` will contain an empty array, not `null`:',
  '',
  '```json',
  '{ "success": true, "data": { "sessions": [] } }',
  '```',
  '',
  '---',
  '',
  '## Full Reference',
  '',
  'For complete endpoint documentation, request/response schemas, and advanced recipes,',
  'see the **API Reference** tab in the Admin panel or the API Cookbook.',
];

export const getQuickstartContent = (baseUrl: string): string => quickstartLines(baseUrl).join('\n');
