import { GetParameterCommand, SSMClient } from '@aws-sdk/client-ssm';
import { userRepository } from '@bike4mind/database';
import { userService } from '@bike4mind/services';
import { Logger } from '@bike4mind/observability';
import users from './users.json';

const createUser = userService.createUser;

const SUPER_ADMIN_EMAIL = 'test@test.com';

// Standing QA login accounts for passwordless (OTC) testing on PREVIEW envs.
// This seeder only ever runs on previews (seedDatabase.ts hard-refuses any other
// stage), so these never reach staging/prod. The `-e2e@test.com` addresses make
// their one-time codes retrievable via the gated /api/test/otc-code endpoint
// (enabled on every preview), so QA can sign in on ANY PR preview with no per-env
// account creation. Interim until edge-gated open signup lets QA self-register.
const QA_ACCOUNTS = [
  { username: 'qaadmin', email: 'qa-admin-e2e@test.com', name: 'QA Admin', isAdmin: true },
  { username: 'qauser', email: 'qa-user-e2e@test.com', name: 'QA User', isAdmin: false },
];

// KMS-encrypted SecureString in bike4mind-dev us-east-2, provisioned by b4m-infra.
// Value is generated by tofu random_password - no literal ever exists in source or config.
const SEEDER_PASSWORD_PARAM = '/b4m/ci/seeder-default-password';

async function fetchSeederPassword(): Promise<string> {
  const client = new SSMClient({ region: 'us-east-2' });
  let res;
  try {
    res = await client.send(new GetParameterCommand({ Name: SEEDER_PASSWORD_PARAM, WithDecryption: true }));
  } catch (e: unknown) {
    throw new Error(
      `Failed to read seeder password from SSM (${SEEDER_PASSWORD_PARAM} in us-east-2). ` +
        `Ensure the parameter exists and the DatabaseSeeder role has ssm:GetParameter on it. ` +
        `Underlying: ${e instanceof Error ? e.message : String(e)}`
    );
  }
  const password = res.Parameter?.Value;
  if (!password) {
    throw new Error(
      'Seeder password missing from SSM. Ensure /b4m/ci/seeder-default-password exists in us-east-2 ' +
        'and the DatabaseSeeder role has ssm:GetParameter on it.'
    );
  }
  return password;
}

export class UserSeeder {
  constructor(private readonly logger: Logger) {}

  async seed() {
    const password = await fetchSeederPassword();

    this.logger.info(`Processing ${users.length} users...`);

    const newUsers = await Promise.all(
      users.map(async user => {
        try {
          // Check if user already exists by email
          const existingUser = await userRepository.findOne({ email: user.email });
          if (existingUser) {
            this.logger.info(`User already exists: ${user.email}, skipping...`);
            return existingUser;
          }

          const newUser = await createUser(
            {
              username: user.username,
              email: user.email,
              name: user.name || user.username,
              isAdmin: user.isAdmin,
              emailVerified: true,
              initialCredits: 10_000,
              record: {
                password,
              },
            },
            {
              db: {
                users: userRepository,
              },
            }
          );

          return newUser;
        } catch (e: unknown) {
          console.log(`Error on creating user: ${user.email} - ${e instanceof Error ? e.message : 'Unknown error'}`);
        }

        return null;
      })
    );

    const processedUsers = newUsers.filter(user => user !== null);

    this.logger.info(`Processed ${processedUsers.length} users`);
    this.logger.info(`Emails: ${processedUsers.map(user => user.email).join(', ')}`);
    this.logger.info(`Processing super admin with email: ${SUPER_ADMIN_EMAIL}`);

    try {
      // Check if super admin already exists
      const existingSuperAdmin = await userRepository.findOne({ email: SUPER_ADMIN_EMAIL });
      if (existingSuperAdmin) {
        this.logger.info(`Super admin already exists: ${SUPER_ADMIN_EMAIL}, skipping...`);
      } else {
        // Create super admin
        await createUser(
          {
            username: 'superadmin',
            email: SUPER_ADMIN_EMAIL,
            name: 'Super Admin',
            record: {
              password,
            },
            tags: ['Developer', 'Analyst'],
            isAdmin: true,
            emailVerified: true,
            initialCredits: 10_000,
          },
          {
            db: {
              users: userRepository,
            },
          }
        );
        this.logger.info(`Created super admin: ${SUPER_ADMIN_EMAIL}`);
      }
    } catch (e: unknown) {
      console.log(`Error on creating user: ${SUPER_ADMIN_EMAIL} - ${e instanceof Error ? e.message : 'Unknown error'}`);
    }

    // Standing QA passwordless-login accounts (preview-only - see QA_ACCOUNTS).
    for (const qa of QA_ACCOUNTS) {
      try {
        const existing = await userRepository.findOne({ email: qa.email });
        if (existing) {
          this.logger.info(`QA account already exists: ${qa.email}, skipping...`);
          continue;
        }
        await createUser(
          {
            username: qa.username,
            email: qa.email,
            name: qa.name,
            // Passwordless: sign-in is via OTC. The password field is unused for login
            // but createUser requires a record; reuse the seeder password.
            record: { password },
            tags: ['Developer', 'Analyst'],
            isAdmin: qa.isAdmin,
            emailVerified: true,
            initialCredits: 10_000,
          },
          { db: { users: userRepository } }
        );
        this.logger.info(`Created QA account: ${qa.email} (isAdmin: ${qa.isAdmin})`);
      } catch (e: unknown) {
        console.log(`Error on creating QA account: ${qa.email} - ${e instanceof Error ? e.message : 'Unknown error'}`);
      }
    }

    this.logger.info('Done');
  }
}
