import {
  Box,
  Button,
  FormControl,
  FormLabel,
  Input,
  Select,
  Option,
  Stack,
  Switch,
  Typography,
  Textarea,
  Card,
  CardContent,
  Divider,
  Tooltip,
  Chip,
  Avatar,
  Modal,
  ModalClose,
  ModalDialog,
  IconButton,
  useTheme,
} from '@mui/joy';
import { FC, useEffect, useState, useRef } from 'react';
import {
  gray,
  green,
  red,
  brand,
  blue,
  purple,
  gold,
  brandAlpha,
  blueAlpha,
  greenAlpha,
  purpleAlpha,
  orangeAlpha,
  cyanAlpha,
  blackAlpha,
  goldAlpha,
  whiteAlpha,
  grayAlpha,
} from '../../utils/themes/colors';
import { ResearchTaskExecutionType, ResearchTaskPeriodicFrequencyType, ResearchTaskType } from '@bike4mind/common';
import { useForm, Controller, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import {
  CreateResearchTaskInput,
  useCreateResearchTask,
  useGetResearchTask,
  useUpdateResearchTask,
} from '@client/app/hooks/data/researchTasks';
import { useGetFileTags, useCreateFileTag } from '@client/app/hooks/data/tag';
import DateTimePicker from '@client/app/components/common/fields/DateTimePicker';
import PopularTargetsModal from './PopularTargets/index';
import TagForm from '@client/app/components/Tag/Form';
import {
  Assignment,
  Description,
  Link,
  Explore,
  Schedule,
  AccessTime,
  EventRepeat,
  Save,
  Cancel,
  RocketLaunch,
  TrendingUp,
  Add,
  Delete,
  Search,
  Label,
  Tag,
} from '@mui/icons-material';
import { usePopularTargets } from '@client/app/components/ResearchTasks/PopularTargets/hooks';
import AutoFixHighIcon from '@mui/icons-material/AutoFixHigh';
import useRefineText from '@client/app/hooks/useRefineText';

interface ResearchTaskFormProps {
  onSubmit?: (taskId?: string) => void;
  onCancel?: () => void;
  taskId?: string;
  researchAgentId: string;
}

// Zod validation schema based on the create.ts schema
const researchTaskFormSchema = z
  .object({
    title: z.string().min(1, 'Title is required').min(3, 'Title must be at least 3 characters').max(100),
    description: z
      .string()
      .min(1, 'Description is required')
      .min(10, 'Description must be at least 10 characters')
      .max(500),
    type: z.enum(ResearchTaskType),
    executionType: z.enum(ResearchTaskExecutionType),
    urls: z.array(z.url('Please enter a valid URL')).optional().prefault([]),
    canDiscoverLinks: z.boolean().optional(),
    prompt: z.string().optional(),
    maxDepth: z.number().min(1, 'Max depth must be at least 1').max(10, 'Max depth cannot exceed 10').optional(),
    executionPeriodicStartAt: z.date().optional(),
    executionPeriodicEndAt: z.date().optional(),
    executionPeriodicFrequency: z.enum(ResearchTaskPeriodicFrequencyType).optional(),
    executionScheduledAt: z.date().optional(),
  })
  .refine(
    data => {
      // Validate URLs are required for SCRAPE type
      if (data.type === ResearchTaskType.SCRAPE) {
        return data.urls && data.urls.length > 0 && data.urls.every(url => url.trim() !== '');
      }
      return true;
    },
    {
      path: ['urls'],
      error: 'At least one URL is required for scrape tasks',
    }
  )
  .refine(
    data => {
      // Validate periodic execution dates
      if (data.executionType === ResearchTaskExecutionType.PERIODIC) {
        return data.executionPeriodicStartAt && data.executionPeriodicEndAt && data.executionPeriodicFrequency;
      }
      return true;
    },
    {
      path: ['executionPeriodicStartAt'],
      error: 'Start date, end date, and frequency are required for periodic tasks',
    }
  )
  .refine(
    data => {
      // Validate scheduled execution date
      if (data.executionType === ResearchTaskExecutionType.SCHEDULED) {
        return data.executionScheduledAt;
      }
      return true;
    },
    {
      path: ['executionScheduledAt'],
      error: 'Scheduled date is required for scheduled tasks',
    }
  );

const ResearchTaskForm: FC<ResearchTaskFormProps> = ({ onSubmit, onCancel, taskId, researchAgentId }) => {
  const isEditing = !!taskId;
  const theme = useTheme();
  const mode = theme.palette.mode;
  const [popularTargetsOpen, setPopularTargetsOpen] = useState(false);
  const [isShimmering, setIsShimmering] = useState(false);
  const [selectedTagId, setSelectedTagId] = useState<string>('');
  const [autoGeneratedTag, setAutoGeneratedTag] = useState<{
    name: string;
    icon: string;
    color: string;
  } | null>(null);
  const [isTagModalOpen, setIsTagModalOpen] = useState(false);
  const [titleManuallyEdited, setTitleManuallyEdited] = useState(false);
  const shimmerIntervalRef = useRef<NodeJS.Timeout | null>(null);

  const { data: existingTask } = useGetResearchTask(researchAgentId, taskId);
  const { data: availableTags = [], refetch: refetchTags } = useGetFileTags();
  const createTask = useCreateResearchTask();
  const updateTask = useUpdateResearchTask(taskId || '');
  const { mutateAsync: createTag, isPending: isCreatingTag } = useCreateFileTag();
  const setPopularTargetsState = usePopularTargets(s => s.setState);

  const { control, handleSubmit, watch, reset, setValue } = useForm<Omit<CreateResearchTaskInput, 'researchAgentId'>>({
    defaultValues: {
      type: ResearchTaskType.SCRAPE,
      title: '',
      description: '',
      executionType: ResearchTaskExecutionType.ON_DEMAND,
      urls: [''],
      canDiscoverLinks: true,
      prompt: '',
      maxDepth: 7,
    },
    resolver: zodResolver(researchTaskFormSchema as any),
  });

  const { fields, append, remove } = useFieldArray<Omit<CreateResearchTaskInput, 'researchAgentId'>>({
    control,
    name: 'urls' as never,
  });

  const taskType = watch('type');
  const executionType = watch('executionType');
  const currentUrls = watch('urls');
  const currentTitle = watch('title');
  const currentDescription = watch('description');
  const currentCanDiscoverLinks = watch('canDiscoverLinks');

  const firstUrl = currentUrls?.[0];

  // Function to fetch title from URL
  // const fetchTitleFromUrl = useCallback(
  //   async (url: string) => {
  //     try {
  //       const response = await fetch('/api/utils/fetchTitle', {
  //         method: 'POST',
  //         headers: {
  //           'Content-Type': 'application/json',
  //         },
  //         body: JSON.stringify({ url }),
  //       });

  //       if (response.ok) {
  //         const data = await response.json();
  //         if (data.success && data.title) {
  //           setValue('title', data.title);
  //         }
  //       }
  //     } catch (error) {
  //       console.error('Failed to fetch title from URL:', error);
  //     }
  //   },
  //   [setValue]
  // );

  // Auto-generate smart tag when URLs/title changes
  useEffect(() => {
    if (firstUrl && currentTitle && !selectedTagId) {
      const smartTag = generateSmartTag(firstUrl, currentTitle);
      setAutoGeneratedTag(smartTag);
    }
  }, [firstUrl, currentTitle, selectedTagId]);

  // TODO: disabled - the API does not exist and errors, and it fires on every keystroke. Needs debounce before re-enabling.
  // Auto-generate title from URL when URL changes (only if title is empty and not manually edited)
  // useEffect(() => {
  //   if (firstUrl && !isEditing && !titleManuallyEdited && (!currentTitle || currentTitle.trim() === '')) {
  //     fetchTitleFromUrl(firstUrl);
  //   }
  // }, [firstUrl, fetchTitleFromUrl, currentTitle, isEditing, titleManuallyEdited]);

  const generateSmartTag = (url: string, title: string) => {
    try {
      const domain = new URL(url).hostname.toLowerCase();

      // Domain-based smart tags
      const domainConfigs: Record<string, { icon: string; color: string; prefix: string }> = {
        'microsoft.com': { icon: '📘', color: '#0078d4', prefix: 'msft' },
        'nvidia.com': { icon: '🖥️', color: '#76b900', prefix: 'nvidia' },
        'apple.com': { icon: '🍎', color: '#007aff', prefix: 'apple' },
        'google.com': { icon: '🔍', color: '#4285f4', prefix: 'google' },
        'sec.gov': { icon: '🏛️', color: '#6b7280', prefix: 'sec' },
        'github.com': { icon: '💻', color: '#24292e', prefix: 'github' },
      };

      let config = Object.entries(domainConfigs).find(([key]) => domain.includes(key))?.[1];

      // Keyword-based fallbacks
      if (!config) {
        const titleLower = title.toLowerCase();
        if (titleLower.includes('earnings')) {
          config = { icon: '📊', color: green[400], prefix: 'earnings' };
        } else if (titleLower.includes('news')) {
          config = { icon: '📰', color: red[400], prefix: 'news' };
        } else {
          config = { icon: '📄', color: purple[300], prefix: 'research' };
        }
      }

      const date = new Date();
      const monthYear = `${(date.getMonth() + 1).toString().padStart(2, '0')}-${date.getFullYear().toString().slice(-2)}`;

      return {
        name: `${config.prefix}-${monthYear}`,
        icon: config.icon,
        color: config.color,
      };
    } catch {
      // Fallback for invalid URLs
      return {
        name: `research-${Date.now().toString().slice(-6)}`,
        icon: '📄',
        color: purple[300],
      };
    }
  };

  const handlePopularTargetSelect = (url: string, company: string, targetFieldIndex: number) => {
    // Update only the specific field index instead of replacing the entire array
    setValue(`urls.${targetFieldIndex}`, url);
    // Only update title if user hasn't manually edited it
    if (!titleManuallyEdited) {
      setValue('title', `${company} Latest Earnings Research`);
    }
    setPopularTargetsOpen(false);
    setPopularTargetsState({ searchTerm: '' });
  };

  useEffect(() => {
    if (isEditing && existingTask) {
      reset({
        type: existingTask.type,
        title: existingTask.title,
        description: existingTask.description,
        urls:
          'urls' in existingTask && existingTask.urls
            ? existingTask.urls
            : 'url' in existingTask && existingTask.url
              ? [existingTask.url]
              : [''],
        canDiscoverLinks: 'canDiscoverLinks' in existingTask ? existingTask.canDiscoverLinks : true,
        maxDepth: 'maxDepth' in existingTask ? existingTask.maxDepth : 7,
        executionType: existingTask.executionType,
        executionPeriodicFrequency:
          'executionPeriodicFrequency' in existingTask ? existingTask.executionPeriodicFrequency : undefined,
        executionPeriodicStartAt:
          'executionPeriodicStartAt' in existingTask ? existingTask.executionPeriodicStartAt : undefined,
        executionPeriodicEndAt:
          'executionPeriodicEndAt' in existingTask ? existingTask.executionPeriodicEndAt : undefined,
        executionScheduledAt: 'executionScheduledAt' in existingTask ? existingTask.executionScheduledAt : undefined,
      });
      // When editing existing task, consider title as manually edited to prevent auto-updates
      setTitleManuallyEdited(true);
    } else {
      // Reset manual edit flag for new tasks
      setTitleManuallyEdited(false);
    }
  }, [isEditing, existingTask, reset]);

  // Ensure at least one URL field is always present for SCRAPE tasks
  useEffect(() => {
    if (taskType === ResearchTaskType.SCRAPE && fields.length === 0) {
      append('');
    }
    // Only run when fields or taskType changes
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fields.length, taskType]);

  // Shimmer effect for popular targets button when URLs are empty
  useEffect(() => {
    const startShimmerInterval = () => {
      // Random interval between 5-7 seconds
      const randomInterval = Math.random() * 2000 + 5000; // 5000-7000ms

      shimmerIntervalRef.current = setTimeout(() => {
        setIsShimmering(true);

        // Stop shimmer after 1 second
        setTimeout(() => {
          setIsShimmering(false);
          if (!currentUrls || currentUrls.length === 0 || currentUrls.every(url => !url || url.trim() === '')) {
            startShimmerInterval(); // Restart the cycle if URLs are still empty
          }
        }, 1000);
      }, randomInterval);
    };

    if (shimmerIntervalRef.current) {
      clearTimeout(shimmerIntervalRef.current);
    }

    // Start shimmer cycle only if URLs are empty and we're in scrape mode
    if (
      (!currentUrls || currentUrls.length === 0 || currentUrls.every(url => !url || url.trim() === '')) &&
      taskType === ResearchTaskType.SCRAPE
    ) {
      startShimmerInterval();
    }

    return () => {
      if (shimmerIntervalRef.current) {
        clearTimeout(shimmerIntervalRef.current);
      }
    };
  }, [currentUrls, taskType]);

  const onFormSubmit = async (data: Omit<CreateResearchTaskInput, 'researchAgentId'>) => {
    try {
      const submitData: CreateResearchTaskInput = {
        ...data,
        researchAgentId,
        // Filter out empty URLs for scrape tasks
        urls: data.type === ResearchTaskType.SCRAPE ? data.urls?.filter(url => url && url.trim() !== '') : undefined,
        // Include tag information
        fileTagId: selectedTagId || undefined,
        autoGeneratedTag: !selectedTagId ? autoGeneratedTag || undefined : undefined,
        // Include deep research specific fields
        maxDepth: data.type === ResearchTaskType.DEEP_RESEARCH ? data.maxDepth : undefined,
      };

      if (isEditing) {
        await updateTask.mutateAsync(submitData);
        onSubmit?.(taskId);
      } else {
        const newTask = await createTask.mutateAsync(submitData);
        console.log(`🎯 Created new research task: ${newTask.title} (${newTask.id})`);
        onSubmit?.(newTask.id);
      }
    } catch (error) {
      console.error('Failed to submit task:', error);
    }
  };

  const isLoading = createTask.isPending || updateTask.isPending;

  return (
    <Box>
      {/* Header */}
      <Box sx={{ textAlign: 'center', mb: 3, mt: 0 }}>
        <Box
          sx={{
            display: 'flex',
            justifyContent: 'center',
            mb: 1.5,
            '& svg': {
              fontSize: 40,
              background: `linear-gradient(135deg, ${blue[400]} 0%, ${brand[500]} 50%, ${purple[500]} 100%)`,
              backgroundClip: 'text',
              WebkitBackgroundClip: 'text',
              color: 'transparent',
              filter: `drop-shadow(0 2px 4px ${blackAlpha[0][10]})`,
            },
          }}
        >
          {isEditing ? <Assignment /> : <RocketLaunch />}
        </Box>
        <Typography
          level="h4"
          sx={{
            background:
              mode === 'dark'
                ? `linear-gradient(135deg, ${gray[50]} 0%, ${gray[200]} 100%)`
                : `linear-gradient(135deg, ${gray[780]} 0%, ${gray[750]} 100%)`,
            backgroundClip: 'text',
            WebkitBackgroundClip: 'text',
            color: 'transparent',
            fontWeight: 700,
            letterSpacing: '-0.025em',
            mb: 0.5,
          }}
        >
          {isEditing ? 'Perfect Your Research Task' : 'Create a Research Task'}
        </Typography>
        <Typography level="body-sm" color="neutral" sx={{ mx: 'auto' }}>
          {isEditing
            ? 'Update your task details to keep your research flowing smoothly'
            : 'Set up intelligent automation to gather insights and data effortlessly'}
        </Typography>
      </Box>

      <form onSubmit={handleSubmit(onFormSubmit)}>
        {/* Four-Column Layout - Responsive */}
        <Box
          sx={{
            display: 'grid',
            gridTemplateColumns: { xs: '1fr', md: '1.2fr 1.5fr 1fr 1fr' },
            gap: { xs: 2.5, md: 3 },
            alignItems: 'start',
          }}
        >
          {/* Column 1 - Task Details */}
          <Stack spacing={2.5}>
            {/* Section Header */}
            <Box sx={{ mb: -1 }}>
              <Typography
                level="body-xs"
                sx={{
                  textTransform: 'uppercase',
                  letterSpacing: '0.1em',
                  color: 'primary.600',
                  fontWeight: 700,
                  display: 'flex',
                  alignItems: 'center',
                  gap: 0.5,
                }}
              >
                <Box sx={{ width: 4, height: 4, borderRadius: '50%', bgcolor: 'primary.500' }} />
                Step 1: Define Your Task
              </Typography>
            </Box>
            {/* Title and Description */}
            <Card
              variant="outlined"
              sx={{
                border: '2px solid',
                background: `linear-gradient(to bottom, ${blueAlpha[650][2]}, transparent)`,
                borderColor: grayAlpha[690][40],
                transition: 'all 0.2s ease',
                '&:hover': {
                  borderColor: grayAlpha[690][40],
                  boxShadow: `0 4px 16px ${blueAlpha[650][15]}`,
                  transform: 'translateY(-2px)',
                },
              }}
            >
              <CardContent>
                <Stack spacing={2}>
                  <Controller
                    name="title"
                    control={control}
                    rules={{
                      required: 'Title is required',
                      minLength: { value: 3, message: 'Title must be at least 3 characters' },
                    }}
                    render={({ field, fieldState }) => (
                      <FormControl error={!!fieldState.error}>
                        <FormLabel sx={{ display: 'flex', alignItems: 'center', gap: 1, fontWeight: 600 }}>
                          <Assignment sx={{ fontSize: 18, color: 'primary.500' }} />
                          Task Title
                        </FormLabel>
                        <Input
                          {...field}
                          placeholder="Give your research task an inspiring name..."
                          size="lg"
                          onChange={e => {
                            field.onChange(e);
                            setTitleManuallyEdited(true);
                          }}
                          sx={{
                            '--Input-focusedThickness': '2px',
                            '--Input-focusedHighlight': blueAlpha[650][25],
                            transition: 'all 0.2s ease',
                          }}
                        />
                        {fieldState.error && (
                          <Typography level="body-xs" color="danger" sx={{ mt: 0.5 }}>
                            {fieldState.error.message}
                          </Typography>
                        )}
                      </FormControl>
                    )}
                  />
                  <Controller
                    name="description"
                    control={control}
                    rules={{
                      required: 'Description is required',
                      minLength: { value: 10, message: 'Description must be at least 10 characters' },
                    }}
                    render={({ field, fieldState }) => (
                      <FormControl error={!!fieldState.error}>
                        <FormLabel
                          sx={{
                            display: 'flex',
                            justifyContent: 'space-between',
                            alignItems: 'center',
                            gap: 1,
                            fontWeight: 600,
                            width: '100%',
                          }}
                        >
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <Description sx={{ fontSize: 18, color: 'primary.500' }} />
                            Description
                          </Box>
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <RefineButton
                              value={currentDescription}
                              context={`Research task for web scraping. Title: ${currentTitle}`}
                              onSuccess={text => setValue('description', text)}
                              refiningMessage="Analyzing..."
                            />
                          </Box>
                        </FormLabel>
                        <Textarea
                          {...field}
                          placeholder="Describe what you want to research and discover..."
                          minRows={4}
                          maxRows={8}
                          size="lg"
                          sx={{
                            '--Textarea-focusedThickness': '2px',
                            '--Textarea-focusedHighlight': blueAlpha[650][25],
                            transition: 'all 0.2s ease',
                            resize: 'vertical',
                          }}
                        />
                        {fieldState.error && (
                          <Typography level="body-xs" color="danger" sx={{ mt: 0.5 }}>
                            {fieldState.error.message}
                          </Typography>
                        )}
                      </FormControl>
                    )}
                  />

                  {/* Task Type Selector */}
                  <Controller
                    name="type"
                    control={control}
                    render={({ field }) => (
                      <FormControl>
                        <FormLabel sx={{ display: 'flex', alignItems: 'center', gap: 1, fontWeight: 600 }}>
                          <Assignment sx={{ fontSize: 18, color: 'primary.500' }} />
                          Research Type
                        </FormLabel>
                        <Box sx={{ display: 'flex', gap: 1, mt: 1 }}>
                          {[
                            {
                              value: ResearchTaskType.SCRAPE,
                              label: '🌐 Web Scrape',
                              description: 'Extract data from specific URLs',
                            },
                            {
                              value: ResearchTaskType.DEEP_RESEARCH,
                              label: '🔬 Deep Research',
                              description: 'AI-powered iterative research',
                            },
                          ].map(option => (
                            <Box
                              key={option.value}
                              onClick={() => {
                                field.onChange(option.value);
                                setValue('type', option.value);
                              }}
                              sx={{
                                flex: 1,
                                p: 2,
                                borderRadius: '8px',
                                border: '2px solid',
                                borderColor: field.value === option.value ? 'primary.500' : 'neutral.300',
                                bgcolor: field.value === option.value ? 'primary.50' : 'background.surface',
                                cursor: 'pointer',
                                textAlign: 'center',
                                transition: 'all 0.2s ease',
                                '&:hover': {
                                  borderColor: field.value === option.value ? 'primary.600' : 'primary.400',
                                  bgcolor: field.value === option.value ? 'primary.100' : 'primary.25',
                                  transform: 'translateY(-2px)',
                                  boxShadow: `0 4px 12px ${blackAlpha[0][10]}`,
                                },
                                '&:active': {
                                  transform: 'translateY(0px)',
                                },
                              }}
                            >
                              <Typography
                                level="title-sm"
                                fontWeight={field.value === option.value ? 600 : 400}
                                color={field.value === option.value ? 'primary' : 'neutral'}
                                sx={{ mb: 0.5 }}
                              >
                                {option.label}
                              </Typography>
                              <Typography level="body-xs" color={field.value === option.value ? 'primary' : 'neutral'}>
                                {option.description}
                              </Typography>
                            </Box>
                          ))}
                        </Box>
                      </FormControl>
                    )}
                  />
                </Stack>
              </CardContent>
            </Card>
          </Stack>

          {/* Column 2 - Target Sources / Deep Research Settings */}
          <Stack spacing={2.5}>
            {/* Section Header */}
            <Box sx={{ mb: -1 }}>
              <Typography
                level="body-xs"
                sx={{
                  textTransform: 'uppercase',
                  letterSpacing: '0.1em',
                  color: mode === 'dark' ? 'warning.400' : 'warning.700',
                  fontWeight: 700,
                  display: 'flex',
                  alignItems: 'center',
                  gap: 0.5,
                }}
              >
                <Box sx={{ width: 4, height: 4, borderRadius: '50%', bgcolor: 'warning.500' }} />
                Step 2: {taskType === ResearchTaskType.DEEP_RESEARCH ? 'Deep Research Settings' : 'Target Sources'}
              </Typography>
            </Box>

            {/* Deep Research Fields */}
            {taskType === ResearchTaskType.DEEP_RESEARCH && (
              <Card
                variant="outlined"
                sx={{
                  border: '2px solid',
                  borderColor: mode === 'dark' ? 'warning.400' : 'warning.200',
                  background: `linear-gradient(to bottom, ${orangeAlpha[375][2]}, transparent)`,
                  transition: 'all 0.2s ease',
                  '&:hover': {
                    borderColor: 'warning.400',
                    boxShadow: `0 4px 16px ${orangeAlpha[375][15]}`,
                    transform: 'translateY(-2px)',
                  },
                }}
              >
                <CardContent>
                  <Stack spacing={2}>
                    <Controller
                      name="maxDepth"
                      control={control}
                      render={({ field, fieldState }) => (
                        <FormControl error={!!fieldState.error}>
                          <FormLabel sx={{ display: 'flex', alignItems: 'center', gap: 1, fontWeight: 600 }}>
                            <Assignment sx={{ fontSize: 18, color: 'primary.500' }} />
                            Research Depth (1-10)
                          </FormLabel>
                          <Input
                            type="number"
                            {...field}
                            value={field.value || 7}
                            onChange={e => field.onChange(Number(e.target.value))}
                            placeholder="7"
                            size="lg"
                            slotProps={{
                              input: { min: 1, max: 10, step: 1 },
                            }}
                            sx={{
                              '--Input-focusedThickness': '2px',
                              '--Textarea-focusedHighlight': blueAlpha[650][25],
                              transition: 'all 0.2s ease',
                            }}
                          />
                          <Typography level="body-xs" color="neutral" sx={{ mt: 0.5 }}>
                            Higher depth = more comprehensive research (recommended: 5-7)
                          </Typography>
                          {fieldState.error && (
                            <Typography level="body-xs" color="danger" sx={{ mt: 0.5 }}>
                              {fieldState.error.message}
                            </Typography>
                          )}
                        </FormControl>
                      )}
                    />
                  </Stack>
                </CardContent>
              </Card>
            )}

            {/* URLs and Smart Discovery */}
            {taskType === ResearchTaskType.SCRAPE && (
              <Card
                variant="outlined"
                sx={{
                  border: '2px solid',
                  borderColor: mode === 'dark' ? 'warning.400' : 'warning.200',
                  background: `linear-gradient(to bottom, ${orangeAlpha[375][2]}, transparent)`,
                  transition: 'all 0.2s ease',
                  '&:hover': {
                    borderColor: 'warning.400',
                    boxShadow: `0 4px 16px ${orangeAlpha[375][15]}`,
                    transform: 'translateY(-2px)',
                  },
                }}
              >
                <CardContent>
                  <Stack spacing={2}>
                    <FormControl>
                      <FormLabel sx={{ display: 'flex', alignItems: 'center', gap: 1, fontWeight: 600 }}>
                        <Link sx={{ fontSize: 18, color: 'primary.500' }} />
                        Target URLs
                      </FormLabel>

                      <Stack spacing={1}>
                        {fields.map((field, index) => (
                          <Controller
                            key={field.id}
                            name={`urls.${index}`}
                            control={control}
                            rules={{
                              required: index === 0 ? 'At least one URL is required' : false,
                              pattern: {
                                value: /^https?:\/\/.+/,
                                message: 'Please enter a valid URL starting with http:// or https://',
                              },
                            }}
                            render={({ field: fieldProps, fieldState }) => (
                              <Box>
                                <Box sx={{ display: 'flex', gap: 1, alignItems: 'flex-start', position: 'relative' }}>
                                  <Input
                                    {...fieldProps}
                                    placeholder={`https://example${index + 1}.com...`}
                                    type="url"
                                    size="lg"
                                    error={!!fieldState.error}
                                    sx={{
                                      flex: 1,
                                      '--Input-focusedThickness': '2px',
                                      '--Textarea-focusedHighlight': blueAlpha[650][25],
                                      transition: 'all 0.2s ease',
                                    }}
                                  />
                                  <Tooltip
                                    title="Browse popular research targets: earnings, press releases & AI news"
                                    arrow
                                    placement="top"
                                  >
                                    <Button
                                      variant="outlined"
                                      color="primary"
                                      size="lg"
                                      onClick={() => {
                                        setPopularTargetsState({ fieldIndex: index });
                                        setPopularTargetsOpen(true);
                                      }}
                                      sx={{
                                        minWidth: 'auto',
                                        px: 2,
                                        transition: 'all 0.2s ease',
                                        border: '2px solid',
                                        borderColor: 'primary.300',
                                        position: 'relative',
                                        overflow: 'hidden',
                                        ...(isShimmering && {
                                          // Multiple shimmer layers
                                          '&::before': {
                                            content: '""',
                                            position: 'absolute',
                                            top: '-100%',
                                            left: '-100%',
                                            width: '300%',
                                            height: '300%',
                                            background: `linear-gradient(45deg, transparent 20%, ${goldAlpha[400][90]} 40%, ${gray[0]} 50%, ${goldAlpha[400][90]} 60%, transparent 80%)`,
                                            animation: 'mega-shimmer 1s ease-in-out',
                                            zIndex: 1,
                                          },
                                          '&::after': {
                                            content: '""',
                                            position: 'absolute',
                                            top: '-50%',
                                            left: '-50%',
                                            width: '200%',
                                            height: '200%',
                                            background: `linear-gradient(135deg, transparent 30%, ${cyanAlpha[600][70]} 50%, transparent 70%)`,
                                            animation: 'mega-shimmer 1s ease-in-out 0.2s',
                                            zIndex: 1,
                                          },
                                          borderColor: gold[400],
                                          background: `linear-gradient(135deg, ${goldAlpha[400][10]} 0%, ${brandAlpha[500][10]} 50%, ${goldAlpha[400][10]} 100%)`,
                                          boxShadow: `
                                              0 0 30px ${goldAlpha[400][80]},
                                              0 0 60px ${brandAlpha[500][60]},
                                              0 0 90px ${goldAlpha[400][40]},
                                              inset 0 1px 0 ${whiteAlpha[0][30]}
                                            `,
                                          transform: 'scale(1.1)',
                                        }),
                                        '&:hover': {
                                          borderColor: 'primary.500',
                                          transform: 'translateY(-1px)',
                                          boxShadow: `0 4px 12px ${brandAlpha[500][30]}`,
                                        },
                                        '&:active': {
                                          transform: 'translateY(0px)',
                                        },
                                        '@keyframes mega-shimmer': {
                                          '0%': {
                                            transform: 'translateX(-150%) translateY(-150%) rotate(45deg)',
                                            opacity: 0,
                                          },
                                          '50%': {
                                            opacity: 1,
                                          },
                                          '100%': {
                                            transform: 'translateX(150%) translateY(150%) rotate(45deg)',
                                            opacity: 0,
                                          },
                                        },
                                        '@keyframes pulse-glow': {
                                          '0%, 100%': {
                                            filter: `brightness(1) drop-shadow(0 0 5px ${goldAlpha[400][50]})`,
                                          },
                                          '50%': {
                                            filter: `brightness(1.5) drop-shadow(0 0 15px ${goldAlpha[400][100]})`,
                                          },
                                        },
                                      }}
                                    >
                                      <TrendingUp
                                        sx={{
                                          fontSize: 20,
                                          position: 'relative',
                                          zIndex: 2,
                                          transition: 'all 0.2s ease',
                                          ...(isShimmering && {
                                            color: `${gold[400]} !important`,
                                            filter: `brightness(2) drop-shadow(0 0 10px ${goldAlpha[400][80]})`,
                                            animation: 'pulse-glow 1s ease-in-out infinite',
                                          }),
                                        }}
                                      />
                                    </Button>
                                  </Tooltip>
                                  <IconButton
                                    variant="outlined"
                                    color="danger"
                                    size="lg"
                                    onClick={() => remove(index)}
                                    sx={{ minWidth: 'auto', px: 2 }}
                                  >
                                    <Delete sx={{ fontSize: 20 }} />
                                  </IconButton>
                                </Box>

                                {fieldState.error && (
                                  <Typography level="body-xs" color="danger" sx={{ mt: 0.5 }}>
                                    {fieldState.error.message}
                                  </Typography>
                                )}
                              </Box>
                            )}
                          />
                        ))}

                        <Button
                          variant="outlined"
                          size="sm"
                          startDecorator={<Add />}
                          onClick={() => append('')}
                          sx={{ alignSelf: 'flex-start' }}
                        >
                          Add Another URL
                        </Button>
                      </Stack>
                    </FormControl>

                    <Controller
                      name="canDiscoverLinks"
                      control={control}
                      render={({ field: { value, onChange, ...field } }) => (
                        <Box>
                          <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 1 }}>
                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                              <Explore sx={{ fontSize: 18, color: 'primary.500' }} />
                              <Typography level="title-sm" fontWeight={600}>
                                Smart Discovery
                              </Typography>
                            </Box>
                            <Switch
                              {...field}
                              checked={value}
                              onChange={event => onChange(event.target.checked)}
                              color={value ? 'primary' : 'neutral'}
                              size="lg"
                            />
                          </Box>
                          <Typography level="body-sm" color="neutral">
                            {value
                              ? "✨ I'll discover related links for deeper insights"
                              : "I'll only analyze the specific URLs provided"}
                          </Typography>
                        </Box>
                      )}
                    />
                    {currentCanDiscoverLinks && (
                      <Controller
                        name="prompt"
                        control={control}
                        render={({ field, fieldState }) => (
                          <FormControl error={!!fieldState.error}>
                            <FormLabel sx={{ display: 'flex', alignItems: 'center', gap: 1, fontWeight: 600 }}>
                              <Search />
                              Prompt{' '}
                              <Typography level="body-xs" color="neutral">
                                (Optional)
                              </Typography>
                            </FormLabel>
                            <Input
                              {...field}
                              placeholder="What links are you looking for?"
                              size="lg"
                              onChange={e => {
                                field.onChange(e);
                                setTitleManuallyEdited(true);
                              }}
                              sx={{
                                '--Input-focusedThickness': '2px',
                                '--Input-focusedHighlight': blueAlpha[650][25],
                                transition: 'all 0.2s ease',
                              }}
                            />
                            {fieldState.error && (
                              <Typography level="body-xs" color="danger" sx={{ mt: 0.5 }}>
                                {fieldState.error.message}
                              </Typography>
                            )}
                          </FormControl>
                        )}
                      />
                    )}
                  </Stack>
                </CardContent>
              </Card>
            )}
          </Stack>

          {/* Column 3 - File Organization */}
          <Stack spacing={2.5}>
            {/* Section Header */}
            <Box sx={{ mb: -1 }}>
              <Typography
                level="body-xs"
                sx={{
                  textTransform: 'uppercase',
                  letterSpacing: '0.1em',
                  color: mode === 'dark' ? 'success.400' : 'success.700',
                  fontWeight: 700,
                  display: 'flex',
                  alignItems: 'center',
                  gap: 0.5,
                }}
              >
                <Box sx={{ width: 4, height: 4, borderRadius: '50%', bgcolor: 'success.500' }} />
                Step 3: Organize Results
              </Typography>
            </Box>
            {/* File Organization Card */}
            <Card
              variant="outlined"
              sx={{
                border: '2px solid',
                borderColor: mode === 'dark' ? 'success.400' : 'success.100',
                background: `linear-gradient(to bottom, ${greenAlpha[500][2]}, transparent)`,
                transition: 'all 0.2s ease',
                '&:hover': {
                  borderColor: 'success.300',
                  boxShadow: `0 4px 16px ${greenAlpha[500][15]}`,
                  transform: 'translateY(-2px)',
                },
              }}
            >
              <CardContent>
                <Stack spacing={2}>
                  <Typography level="title-sm" sx={{ display: 'flex', alignItems: 'center', gap: 1, fontWeight: 600 }}>
                    <Label sx={{ fontSize: 18, color: 'primary.500' }} />
                    File Organization
                  </Typography>
                  <Typography level="body-sm" color="neutral">
                    Choose a tag for all files from this research
                  </Typography>

                  <FormControl sx={{ gap: 1 }}>
                    <Select
                      value={selectedTagId || ''}
                      onChange={(_, value) => setSelectedTagId(value as string)}
                      startDecorator={
                        selectedTagId ? (
                          (() => {
                            const selectedTag = availableTags.find(t => t.id === selectedTagId);
                            return selectedTag ? (
                              <Avatar sx={{ width: 20, height: 20, bgcolor: selectedTag.color, fontSize: '12px' }}>
                                {selectedTag.icon}
                              </Avatar>
                            ) : null;
                          })()
                        ) : (
                          <Tag sx={{ fontSize: 18 }} />
                        )
                      }
                      placeholder="Use Auto-Generated Tag"
                      size="lg"
                      sx={{
                        '--Select-focusedThickness': '2px',
                      }}
                    >
                      {availableTags.map(tag => (
                        <Option key={tag.id} value={tag.id}>
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <Avatar sx={{ width: 20, height: 20, bgcolor: tag.color, fontSize: '12px' }}>
                              {tag.icon}
                            </Avatar>
                            {tag.name}
                          </Box>
                        </Option>
                      ))}
                    </Select>
                    <Button
                      variant="soft"
                      startDecorator={<Add />}
                      onClick={() => setIsTagModalOpen(true)}
                      sx={{ alignSelf: 'flex-start' }}
                    >
                      Create New Tag
                    </Button>
                  </FormControl>

                  {/* Tag Preview */}
                  <Box sx={{ p: 2, bgcolor: 'background.level1', borderRadius: 'sm' }}>
                    <Typography level="body-sm" sx={{ mb: 1, color: 'neutral.600' }}>
                      {selectedTagId ? 'Selected tag:' : 'Auto-generated tag preview:'}
                    </Typography>
                    {selectedTagId ? (
                      (() => {
                        const selectedTag = availableTags.find(t => t.id === selectedTagId);
                        return selectedTag ? (
                          <Chip
                            variant="soft"
                            sx={{ bgcolor: `${selectedTag.color}20`, color: selectedTag.color }}
                            startDecorator={
                              <Avatar sx={{ width: 20, height: 20, bgcolor: selectedTag.color, fontSize: '12px' }}>
                                {selectedTag.icon}
                              </Avatar>
                            }
                          >
                            {selectedTag.name}
                          </Chip>
                        ) : null;
                      })()
                    ) : autoGeneratedTag ? (
                      <Chip
                        variant="soft"
                        sx={{ bgcolor: `${autoGeneratedTag.color}20`, color: autoGeneratedTag.color }}
                        startDecorator={
                          <Avatar sx={{ width: 20, height: 20, bgcolor: autoGeneratedTag.color, fontSize: '12px' }}>
                            {autoGeneratedTag.icon}
                          </Avatar>
                        }
                      >
                        {autoGeneratedTag.name}
                      </Chip>
                    ) : (
                      <Typography level="body-xs" color="neutral">
                        Enter a URL and title to see auto-generated tag
                      </Typography>
                    )}
                  </Box>

                  <Typography level="body-xs" color="neutral" sx={{ fontStyle: 'italic' }}>
                    ✨ All files discovered from this research will be automatically tagged for easy organization
                  </Typography>
                </Stack>
              </CardContent>
            </Card>
          </Stack>

          {/* Column 4 - Execution Schedule */}
          <Stack spacing={2.5}>
            {/* Section Header */}
            <Box sx={{ mb: -1 }}>
              <Typography
                level="body-xs"
                sx={{
                  textTransform: 'uppercase',
                  letterSpacing: '0.1em',
                  color: mode === 'dark' ? 'secondary.400' : 'secondary.700',
                  fontWeight: 700,
                  display: 'flex',
                  alignItems: 'center',
                  gap: 0.5,
                }}
              >
                <Box sx={{ width: 4, height: 4, borderRadius: '50%', bgcolor: 'secondary.500' }} />
                Step 4: Schedule Execution
              </Typography>
            </Box>

            <Card
              variant="outlined"
              sx={{
                border: '2px solid',
                borderColor: grayAlpha[690][40],
                background: `linear-gradient(to bottom, ${purpleAlpha[500][2]}, transparent)`,
                transition: 'all 0.2s ease',
                '&:hover': {
                  boxShadow: `0 4px 16px ${purpleAlpha[500][15]}`,
                  transform: 'translateY(-2px)',
                },
              }}
            >
              <CardContent>
                <Controller
                  name="executionType"
                  control={control}
                  render={({ field }) => (
                    <FormControl>
                      <FormLabel sx={{ display: 'flex', alignItems: 'center', gap: 1, fontWeight: 600 }}>
                        <Schedule sx={{ fontSize: 18, color: 'primary.500' }} />
                        When should this run?
                      </FormLabel>
                      <Select
                        value={field.value}
                        onChange={(_, value) => {
                          if (value) {
                            field.onChange(value);
                            setValue('executionType', value);
                          }
                        }}
                        size="lg"
                        sx={{ '--Select-focusedThickness': '2px' }}
                      >
                        <Option value={ResearchTaskExecutionType.ON_DEMAND}>🚀 On Demand</Option>
                        <Option value={ResearchTaskExecutionType.PERIODIC}>🔄 Periodic</Option>
                      </Select>
                    </FormControl>
                  )}
                />
              </CardContent>
            </Card>

            {executionType === ResearchTaskExecutionType.PERIODIC && (
              <Card
                variant="outlined"
                sx={{
                  border: '1px solid',
                  borderColor: 'warning.300',
                  bgcolor: 'warning.50',
                  transition: 'all 0.2s ease',
                }}
              >
                <CardContent>
                  <Typography level="title-sm" sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
                    <EventRepeat sx={{ fontSize: 18, color: 'warning.500' }} />
                    Automation Settings
                  </Typography>

                  <Stack spacing={2}>
                    <Controller
                      name="executionPeriodicFrequency"
                      control={control}
                      defaultValue={ResearchTaskPeriodicFrequencyType.DAILY}
                      render={({ field }) => (
                        <FormControl>
                          <FormLabel>Frequency</FormLabel>
                          <Box sx={{ display: 'flex', gap: 1, mt: 1 }}>
                            {[
                              { value: ResearchTaskPeriodicFrequencyType.DAILY, label: '📅 Daily', emoji: '📅' },
                              { value: ResearchTaskPeriodicFrequencyType.WEEKLY, label: '🗓️ Weekly', emoji: '🗓️' },
                              { value: ResearchTaskPeriodicFrequencyType.MONTHLY, label: '📆 Monthly', emoji: '📆' },
                            ].map(option => (
                              <Box
                                key={option.value}
                                onClick={() => field.onChange(option.value)}
                                sx={{
                                  flex: 1,
                                  p: 1.5,
                                  borderRadius: '8px',
                                  border: '2px solid',
                                  borderColor: field.value === option.value ? 'primary.500' : 'neutral.300',
                                  bgcolor: field.value === option.value ? 'primary.50' : 'background.surface',
                                  cursor: 'pointer',
                                  textAlign: 'center',
                                  transition: 'all 0.2s ease',
                                  '&:hover': {
                                    borderColor: field.value === option.value ? 'primary.600' : 'primary.400',
                                    bgcolor: field.value === option.value ? 'primary.100' : 'primary.25',
                                    transform: 'translateY(-2px)',
                                    boxShadow: `0 4px 12px ${blackAlpha[0][10]}`,
                                  },
                                  '&:active': {
                                    transform: 'translateY(0px)',
                                  },
                                }}
                              >
                                <Typography
                                  level="title-sm"
                                  sx={{
                                    fontSize: '24px',
                                    mb: 0.5,
                                    filter: field.value === option.value ? 'none' : 'grayscale(0.5)',
                                  }}
                                >
                                  {option.emoji}
                                </Typography>
                                <Typography
                                  level="body-sm"
                                  fontWeight={field.value === option.value ? 600 : 400}
                                  color={field.value === option.value ? 'primary' : 'neutral'}
                                >
                                  {option.label.replace(option.emoji, '').trim()}
                                </Typography>
                              </Box>
                            ))}
                          </Box>
                        </FormControl>
                      )}
                    />

                    <Controller
                      name="executionPeriodicStartAt"
                      control={control}
                      render={({ field }) => (
                        <FormControl>
                          <FormLabel sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <AccessTime sx={{ fontSize: 16 }} />
                            Start Date & Time
                          </FormLabel>
                          <DateTimePicker value={field.value} onChange={field.onChange} />
                        </FormControl>
                      )}
                    />
                    <Controller
                      name="executionPeriodicEndAt"
                      control={control}
                      render={({ field }) => (
                        <FormControl>
                          <FormLabel sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <AccessTime sx={{ fontSize: 16 }} />
                            End Date & Time (Optional)
                          </FormLabel>
                          <DateTimePicker value={field.value} onChange={field.onChange} />
                        </FormControl>
                      )}
                    />
                  </Stack>
                </CardContent>
              </Card>
            )}
          </Stack>
        </Box>

        <Divider sx={{ my: 3 }} />

        <Box sx={{ display: 'flex', gap: 2, justifyContent: 'center' }}>
          <Button
            variant="outlined"
            color="neutral"
            onClick={onCancel}
            disabled={isLoading}
            size="md"
            startDecorator={<Cancel />}
            sx={{
              minWidth: 100,
              transition: 'all 0.2s ease',
              '&:hover': {
                transform: 'translateY(-1px)',
                boxShadow: `0 4px 12px ${blackAlpha[0][15]}`,
              },
            }}
          >
            Cancel
          </Button>
          <Button
            type="submit"
            loading={isLoading}
            size="md"
            startDecorator={!isLoading && <Save />}
            sx={{
              minWidth: 140,
              background: `linear-gradient(135deg, ${blue[400]} 0%, ${brand[500]} 50%, ${purple[500]} 100%)`,
              transition: 'all 0.2s ease',
              '&:hover': {
                transform: 'translateY(-1px)',
                boxShadow: `0 8px 20px ${brandAlpha[500][40]}`,
                background: `linear-gradient(135deg, ${blue[700]} 0%, ${blue[800]} 50%, ${purple[700]} 100%)`,
              },
              '&:active': {
                transform: 'translateY(0px)',
              },
            }}
          >
            {isEditing ? '✨ Update Task' : '🚀 Create Task'}
          </Button>
        </Box>

        <Typography level="body-xs" color="neutral" sx={{ textAlign: 'center', mt: 1.5, fontStyle: 'italic' }}>
          {isEditing
            ? 'Your updates will be saved and applied immediately'
            : 'Your research task will be ready to discover amazing insights!'}
        </Typography>
      </form>

      <PopularTargetsModal
        open={popularTargetsOpen}
        onClose={() => setPopularTargetsOpen(false)}
        onSelect={handlePopularTargetSelect}
      />

      {/* Tag Creation Modal */}
      <Modal
        open={isTagModalOpen}
        onClose={isCreatingTag ? undefined : () => setIsTagModalOpen(false)}
        sx={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          backdropFilter: 'blur(4px)',
          padding: 2,
        }}
      >
        <ModalDialog
          sx={{
            width: '95vw',
            maxWidth: '650px',
            maxHeight: '90vh',
            display: 'flex',
            flexDirection: 'column',
            margin: 'auto',
            background: `linear-gradient(135deg, ${whiteAlpha[0][95]} 0%, ${grayAlpha[15][95]} 100%)`,
            boxShadow: `0 25px 50px -12px ${blackAlpha[0][25]}`,
            borderRadius: '16px',
            border: `1px solid ${whiteAlpha[0][20]}`,
            position: 'relative',
            overflow: 'auto',
            transform: 'none',
            top: 'auto',
            left: 'auto',
            '&::before': {
              content: '""',
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              height: '4px',
              background: `linear-gradient(90deg, ${blue[400]} 0%, ${brand[500]} 50%, ${purple[500]} 100%)`,
            },
          }}
        >
          <ModalClose
            sx={{
              position: 'absolute',
              top: 12,
              right: 12,
              zIndex: 10,
              borderRadius: '50%',
              transition: 'all 0.2s ease',
              '&:hover': {
                bgcolor: 'danger.softHoverBg',
                transform: 'scale(1.1)',
              },
            }}
          />

          <TagForm
            onSubmit={async tagData => {
              try {
                const newTag = await createTag(tagData);
                await refetchTags();
                setSelectedTagId(newTag.id); // Auto-select the newly created tag
                setIsTagModalOpen(false);
              } catch (error) {
                console.error('Failed to create tag:', error);
              }
            }}
            submitting={isCreatingTag}
          />
        </ModalDialog>
      </Modal>
    </Box>
  );
};

export const RefineButton: FC<{
  value: string;
  context?: string;
  onSuccess: (text: string) => void;
  refiningMessage?: string;
}> = ({ value, context, onSuccess, refiningMessage = 'Refining...' }) => {
  const { mutateAsync: refineText, isPending: isRefiningText } = useRefineText({
    onSuccess,
  });

  return (
    <Button
      variant="plain"
      size="sm"
      startDecorator={
        <Box
          component="span"
          sx={{
            display: 'inline-flex',
            alignItems: 'center',
            animation: isRefiningText ? 'wandBounce 0.7s infinite cubic-bezier(.68,-0.55,.27,1.55)' : undefined,
            '@keyframes wandBounce': {
              '0%': { transform: 'translateY(0)' },
              '20%': { transform: 'translateY(-4px)' },
              '40%': { transform: 'translateY(-8px)' },
              '60%': { transform: 'translateY(-4px)' },
              '80%': { transform: 'translateY(0)' },
              '100%': { transform: 'translateY(0)' },
            },
          }}
        >
          <AutoFixHighIcon />
        </Box>
      }
      onClick={() => refineText({ text: value, context })}
      disabled={isRefiningText}
      sx={{
        position: 'relative',
        overflow: 'hidden',
        ...(isRefiningText && {
          pointerEvents: 'none',
        }),
        minWidth: 90,
      }}
    >
      {isRefiningText ? (
        <Box
          component="span"
          sx={{
            display: 'inline-flex',
            alignItems: 'center',
            fontWeight: 600,
            fontSize: '0.95em',
            letterSpacing: '0.02em',
            color: 'transparent',
            background: `linear-gradient(110deg, ${purple[300]} 8%, ${purple[400]} 18%, ${purple[300]} 33%)`,
            backgroundSize: '200% 100%',
            backgroundClip: 'text',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            animation: 'shimmerRefineText 1.2s linear infinite',
            boxShadow: `0 0 8px 0 ${purpleAlpha[325][20]}`,
            borderRadius: 'inherit',
            position: 'relative',
            zIndex: 1,
          }}
        >
          {refiningMessage}
          <style>
            {`
              @keyframes shimmerRefineText {
                0% { background-position: -120% 0; }
                100% { background-position: 120% 0; }
              }
            `}
          </style>
        </Box>
      ) : (
        'Enhance'
      )}
    </Button>
  );
};

export default ResearchTaskForm;
