import { AIImageService, AIImageGenerationOptions, ImageEditResponse } from './AIImageService';
import OpenAI from 'openai';
import { Logger } from '@bike4mind/observability';
import { ImageModels } from '@bike4mind/common';

export class XAIImageService extends AIImageService {
  async generate(prompt: string, options: AIImageGenerationOptions): Promise<string[]> {
    // XAI uses the same OpenAI SDK but with different base URL and endpoint
    const xai = new OpenAI({
      apiKey: this.apiKey,
      baseURL: 'https://api.x.ai/v1',
    });

    Logger.log('Generating image with XAI/Grok... with these params: ', options);

    try {
      // XAI image generation uses a dedicated images/generations endpoint
      // as per https://docs.x.ai/docs/guides/image-generations
      // XAI does not support size, quality, or other OpenAI-specific parameters
      const response = await xai.images.generate({
        prompt,
        model: ImageModels.GROK_IMAGINE_IMAGE_QUALITY,
        n: options.n || 1,
        user: options.user,
      });

      if (!response.data || response.data.length === 0) {
        throw new Error('No images generated by XAI');
      }

      const imageUrls = response.data.map(image => {
        if (!image.url) {
          throw new Error('No URL in XAI image response');
        }
        return image.url;
      });

      Logger.log(`XAI generated ${imageUrls.length} image(s) successfully`);
      return imageUrls;
    } catch (error) {
      Logger.error('XAI image generation failed:', error);

      if (error instanceof Error) {
        throw new Error(`XAI image generation failed: ${error.message}`);
      }

      throw new Error('XAI image generation failed with unknown error');
    }
  }

  async edit(_image: string, _prompt: string, _options: any): Promise<ImageEditResponse> {
    throw new Error('Image editing is not supported by XAI/Grok models');
  }

  async variantions(_image: Buffer, _options: any): Promise<string[]> {
    throw new Error('Image variations are not supported by XAI/Grok models');
  }
}
