/**
 * POST /api/v1/image-generations - queue an image generation; the caller polls the returned quest.
 * Also served at the legacy `/api/ai/generate-image` (pages/api/ai/generate-image.ts re-exports this).
 *
 * Auth mode, the `ai:generate` scope and body validation all come from `generateImageContract`.
 * The scope lets a least-privilege image-only key drive the whole POST -> poll GET /api/v1/quests/{id}
 * flow (the poll endpoint already accepts ai:generate). `callbackUrl` replaces the poll with a push
 * (server/generationCallback).
 */

import { nextRouteForContract } from '@server/middlewares/defineNextRoute';
import { getImageGeneration } from '@server/queueHandlers/imageGeneration';
import { generateImageContract, GenerateImageIvokeParams } from '@bike4mind/common';
import { getOrCreateSession } from '@server/managers/sessionManager';
import { resolveSessionOrigin } from '@server/managers/sessionOrigin';
import { resolveBillingOrgId } from '@server/utils/orgAccess';
import { questRepository } from '@bike4mind/database';
import { resolveImagePrompt, HISTORY_LOOKBACK, type PromptResolution } from '@server/utils/resolveImagePrompt';
import { armGenerationCallback, resolveGenerationCallback } from '@server/generationCallback/armGenerationCallback';
import { assertReferenceImagesSupported } from '@server/utils/assertReferenceImagesSupported';

const handler = nextRouteForContract(generateImageContract).post(async (req, res) => {
  const body = req.validated;

  req.logger.updateMetadata({
    userId: req.user?.id,
    userEmail: req.user?.email,
    bodyKeys: Object.keys(req.body || {}).join(', '),
    model: body.model,
    size: body.size,
    width: body.width,
    height: body.height,
    aspectRatio: body.aspect_ratio,
    sessionId: body.sessionId,
    questId: body.questId,
    referenceImageCount: body.referenceImageFabFileIds?.length ?? 0,
    n: body.n,
    quality: body.quality,
    style: body.style,
    responseFormat: body.response_format,
    promptPreview: body.prompt.substring(0, 100) + '...',
    promptResolution: body.promptResolution ?? 'auto',
  });

  assertReferenceImagesSupported(body.model, body.referenceImageFabFileIds);

  const { sessionId: reqSessionId, sessionName, callbackUrl, promptResolution, ...invokeParams } = body;
  const callback = await resolveGenerationCallback(req, callbackUrl);

  const { sessionId, asyncPromises, session } = await getOrCreateSession({
    sessionId: reqSessionId,
    sessionName: sessionName,
    projectId: invokeParams.projectId,
    user: req.user,
    ability: req.ability,
    logger: req.logger,
    origin: resolveSessionOrigin(req),
  });

  try {
    // Resolve the billing org from the client-supplied value, rejecting any org the caller is
    // not a member of. null = personal account, undefined = fall back to the caller's own org.
    const effectiveOrgId = await resolveBillingOrgId(req, invokeParams.organizationId);

    const originalPrompt = body.prompt;
    // 'literal' callers own their prompt (agents, pipelines): skip the resolver entirely so the
    // model receives it unchanged, bar ImageGeneration's truncation to the model's prompt limit; the
    // 'fresh' intent also stops the prior image being carried forward, except for models that
    // require an input image (ImageGeneration.ts).
    const shouldResolvePrompt = !!originalPrompt && promptResolution !== 'literal';

    // Resolve the prompt against session history (text + image). Runs whenever the session has any
    // prior turn so coreference ("different variant", "make it darker") and text-grounded follow-ups
    // ("now generate the logo we discussed") both bind correctly. The pre-computed session summary
    // is included as long-term context - it's generated by the chat path's SummarizeNotebookFeature
    // and stored on the Session doc, so passing it costs zero extra DB calls or LLM calls.
    const recentMessages = shouldResolvePrompt
      ? await questRepository.getMostRecentChatHistory(sessionId, HISTORY_LOOKBACK)
      : [];
    const sessionSummary = session?.contextSummary || session?.summary || null;
    const resolution: PromptResolution = shouldResolvePrompt
      ? await resolveImagePrompt({
          originalPrompt,
          recentMessages,
          sessionSummary,
          logger: req.logger,
          endUserId: req.user?.id,
        })
      : { rewrittenPrompt: originalPrompt ?? '', intent: 'fresh' };

    // For continuation prompts ("different variant", "the logo we discussed"), the rewrite is
    // non-optional - the user's literal text doesn't carry the subject and the image model would
    // hallucinate without it. So we always use the rewrittenPrompt for continuations, regardless of
    // the prompt_enhancement tool toggle - only an explicit promptResolution: 'literal' opts out. The
    // toggle only controls rewriting of self-contained 'fresh' prompts, where opting out to keep
    // literal words is a valid user choice.
    const promptEnhancementEnabled = body.tools?.includes('prompt_enhancement') ?? false;
    const shouldUseRewrittenPrompt =
      shouldResolvePrompt && (resolution.intent === 'continuation' || promptEnhancementEnabled);
    const effectivePrompt = shouldUseRewrittenPrompt ? resolution.rewrittenPrompt : (originalPrompt ?? '');
    const promptWasEnhanced = shouldUseRewrittenPrompt && effectivePrompt !== originalPrompt;

    // INVARIANT: the top-level `intent` and `promptEnhancement.intent` must always reflect the same
    // resolver decision. They serve different lifecycles - top-level is the transit value carried
    // through the SQS queue into `process()` for image carryforward gating; the nested copy is the
    // persisted value on the Quest used by the UI banner. Both are derived from `resolution.intent`
    // here at construction time and must not be mutated independently downstream.
    const enhancedBody: GenerateImageIvokeParams = {
      ...invokeParams,
      sessionId,
      organizationId: effectiveOrgId,
      prompt: effectivePrompt,
      intent: resolution.intent,
      promptEnhancement: originalPrompt
        ? {
            originalPrompt,
            enhancedPrompt: effectivePrompt,
            promptWasEnhanced,
            intent: resolution.intent,
          }
        : undefined,
    };

    req.logger.log(`[DEBUG API] Calling imageGeneration.invoke...`);
    const startTime = performance.now();

    const quest = await getImageGeneration().invoke({
      userId: req.user.id,
      body: enhancedBody,
    });

    const endTime = performance.now();

    await armGenerationCallback(quest.id, callback, req.logger);

    req.logger.updateMetadata({
      duration: `${endTime - startTime}ms`,
      questStatus: quest?.status,
      questType: quest?.type,
      hasReply: !!quest?.reply,
      hasImages: !!quest?.images?.length,
      intent: resolution.intent,
      promptEnhancementEnabled,
      promptWasEnhanced,
      usedRewrittenPrompt: shouldUseRewrittenPrompt,
    });

    req.logger.log(`[DEBUG API] imageGeneration.invoke completed in ${endTime - startTime}ms`);

    await Promise.all(asyncPromises);

    const response = {
      quest,
      session,
      originalPrompt,
      enhancedPrompt: effectivePrompt,
      promptWasEnhanced,
      intent: resolution.intent,
    };

    return res.json(response);
  } catch (error) {
    req.logger.error(`[DEBUG API] Error in generate-image endpoint:`, {
      error,
      errorMessage: error instanceof Error ? error.message : 'Unknown error',
      userId: req.user?.id,
    });
    throw error;
  }
});

export default handler;
