export interface WorldCity {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  timezone: string;
  lat: number;
  lng: number;
  emoji: string;
}

// Curated, diverse coverage across time zones (subset, expandable to 100+)
export const WORLD_CITIES: WorldCity[] = [
  // Core ops
  {
    id: 'austin',
    name: 'Austin',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/Chicago',
    lat: 30.2672,
    lng: -97.7431,
    emoji: '🤠',
  },
  {
    id: 'cebu',
    name: 'Cebu',
    country: 'Philippines',
    countryCode: 'PH',
    timezone: 'Asia/Manila',
    lat: 10.3157,
    lng: 123.8854,
    emoji: '🏝️',
  },
  {
    id: 'kyiv',
    name: 'Kyiv',
    country: 'Ukraine',
    countryCode: 'UA',
    timezone: 'Europe/Kiev',
    lat: 50.4501,
    lng: 30.5234,
    emoji: '🌻',
  },
  {
    id: 'louisville',
    name: 'Louisville',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/New_York',
    lat: 38.2527,
    lng: -85.7585,
    emoji: '🐎',
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/Los_Angeles',
    lat: 34.0522,
    lng: -118.2437,
    emoji: '🎬',
  },

  // Americas
  {
    id: 'new-york',
    name: 'New York',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/New_York',
    lat: 40.7128,
    lng: -74.006,
    emoji: '🗽',
  },
  {
    id: 'chicago',
    name: 'Chicago',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/Chicago',
    lat: 41.8781,
    lng: -87.6298,
    emoji: '🌆',
  },
  {
    id: 'denver',
    name: 'Denver',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/Denver',
    lat: 39.7392,
    lng: -104.9903,
    emoji: '⛰️',
  },
  {
    id: 'seattle',
    name: 'Seattle',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/Los_Angeles',
    lat: 47.6062,
    lng: -122.3321,
    emoji: '☔',
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/Los_Angeles',
    lat: 37.7749,
    lng: -122.4194,
    emoji: '🌉',
  },
  {
    id: 'miami',
    name: 'Miami',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/New_York',
    lat: 25.7617,
    lng: -80.1918,
    emoji: '🌴',
  },
  {
    id: 'atlanta',
    name: 'Atlanta',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/New_York',
    lat: 33.749,
    lng: -84.388,
    emoji: '🍑',
  },
  {
    id: 'houston',
    name: 'Houston',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/Chicago',
    lat: 29.7604,
    lng: -95.3698,
    emoji: '🛢️',
  },
  {
    id: 'boston',
    name: 'Boston',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/New_York',
    lat: 42.3601,
    lng: -71.0589,
    emoji: '🎓',
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    countryCode: 'CA',
    timezone: 'America/Toronto',
    lat: 43.6532,
    lng: -79.3832,
    emoji: '🍁',
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'Canada',
    countryCode: 'CA',
    timezone: 'America/Vancouver',
    lat: 49.2827,
    lng: -123.1207,
    emoji: '🍁',
  },
  {
    id: 'mexico-city',
    name: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    timezone: 'America/Mexico_City',
    lat: 19.4326,
    lng: -99.1332,
    emoji: '🌮',
  },
  {
    id: 'bogota',
    name: 'Bogotá',
    country: 'Colombia',
    countryCode: 'CO',
    timezone: 'America/Bogota',
    lat: 4.711,
    lng: -74.0721,
    emoji: '⛰️',
  },
  {
    id: 'lima',
    name: 'Lima',
    country: 'Peru',
    countryCode: 'PE',
    timezone: 'America/Lima',
    lat: -12.0464,
    lng: -77.0428,
    emoji: '🦙',
  },
  {
    id: 'santiago',
    name: 'Santiago',
    country: 'Chile',
    countryCode: 'CL',
    timezone: 'America/Santiago',
    lat: -33.4489,
    lng: -70.6693,
    emoji: '🗻',
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    timezone: 'America/Argentina/Buenos_Aires',
    lat: -34.6037,
    lng: -58.3816,
    emoji: '💃',
  },
  {
    id: 'panama-city',
    name: 'Panama City',
    country: 'Panama',
    countryCode: 'PA',
    timezone: 'America/Panama',
    lat: 8.9824,
    lng: -79.5199,
    emoji: '🛳️',
  },

  // Europe
  {
    id: 'london',
    name: 'London',
    country: 'UK',
    countryCode: 'GB',
    timezone: 'Europe/London',
    lat: 51.5074,
    lng: -0.1278,
    emoji: '🏰',
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    timezone: 'Europe/Paris',
    lat: 48.8566,
    lng: 2.3522,
    emoji: '🗼',
  },
  {
    id: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    countryCode: 'DE',
    timezone: 'Europe/Berlin',
    lat: 52.52,
    lng: 13.405,
    emoji: '🦅',
  },
  {
    id: 'madrid',
    name: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    timezone: 'Europe/Madrid',
    lat: 40.4168,
    lng: -3.7038,
    emoji: '💃',
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    timezone: 'Europe/Rome',
    lat: 41.9028,
    lng: 12.4964,
    emoji: '🏛️',
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    timezone: 'Europe/Amsterdam',
    lat: 52.3676,
    lng: 4.9041,
    emoji: '🚲',
  },
  {
    id: 'stockholm',
    name: 'Stockholm',
    country: 'Sweden',
    countryCode: 'SE',
    timezone: 'Europe/Stockholm',
    lat: 59.3293,
    lng: 18.0686,
    emoji: '❄️',
  },
  {
    id: 'warsaw',
    name: 'Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    timezone: 'Europe/Warsaw',
    lat: 52.2297,
    lng: 21.0122,
    emoji: '🛡️',
  },
  {
    id: 'vienna',
    name: 'Vienna',
    country: 'Austria',
    countryCode: 'AT',
    timezone: 'Europe/Vienna',
    lat: 48.2082,
    lng: 16.3738,
    emoji: '🎼',
  },
  {
    id: 'athens',
    name: 'Athens',
    country: 'Greece',
    countryCode: 'GR',
    timezone: 'Europe/Athens',
    lat: 37.9838,
    lng: 23.7275,
    emoji: '🏺',
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    country: 'Türkiye',
    countryCode: 'TR',
    timezone: 'Europe/Istanbul',
    lat: 41.0082,
    lng: 28.9784,
    emoji: '🕌',
  },
  {
    id: 'moscow',
    name: 'Moscow',
    country: 'Russia',
    countryCode: 'RU',
    timezone: 'Europe/Moscow',
    lat: 55.7558,
    lng: 37.6173,
    emoji: '🏛️',
  },

  // Middle East & Africa
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    countryCode: 'AE',
    timezone: 'Asia/Dubai',
    lat: 25.2048,
    lng: 55.2708,
    emoji: '🏜️',
  },
  {
    id: 'tel-aviv',
    name: 'Tel Aviv',
    country: 'Israel',
    countryCode: 'IL',
    timezone: 'Asia/Jerusalem',
    lat: 32.0853,
    lng: 34.7818,
    emoji: '🌊',
  },
  {
    id: 'riyadh',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    timezone: 'Asia/Riyadh',
    lat: 24.7136,
    lng: 46.6753,
    emoji: '🏜️',
  },
  {
    id: 'tehran',
    name: 'Tehran',
    country: 'Iran',
    countryCode: 'IR',
    timezone: 'Asia/Tehran',
    lat: 35.6892,
    lng: 51.389,
    emoji: '🕌',
  },
  {
    id: 'johannesburg',
    name: 'Johannesburg',
    country: 'South Africa',
    countryCode: 'ZA',
    timezone: 'Africa/Johannesburg',
    lat: -26.2041,
    lng: 28.0473,
    emoji: '🦁',
  },
  {
    id: 'nairobi',
    name: 'Nairobi',
    country: 'Kenya',
    countryCode: 'KE',
    timezone: 'Africa/Nairobi',
    lat: -1.2921,
    lng: 36.8219,
    emoji: '🦒',
  },
  {
    id: 'lagos',
    name: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    timezone: 'Africa/Lagos',
    lat: 6.5244,
    lng: 3.3792,
    emoji: '🌍',
  },
  {
    id: 'cairo',
    name: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    timezone: 'Africa/Cairo',
    lat: 30.0444,
    lng: 31.2357,
    emoji: '🏺',
  },

  // South & East Asia
  {
    id: 'mumbai',
    name: 'Mumbai',
    country: 'India',
    countryCode: 'IN',
    timezone: 'Asia/Kolkata',
    lat: 19.076,
    lng: 72.8777,
    emoji: '🕌',
  },
  {
    id: 'karachi',
    name: 'Karachi',
    country: 'Pakistan',
    countryCode: 'PK',
    timezone: 'Asia/Karachi',
    lat: 24.8607,
    lng: 67.0011,
    emoji: '🌆',
  },
  {
    id: 'dhaka',
    name: 'Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    timezone: 'Asia/Dhaka',
    lat: 23.8103,
    lng: 90.4125,
    emoji: '🌿',
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    timezone: 'Asia/Bangkok',
    lat: 13.7563,
    lng: 100.5018,
    emoji: '🛕',
  },
  {
    id: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    timezone: 'Asia/Kuala_Lumpur',
    lat: 3.139,
    lng: 101.6869,
    emoji: '🕌',
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    timezone: 'Asia/Singapore',
    lat: 1.3521,
    lng: 103.8198,
    emoji: '🦁',
  },
  {
    id: 'jakarta',
    name: 'Jakarta',
    country: 'Indonesia',
    countryCode: 'ID',
    timezone: 'Asia/Jakarta',
    lat: -6.2088,
    lng: 106.8456,
    emoji: '🌋',
  },
  {
    id: 'manila',
    name: 'Manila',
    country: 'Philippines',
    countryCode: 'PH',
    timezone: 'Asia/Manila',
    lat: 14.5995,
    lng: 120.9842,
    emoji: '🌴',
  },
  {
    id: 'ho-chi-minh',
    name: 'Ho Chi Minh City',
    country: 'Vietnam',
    countryCode: 'VN',
    timezone: 'Asia/Ho_Chi_Minh',
    lat: 10.8231,
    lng: 106.6297,
    emoji: '🛶',
  },
  {
    id: 'hanoi',
    name: 'Hanoi',
    country: 'Vietnam',
    countryCode: 'VN',
    timezone: 'Asia/Bangkok',
    lat: 21.0278,
    lng: 105.8342,
    emoji: '🎎',
  },
  {
    id: 'hong-kong',
    name: 'Hong Kong',
    country: 'China',
    countryCode: 'CN',
    timezone: 'Asia/Hong_Kong',
    lat: 22.3193,
    lng: 114.1694,
    emoji: '🏮',
  },
  {
    id: 'taipei',
    name: 'Taipei',
    country: 'Taiwan',
    countryCode: 'TW',
    timezone: 'Asia/Taipei',
    lat: 25.033,
    lng: 121.5654,
    emoji: '🕍',
  },
  {
    id: 'shanghai',
    name: 'Shanghai',
    country: 'China',
    countryCode: 'CN',
    timezone: 'Asia/Shanghai',
    lat: 31.2304,
    lng: 121.4737,
    emoji: '🏙️',
  },
  {
    id: 'beijing',
    name: 'Beijing',
    country: 'China',
    countryCode: 'CN',
    timezone: 'Asia/Shanghai',
    lat: 39.9042,
    lng: 116.4074,
    emoji: '🏮',
  },
  {
    id: 'seoul',
    name: 'Seoul',
    country: 'South Korea',
    countryCode: 'KR',
    timezone: 'Asia/Seoul',
    lat: 37.5665,
    lng: 126.978,
    emoji: '🎎',
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    timezone: 'Asia/Tokyo',
    lat: 35.6762,
    lng: 139.6503,
    emoji: '🗾',
  },

  // Oceania & Pacific
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    timezone: 'Australia/Sydney',
    lat: -33.8688,
    lng: 151.2093,
    emoji: '🦘',
  },
  {
    id: 'auckland',
    name: 'Auckland',
    country: 'New Zealand',
    countryCode: 'NZ',
    timezone: 'Pacific/Auckland',
    lat: -36.8485,
    lng: 174.7633,
    emoji: '🧭',
  },
  {
    id: 'honolulu',
    name: 'Honolulu',
    country: 'USA',
    countryCode: 'US',
    timezone: 'Pacific/Honolulu',
    lat: 21.3069,
    lng: -157.8583,
    emoji: '🌺',
  },
  {
    id: 'anchorage',
    name: 'Anchorage',
    country: 'USA',
    countryCode: 'US',
    timezone: 'America/Anchorage',
    lat: 61.2181,
    lng: -149.9003,
    emoji: '🧊',
  },
];
