#!/usr/bin/env node

// Regenerates src/generated/ from the checked-in OpenAPI spec (apps/client/public/openapi.json):
//   openapi.ts    - openapi-typescript's `paths` / `components` / `operations` types
//   operations.ts - the runtime operationId -> { method, path } manifest the client routes by
// Both are checked in. The CI `openapi` job regenerates the spec and these files and fails on any diff,
// so a contract change that is not regenerated here fails CI, and one that is breaks the SDK typecheck.
// Run via `pnpm turbo:openapi:generate` (spec + SDK) or `pnpm --filter @bike4mind/sdk generate`.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import * as prettier from 'prettier';

const pkgDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const specPath = path.resolve(pkgDir, '../../apps/client/public/openapi.json');
const outDir = path.join(pkgDir, 'src', 'generated');
const HEADER =
  '// Generated by packages/sdk/scripts/generate.mjs from apps/client/public/openapi.json. Do not edit.\n\n';
const METHODS = ['get', 'put', 'post', 'delete', 'patch', 'head', 'options', 'trace'];

export function buildManifest(spec) {
  const entries = [];
  const seen = new Set();
  for (const [route, item] of Object.entries(spec.paths ?? {})) {
    for (const method of METHODS) {
      const operation = item[method];
      if (!operation) continue;
      const { operationId } = operation;
      if (!operationId) throw new Error(`${method.toUpperCase()} ${route} has no operationId`);
      if (seen.has(operationId)) throw new Error(`duplicate operationId ${operationId}`);
      seen.add(operationId);
      entries.push([operationId, { method: method.toUpperCase(), path: route }]);
    }
  }
  entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return Object.fromEntries(entries);
}

async function format(file, source) {
  const config = await prettier.resolveConfig(file);
  return prettier.format(source, { ...config, filepath: file });
}

async function main() {
  const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));
  fs.mkdirSync(outDir, { recursive: true });

  const typesFile = path.join(outDir, 'openapi.ts');
  // A field with a `default` is optional to send; the option's default (true) would make it required in requests.
  const ast = await openapiTS(spec, { defaultNonNullable: false });
  fs.writeFileSync(typesFile, await format(typesFile, HEADER + astToString(ast)));

  const manifestFile = path.join(outDir, 'operations.ts');
  const manifest = `${HEADER}export const operations = ${JSON.stringify(buildManifest(spec), null, 2)} as const;\n`;
  fs.writeFileSync(manifestFile, await format(manifestFile, manifest));

  console.log(`wrote ${path.relative(process.cwd(), typesFile)} and ${path.relative(process.cwd(), manifestFile)}`);
}

if (process.argv[1] && fs.realpathSync(process.argv[1]) === fs.realpathSync(fileURLToPath(import.meta.url))) {
  main().catch(error => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
