import { IBaseRepository } from './BaseTypes';
import { IResearchDataWithFiles } from './ResearchDataTypes';

export enum ResearchTaskExecutionType {
  /**
   * The task is executed on demand
   * eg: when the user creates the task
   */
  ON_DEMAND = 'on-demand',
  /**
   * The task is executed periodically
   * eg: daily, weekly, monthly
   */
  PERIODIC = 'periodic',
  /**
   * The task is executed scheduled
   * eg: at a specific time
   */
  SCHEDULED = 'scheduled',
}

export enum ResearchTaskPeriodicFrequencyType {
  DAILY = 'daily',
  WEEKLY = 'weekly',
  MONTHLY = 'monthly',
}

export enum ResearchTaskType {
  SCRAPE = 'scrape',
  SALESFORCE = 'salesforce',
  DEEP_RESEARCH = 'deepResearch',
}

export enum ResearchTaskStatus {
  PENDING = 'pending',
  PROCESSING = 'processing',
  COMPLETED = 'completed',
  FAILED = 'failed',
}

export interface IBaseResearchTask {
  /**
   * The unique ID of the task
   */
  id: string;
  /**
   * The user ID that created the task
   */
  userId: string;

  /**
   * The research agent ID that created the task
   */
  researchAgentId: string;

  /**
   * The research data ID that the task main content is stored in
   * @deprecated
   */
  researchDataId?: string;

  /**
   * The type of the task
   */
  type: ResearchTaskType;
  /**
   * The title of the task
   */
  title: string;
  /**
   * The description of the task
   */
  description: string;
  /**
   * The status of the task
   */
  status: ResearchTaskStatus;
  /**
   * The message of the task if it failed
   */
  statusFailedMessage?: string | null;
  /**
   * The date and time the task failed
   */
  statusFailedAt?: Date | null;
  /**
   * The date and time the task was completed
   */
  statusCompletedAt?: Date;

  /**
   * The execution type of the task
   * - on-demand: The task is executed on demand
   * - periodic: The task is executed periodically
   * - scheduled: The task is executed scheduled
   */
  executionType: ResearchTaskExecutionType;

  /**
   * The file tag ID to apply to all files created from this task
   */
  fileTagId?: string;

  /**
   * The organization ID that the task is associated with
   * if specified, the stored files will be associated with the organization
   */
  organizationId?: string;

  /**
   * Auto-generated tag information for file organization
   */
  autoGeneratedTag?: {
    name: string;
    icon: string;
    color: string;
  };

  /**
   * The date and time the task was created */
  createdAt: Date;
  /**
   * The date and time the task was updated
   */
  updatedAt: Date;

  /**
   * The date and time the task was deleted
   */
  deletedAt?: Date;
}

interface IResearchTaskPeriodic extends IBaseResearchTask {
  executionType: ResearchTaskExecutionType.PERIODIC;
  /**
   * The frequency of the task
   */
  executionPeriodicFrequency: ResearchTaskPeriodicFrequencyType;
  /**
   * The start date of the task
   */
  executionPeriodicStartAt: Date;
  /**
   * The end date of the task
   */
  executionPeriodicEndAt: Date;

  /**
   * The date and time the task was last executed
   */
  lastExecutionAt?: Date;
}
interface IResearchTaskScheduled extends IBaseResearchTask {
  executionType: ResearchTaskExecutionType.SCHEDULED;
  /**
   * The date and time the task is scheduled to run
   */
  executionScheduledAt: Date;
}
interface IResearchTaskOnDemand extends IBaseResearchTask {
  executionType: ResearchTaskExecutionType.ON_DEMAND;
}

export interface DiscoveredLink {
  /**
   * The URL of the link
   */
  url: string;
  /**
   * The text of the link
   */
  text?: string;

  /**
   * The status of the link for relevance scoring
   *
   * pending: The link is pending to be processed
   * processing: The link is being processed
   * completed: The link has been processed
   */
  status: 'pending' | 'processing' | 'failed' | 'completed';

  /**
   * The file type of the link
   */
  fileType?: string;
  /**
   * The relevance of the link
   */
  relevance?: number;
  /**
   * Whether the link is recommended
   */
  isRecommended?: boolean;
  /**
   * Whether the link is downloadable
   */
  isDownloadable?: boolean;

  /**
   * The research data ID that the link is associated with
   */
  researchDataId?: string;

  /**
   * The source URL of the link from IResearchTaskScrape.urls
   */
  sourceUrl?: string;
}

export type IResearchTaskExecution = IResearchTaskPeriodic | IResearchTaskScheduled | IResearchTaskOnDemand;

/**
 * A research task that scrapes a website
 */
export type IResearchTaskScrape = IResearchTaskExecution & {
  type: ResearchTaskType.SCRAPE;
  /**
   * The URL of the website to scrape (legacy single URL - deprecated)
   * @deprecated
   */
  url?: string;
  /**
   * Whether the task can discover links
   */
  canDiscoverLinks: boolean;
  /**
   * The links that were discovered in the content (legacy - deprecated)
   */
  discoveredLinks?: DiscoveredLink[];

  /**
   * Multiple URLs to scrape in this task
   */
  urls: string[];

  /**
   * The prompt of the task, this is the prompt that will be used to generate the research data
   */
  prompt?: string;
};

/**
 * A research task that discovers Salesforce opportunities
 *
 * FOR NOW THIS IS NOT USED
 */
export type IResearchTaskSalesforce = IResearchTaskExecution & {
  type: ResearchTaskType.SALESFORCE;
  /**
   * The Salesforce ID of the task
   */
  salesforceId: string;
};

/**
 * A research task that performs deep research using iterative web search and analysis
 */
export type IResearchTaskDeepResearch = IResearchTaskExecution & {
  type: ResearchTaskType.DEEP_RESEARCH;
  /**
   * Maximum number of research iterations (default: 7, max: 10)
   */
  maxDepth?: number;
  /**
   * Maximum research duration in minutes (default: 4.5, max: 10)
   */
  duration?: number;
};

/**
 * A research task that can be either a scrape task, Salesforce task, or deep research task
 */
export type IResearchTask = IResearchTaskScrape | IResearchTaskSalesforce | IResearchTaskDeepResearch;

export type IResearchTaskWithData = IResearchTask & {
  researchData: IResearchDataWithFiles[];
};

export interface IResearchTaskRepository extends IBaseRepository<IResearchTask> {
  /**
   * Find a research task by ID and user ID
   */
  findByIdAndUserId(id: string, userId: string): Promise<IResearchTask | null>;
  /**
   * Find all research tasks by user ID
   */
  findAllByUserId(userId: string): Promise<IResearchTask[]>;
  /**
   * Search for research tasks
   */
  search(
    search: string,
    filters: { userId?: string },
    pagination: { page: number; limit: number },
    orderBy: { by: string; direction: 'asc' | 'desc' }
  ): Promise<{
    data: IResearchTask[];
    hasMore: boolean;
    total: number;
  }>;

  /**
   * Update many research tasks by research agent ID
   */
  updateManyByResearchAgentId(researchAgentId: string, update: Partial<IResearchTask>): Promise<unknown>;

  /**
   * Find all research tasks by user ID and research agent ID
   */
  findAllByUserIdAndResearchAgentId(userId: string, researchAgentId: string): Promise<IResearchTask[]>;
}

export interface IResearchTaskJobs {
  /**
   * Process the research task
   * @param id The ID of the research task
   * @param userId The ID of the user
   */
  process(id: string, userId: string): Promise<void>;

  /**
   * Process the discovered links
   * @param id The ID of the research task
   * @param userId The ID of the user
   */
  processDiscoveredLinks(id: string, userId: string): Promise<void>;

  /**
   * Download the relevant links
   * @param id The ID of the research task
   * @param userId The ID of the user
   */
  downloadRelevantLinks(id: string, userId: string): Promise<void>;

  /**
   * Send a status update to the client
   * @param id The ID of the research task
   * @param update The update to send
   */
  sendToClient(
    researchTask: IResearchTask,
    update: { status: string; currentStep: string; progress: number }
  ): Promise<void>;
}
