/**
 * Software Project Scheduling Types for B4M Pi
 *
 * SWAG Engine (Scientific Wild-Ass Guess) + Gantt scheduling
 * Lifted from optimal-viz project.
 */

/**
 * A software task (GitHub issue, JIRA ticket, etc.)
 */
export interface SoftwareTask {
  // Identity
  id: string;
  title: string;
  description: string;
  url?: string;

  // Classification
  type: 'bug' | 'feature' | 'refactor' | 'task' | 'subtask' | 'epic' | 'unknown';
  /** Original issue type name from source (e.g. Jira custom types like "Spike", "Design Task") */
  issueTypeName?: string;
  /** Current workflow status (e.g. "In Progress", "To Do") - primarily from Jira */
  status?: string;
  priority: 'P0' | 'P1' | 'P2' | 'P3' | 'unknown';
  labels: string[];
  labelColors?: Record<string, string>; // label name → hex color (e.g. "d73a4a")

  // Dependencies
  predecessors: string[]; // Task IDs that must complete first
  blockedBy?: string[]; // External blockers (text descriptions)

  // Assignment
  assignee?: string; // Engineer ID if assigned
  requiredSkills?: string[];

  // Time constraints
  hardDeadline?: number; // Timestamp - client commitment
  softDeadline?: number; // Timestamp - target

  // Stack ranking vectors (0-10 scale, optional - can be inferred)
  reach?: number; // How many users affected
  retention?: number; // Does it keep users coming back
  revenue?: number; // Direct/indirect monetization
  romance?: number; // Team excitement, learning opportunity
  confidence?: number; // Estimate certainty
  foundation?: number; // 0 = edge polish, 10 = core infrastructure/platform
  visibility?: number; // 0 = invisible plumbing, 10 = hero feature users notice

  // Source tracking
  source: 'github' | 'jira' | 'csv' | 'manual';
  sourceId?: string;

  // Raw text for AI analysis
  rawText: string;
}

/**
 * SWAG (Scientific Wild-Ass Guess) estimate generated by AI
 */
export interface SWAGEstimate {
  taskId: string;

  // Duration estimate with uncertainty (in hours)
  duration: {
    p50: number; // Median case
    p80: number; // Conservative
    p95: number; // Worst realistic
  };

  // What the AI inferred
  inferredComplexity: 'trivial' | 'simple' | 'medium' | 'complex' | 'epic';
  inferredSkills: string[];
  inferredType: 'bug' | 'feature' | 'refactor' | 'integration' | 'config';

  // Similar completed work (for calibration)
  similarClosedIssues: SimilarIssue[];

  // Confidence in the SWAG (0-1)
  confidence: number;
  confidenceFactors: string[];

  // Adjustment factors
  adjustments: {
    ifAssignedTo: Record<string, number>; // Engineer ID → multiplier
    ifBlockedBy: Record<string, number>; // Blocker type → delay hours
  };

  // Explanation for humans
  reasoning: string;

  // Inferred stack ranking (if not provided)
  inferredStackRanking?: {
    reach: number; // How many users affected
    retention: number; // Does it keep users coming back
    revenue: number; // Direct/indirect monetization
    romance: number; // Team excitement, learning opportunity
    confidence: number; // Estimate certainty
    foundation: number; // 0 = edge polish, 10 = core infrastructure/platform
    visibility: number; // 0 = invisible plumbing, 10 = hero feature users notice
  };

  // Anomaly detection - flags estimates that deviate significantly from historical norms
  anomaly?: {
    deviationRatio: number; // estimate p50 / historical median (>2 or <0.5 = flagged)
    historicalMedianHours: number; // the historical median for this task type
    historicalCount: number; // sample size behind the median
    direction: 'over' | 'under'; // estimate is higher or lower than expected
    description: string; // human-readable explanation
  };
}

export interface SimilarIssue {
  issueId: string;
  title: string;
  similarity: number; // 0-1 semantic similarity
  actualDuration: number; // How long it really took (hours)
  completedBy?: string; // Who did it
}

/**
 * Engineer/resource for software projects
 */
export interface SoftwareEngineer {
  id: string;
  name: string;

  // Skills (learned from completed work)
  skills: string[];
  skillStrengths: Record<string, number>; // Skill → proficiency 0-1

  // Velocity (learned from history)
  velocity: {
    overall: number; // Issues/week average
    byType: Record<string, number>; // Type → issues/week
    byComplexity: Record<string, number>; // Complexity → multiplier
    trend: 'improving' | 'stable' | 'declining';
  };

  // Availability
  availability: {
    hoursPerWeek: number;
    currentLoad: number; // 0-100%
  };

  // Repo constraints
  allowedRepos?: string[]; // If set, engineer can only work on tasks from these repos

  // For new engineers
  isRamping: boolean;
  rampStartDate?: number;
  rampMultiplier?: number; // Current productivity multiplier (0-1)
}

/**
 * Software project scheduling problem
 */
export interface SoftwareProject {
  id: string;
  name: string;
  description: string;
  createdAt: number;
  updatedAt: number;

  // Tasks to schedule
  tasks: SoftwareTask[];

  // SWAG estimates (generated by AI)
  estimates: SWAGEstimate[];

  // Team
  engineers: SoftwareEngineer[];

  // Constraints
  constraints: SoftwareProjectConstraints;

  // Objective
  objective: SoftwareProjectObjective;

  // Solver mode
  mode: SolverMode;

  // Duration mode - which estimate percentile to use (default: p50)
  durationMode?: DurationMode;
}

export interface SoftwareProjectConstraints {
  // Time constraints
  sprintLengthDays?: number;
  planningHorizonDays?: number;

  // Capacity constraints
  maxHoursPerEngineerPerDay?: number;
  respectAvailability: boolean;

  // Skill constraints
  requireSkillMatch: boolean;

  // Hard deadlines (must satisfy)
  hardDeadlinesMustMeet: boolean;

  // If true, only schedule tasks with explicit assignees; unassigned tasks are skipped
  respectAssignments?: boolean;
}

export interface SoftwareProjectObjective {
  // Primary objective
  primary: 'minimize_makespan' | 'maximize_value' | 'minimize_risk' | 'balanced';

  // Weights for multi-objective (0-1, should sum to ~1)
  weights?: {
    makespan: number; // Lower is better
    value: number; // Higher is better (stack ranking score)
    risk: number; // Lower is better (prefer high confidence)
    morale: number; // Romance balance
  };
}

/**
 * Duration mode - which estimate percentile the solver uses for scheduling
 */
export type DurationMode = 'p50' | 'p80' | 'p95';

/**
 * Solver mode - different optimization profiles
 */
export type SolverMode =
  | 'only_bugs' // Minimize time to zero P1/P2
  | 'strategic' // Maximize synergy + revenue
  | 'quick_wins' // Max tasks in 1 week
  | 'max_fun' // Maximize romance
  | 'revenue_protection' // Retention ≥ 8 OR revenue ≥ 7
  | 'deadline_sprint' // Minimize P(miss deadline)
  | 'balanced'; // Pareto-optimal

/**
 * Scheduled task output
 */
export interface ScheduledSoftwareTask {
  taskId: string;
  engineerId: string;
  engineerName: string;

  // Timing (in hours from schedule start)
  startTime: number;
  endTime: number;
  duration: number;

  // Confidence
  completionConfidence: number;
  riskFactors: string[];
}

/**
 * Software schedule result
 */
export interface SoftwareScheduleResult {
  schedule: ScheduledSoftwareTask[];

  // Metrics
  makespan: number; // Total schedule duration (hours)
  totalValue: number; // Sum of task values
  averageConfidence: number;
  tasksScheduled: number;
  tasksUnscheduled: number;

  // By engineer breakdown
  engineerLoads: Record<string, number>; // Engineer ID → total hours

  // Deadline analysis
  deadlinesMet: number;
  deadlinesMissed: number;
  deadlinesAtRisk: string[]; // Task IDs

  // Solver info
  solverName: string;
  solveTimeMs: number;
  iterations: number;
  solutionQuality: 'optimal' | 'near-optimal' | 'feasible' | 'unknown';
}

/**
 * Human correction to propagate
 */
export interface TaskCorrection {
  taskId: string;
  correctionType: 'easier' | 'harder';
  reason: string;
  newDurationMultiplier?: number; // e.g., 0.4 for "40% of original estimate"

  // What the system learned
  inferredPattern?: string; // e.g., "auth-library-reuse"
  affectedTasks?: string[]; // Other tasks updated
}

/**
 * Calculate stack ranking value for a task
 *
 * Stack Ranking Schema:
 * - Core 3R: Reach (x2), Retention (x3), Revenue (x5)
 * - Extended: Romance (x1.5), Confidence (x1.5), Foundation (x2), Visibility (x1.5)
 *
 * Foundation vs Visibility creates a useful 2x2:
 * - High Foundation + High Visibility = Major feature that establishes platform
 * - High Foundation + Low Visibility = Infrastructure investment
 * - Low Foundation + High Visibility = UI polish, quick wins, delighters
 * - Low Foundation + Low Visibility = Bug fixes, maintenance, cleanup
 */
export function calculateTaskValue(task: SoftwareTask, estimate?: SWAGEstimate): number {
  // Use provided values or inferred values or defaults
  const reach = task.reach ?? estimate?.inferredStackRanking?.reach ?? 5;
  const retention = task.retention ?? estimate?.inferredStackRanking?.retention ?? 5;
  const revenue = task.revenue ?? estimate?.inferredStackRanking?.revenue ?? 5;
  const romance = task.romance ?? estimate?.inferredStackRanking?.romance ?? 5;
  const confidence = task.confidence ?? estimate?.inferredStackRanking?.confidence ?? 5;
  const foundation = task.foundation ?? estimate?.inferredStackRanking?.foundation ?? 5;
  const visibility = task.visibility ?? estimate?.inferredStackRanking?.visibility ?? 5;

  // Core 3R (business impact)
  const coreScore = reach * 2.0 + retention * 3.0 + revenue * 5.0;

  // Extended factors (team + estimation + strategic positioning)
  const extendedScore = romance * 1.5 + confidence * 1.5 + foundation * 2.0 + visibility * 1.5;

  return coreScore + extendedScore;
}

// Resource Allocation Types

/**
 * Resource allocation project (multi-project planning)
 * Inspired by an established planner pattern
 */
export interface ResourceProject {
  id: string;
  name: string;
  color: string; // For visual identification

  // Timeline (0-11 for Jan-Dec, or week numbers)
  startPeriod: number;
  endPeriod: number;

  // Phases within the project
  phases: ResourcePhase[];

  // Metadata
  priority: number; // Display order (lower = higher priority)
  status: 'active' | 'planned' | 'completed' | 'on_hold';
}

/**
 * Phase within a project (QA, Development, Maintenance, Launch, etc.)
 */
export interface ResourcePhase {
  id: string;
  name: string;
  color: string; // Phase-specific color

  // Percentage of project duration (0-100)
  pct: number;

  // Team assignments: resource ID -> allocation percentage (0-100)
  teamWeights: Record<string, number>;
}

/**
 * Resource (team member) for allocation planning
 */
export interface Resource {
  id: string;
  name: string;
  role?: string;

  // Skills/tags for filtering
  skills: string[];

  // Monthly/weekly availability (period key -> percentage 0-100)
  // e.g., { "2026-01": 100, "2026-02": 80 } or { "W1": 100, "W2": 50 }
  availability: Record<string, number>;

  // Link to SoftwareEngineer if available (for velocity data)
  engineerId?: string;
}

/**
 * Computed allocation for a resource in a period
 */
export interface ResourceAllocation {
  resourceId: string;
  period: string; // "2026-01" or "W1"

  // Allocations by project
  allocations: {
    projectId: string;
    projectName: string;
    phaseId: string;
    phaseName: string;
    percentage: number;
  }[];

  // Total percentage (should be ≤100 for no conflict)
  totalPercentage: number;
}

/**
 * Resource conflict (over-allocation warning)
 */
export interface ResourceConflict {
  resourceId: string;
  resourceName: string;
  period: string;

  // What caused the conflict
  allocations: {
    projectId: string;
    projectName: string;
    percentage: number;
  }[];

  // Total allocation (>100 means conflict)
  totalPercentage: number;

  // Severity
  severity: 'warning' | 'critical'; // warning: 100-120%, critical: >120%
}

/**
 * Resource allocation plan (full planning state)
 */
export interface ResourceAllocationPlan {
  id: string;
  name: string;

  // Planning period type
  periodType: 'monthly' | 'weekly';
  startPeriod: string; // "2026-01" or "2026-W01"
  endPeriod: string;

  // Data
  projects: ResourceProject[];
  resources: Resource[];

  // Computed fields (generated from projects and resources)
  allocations?: ResourceAllocation[];
  conflicts?: ResourceConflict[];

  // Metadata
  createdAt: number;
  updatedAt: number;
}

/**
 * Calculate resource allocations from projects
 */
export function calculateResourceAllocations(
  projects: ResourceProject[],
  resources: Resource[],
  startPeriod: number,
  endPeriod: number
): ResourceAllocation[] {
  const allocations: Map<string, ResourceAllocation> = new Map();

  // Initialize allocations for each resource-period combination
  for (const resource of resources) {
    for (let period = startPeriod; period <= endPeriod; period++) {
      const key = `${resource.id}-${period}`;
      allocations.set(key, {
        resourceId: resource.id,
        period: period.toString(),
        allocations: [],
        totalPercentage: 0,
      });
    }
  }

  // Calculate allocations from projects
  for (const project of projects) {
    if (project.status !== 'active' && project.status !== 'planned') continue;

    const projectDuration = project.endPeriod - project.startPeriod + 1;

    for (const phase of project.phases) {
      // Calculate phase periods
      const phaseStartOffset =
        project.phases.slice(0, project.phases.indexOf(phase)).reduce((sum, p) => sum + p.pct, 0) / 100;
      const phaseEndOffset = phaseStartOffset + phase.pct / 100;

      const phaseStartPeriod = Math.floor(project.startPeriod + phaseStartOffset * projectDuration);
      const phaseEndPeriod = Math.min(
        Math.floor(project.startPeriod + phaseEndOffset * projectDuration),
        project.endPeriod
      );

      // Add allocations for each team member in this phase
      for (const [resourceId, percentage] of Object.entries(phase.teamWeights)) {
        if (percentage <= 0) continue;

        for (let period = phaseStartPeriod; period <= phaseEndPeriod; period++) {
          if (period < startPeriod || period > endPeriod) continue;

          const key = `${resourceId}-${period}`;
          const allocation = allocations.get(key);
          if (allocation) {
            allocation.allocations.push({
              projectId: project.id,
              projectName: project.name,
              phaseId: phase.id,
              phaseName: phase.name,
              percentage,
            });
            allocation.totalPercentage += percentage;
          }
        }
      }
    }
  }

  return Array.from(allocations.values());
}

/**
 * Detect resource conflicts from allocations
 */
export function detectResourceConflicts(allocations: ResourceAllocation[], resources: Resource[]): ResourceConflict[] {
  const resourceMap = new Map(resources.map(r => [r.id, r]));
  const conflicts: ResourceConflict[] = [];

  for (const allocation of allocations) {
    if (allocation.totalPercentage > 100) {
      const resource = resourceMap.get(allocation.resourceId);
      conflicts.push({
        resourceId: allocation.resourceId,
        resourceName: resource?.name || allocation.resourceId,
        period: allocation.period,
        allocations: allocation.allocations.map(a => ({
          projectId: a.projectId,
          projectName: a.projectName,
          percentage: a.percentage,
        })),
        totalPercentage: allocation.totalPercentage,
        severity: allocation.totalPercentage > 120 ? 'critical' : 'warning',
      });
    }
  }

  return conflicts;
}
