import { asyncHandler } from '@server/middlewares/asyncHandler';
import { baseApi } from '@server/middlewares/baseApi';
import { researchTaskService } from '@bike4mind/services';
import {
  researchAgentRepository,
  withTransaction,
  researchTaskRepository,
  researchDataRepository,
  taskScheduleRepository,
} from '@bike4mind/database';
import { researchTaskJobs } from '@server/jobs/researchTasks';
import { ResearchTaskType, ResearchTaskExecutionType } from '@bike4mind/common';
import * as z from 'zod';

const idParamSchema = z.object({ id: z.string() });

// Allowlist of all fields any task type may send. The service's own secureParameters
// call enforces type-specific constraints (required urls for SCRAPE, date fields for
// PERIODIC, etc.) — this schema's job is to strip unknown keys before that layer.
const taskCreateBodySchema = z.object({
  title: z.string().max(100),
  description: z.string().max(500),
  type: z.nativeEnum(ResearchTaskType),
  executionType: z.nativeEnum(ResearchTaskExecutionType).default(ResearchTaskExecutionType.ON_DEMAND),
  prompt: z.string().max(500).optional(),
  fileTagId: z.string().optional(),
  autoGeneratedTag: z.object({ name: z.string(), icon: z.string(), color: z.string() }).optional(),
  // SCRAPE
  urls: z.array(z.string()).optional(),
  canDiscoverLinks: z.boolean().optional(),
  // PERIODIC
  executionPeriodicStartAt: z.coerce.date().optional(),
  executionPeriodicEndAt: z.coerce.date().optional(),
  executionPeriodicFrequency: z.string().optional(),
  // SCHEDULED
  executionScheduledAt: z.coerce.date().optional(),
  // DEEP_RESEARCH
  maxDepth: z.number().min(1).max(10).optional(),
});

const handler = baseApi({ auth: true })
  .get(
    asyncHandler(async (req, res) => {
      const { id } = idParamSchema.parse(req.query);
      const result = await researchTaskService.listByAgentId(
        req.user as any,
        { researchAgentId: id },
        {
          db: {
            researchTasks: researchTaskRepository,
          },
        }
      );

      return res.json(result);
    })
  )
  .post(
    asyncHandler(async (req, res) => {
      const { id } = idParamSchema.parse(req.query);
      const body = taskCreateBodySchema.parse(req.body);
      const result = await researchTaskService.create(
        req.user as any,
        { ...body, researchAgentId: id },
        {
          db: {
            transaction: withTransaction,
            researchTasks: researchTaskRepository,
            researchAgents: researchAgentRepository,
            taskSchedules: taskScheduleRepository,
          },
          jobs: {
            researchTasks: researchTaskJobs,
          },
        }
      );

      return res.json(result);
    })
  )
  .delete(
    asyncHandler(async (req, res) => {
      const { id } = idParamSchema.parse(req.query);
      const result = await researchTaskService.remove(
        req.user as any,
        { id },
        {
          db: {
            researchTasks: researchTaskRepository,
            researchDatas: researchDataRepository,
          },
        }
      );

      return res.json(result);
    })
  );

export const config = {
  api: {
    externalResolver: true,
  },
};

export default handler;
