import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildDeploymentOpenApiDocument, loadDeploymentContracts } from './deployment';

/**
 * Build-time entry for the deployment spec served at /api/v1/openapi.deployment.json.
 * Run via `pnpm --filter @bike4mind/common openapi:generate:deployment`; the client
 * prebuild/predev run it after the premium glue codegen, which emits the contract list
 * this reads.
 *
 * The list is loaded by path, not imported, so this package neither typechecks against
 * add-on sources nor fails when the gitignored file is missing (an install-only checkout):
 * missing means no add-on contracts. The committed apps/client/public/openapi.json is
 * never touched - generate.ts owns it.
 */

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../../..');
const generatedDir = resolve(repoRoot, 'apps/client/server/premium-generated');
const contractsPath = resolve(generatedDir, 'premiumContracts.generated.ts');
const outputPath = resolve(generatedDir, 'deploymentOpenApi.generated.ts');

const pkg = JSON.parse(readFileSync(resolve(here, '../../package.json'), 'utf8')) as { version: string };

const extraContracts = await loadDeploymentContracts(contractsPath);

const document = buildDeploymentOpenApiDocument(pkg.version, extraContracts);

mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  outputPath,
  '// AUTO-GENERATED by b4m-core/common/src/openapi/generateDeployment.ts - do not edit.\n' +
    '// Gitignored; reset to null by apps/client/scripts/generate-premium-glue.mjs.\n\n' +
    `export const deploymentOpenApiSpec: ({ servers?: ReadonlyArray<{ url?: string }> } & Record<string, unknown>) | null = ${JSON.stringify(document, null, 2)};\n`,
  'utf8'
);

console.log(`[openapi] wrote ${outputPath} (${extraContracts.length} add-on contract(s))`);
