import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi';
import type { EndpointContract } from '../api-contract/types';
import { buildDeploymentOpenApiDocument } from './deployment';

/**
 * Build-time entry for the deployment spec served at /api/v1/openapi.deployment.json.
 * Run via `pnpm --filter @bike4mind/common openapi:generate:deployment`; the client
 * prebuild/predev run it after the premium glue codegen, which emits the contract list
 * this reads.
 *
 * The list is loaded by path, not imported, so this package neither typechecks against
 * add-on sources nor fails when the gitignored file is missing (an install-only checkout):
 * missing means no add-on contracts. The committed apps/client/public/openapi.json is
 * never touched - generate.ts owns it.
 */

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../../..');
const generatedDir = resolve(repoRoot, 'apps/client/server/premium-generated');
const contractsPath = resolve(generatedDir, 'premiumContracts.generated.ts');
const outputPath = resolve(generatedDir, 'deploymentOpenApi.generated.ts');

const pkg = JSON.parse(readFileSync(resolve(here, '../../package.json'), 'utf8')) as { version: string };

// The contract list is loaded as CommonJS (apps/client is not an ES module package),
// so add-on schemas are built from zod's CJS build, a separate class hierarchy from the
// ESM one registry.ts extends. Without this, registering them fails on `.openapi()`.
extendZodWithOpenApi(createRequire(import.meta.url)('zod'));

const extraContracts: readonly EndpointContract[] = existsSync(contractsPath)
  ? ((await import(pathToFileURL(contractsPath).href)) as { premiumContracts: readonly EndpointContract[] })
      .premiumContracts
  : [];

const document = buildDeploymentOpenApiDocument(pkg.version, extraContracts);

mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  outputPath,
  '// AUTO-GENERATED by b4m-core/common/src/openapi/generateDeployment.ts - do not edit.\n' +
    '// Gitignored; reset to null by apps/client/scripts/generate-premium-glue.mjs.\n\n' +
    `export const deploymentOpenApiSpec: Record<string, unknown> | null = ${JSON.stringify(document, null, 2)};\n`,
  'utf8'
);

console.log(`[openapi] wrote ${outputPath} (${extraContracts.length} add-on contract(s))`);
