import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildDeploymentOpenApiDocument, loadDeploymentContracts } from './deployment';

// This file sits at b4m-core/common/src/openapi/, four levels below the monorepo root.
export const MONOREPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../../..');

export const GENERATED_DIR = 'apps/client/server/premium-generated';

/**
 * Read the add-on contract list under `repoRoot` and write the deployment spec module the
 * /api/v1/openapi.deployment.json route imports. With no add-on contracts the module
 * exports null and the route serves the committed core spec.
 */
export async function writeDeploymentOpenApiModule(options: {
  repoRoot: string;
  version: string;
}): Promise<{ outputPath: string; contractCount: number }> {
  const generatedDir = resolve(options.repoRoot, GENERATED_DIR);
  const contractsPath = resolve(generatedDir, 'premiumContracts.generated.ts');
  const outputPath = resolve(generatedDir, 'deploymentOpenApi.generated.ts');

  const extraContracts = await loadDeploymentContracts(contractsPath);
  const document = buildDeploymentOpenApiDocument(options.version, extraContracts);

  mkdirSync(generatedDir, { recursive: true });
  writeFileSync(
    outputPath,
    '// AUTO-GENERATED by b4m-core/common/src/openapi/generateDeployment.ts - do not edit.\n' +
      '// Gitignored; reset to null by apps/client/scripts/generate-premium-glue.mjs.\n\n' +
      "import type { DeploymentOpenApiSpec } from '../utils/openApiSpecHandler';\n\n" +
      `export const deploymentOpenApiSpec: DeploymentOpenApiSpec | null = ${JSON.stringify(document, null, 2)};\n`,
    'utf8'
  );

  return { outputPath, contractCount: extraContracts.length };
}

/**
 * What `openapi:generate:deployment` runs: sources the spec version from
 * `repoRoot`/b4m-core/common/package.json, then writes the module. Throws on a missing
 * version - JSON.stringify would drop an undefined `info.version` and serve an invalid spec.
 */
export async function generateDeploymentOpenApiModule(
  repoRoot: string = MONOREPO_ROOT
): Promise<{ outputPath: string; contractCount: number }> {
  const pkgPath = resolve(repoRoot, 'b4m-core/common/package.json');
  const pkg: unknown = JSON.parse(readFileSync(pkgPath, 'utf8'));
  const version = typeof pkg === 'object' && pkg !== null && 'version' in pkg ? pkg.version : undefined;
  if (typeof version !== 'string' || version === '') {
    throw new Error(`[openapi] ${pkgPath} has no version for the deployment spec`);
  }
  return writeDeploymentOpenApiModule({ repoRoot, version });
}
