import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '@client/app/contexts/ApiContext';
import { toast } from 'sonner';
import {
  IResearchTask,
  ResearchTaskType,
  ResearchTaskStatus,
  IResearchTaskWithData,
  ResearchTaskExecutionType,
  ResearchTaskPeriodicFrequencyType,
} from '@bike4mind/common';
import { isAxiosError } from 'axios';
import { useWebsocket } from '@client/app/contexts/WebsocketContext';
import { useEffect, useState } from 'react';

export interface CreateResearchTaskInput {
  type: ResearchTaskType;
  title: string;
  description: string;
  executionType: ResearchTaskExecutionType;
  executionPeriodicStartAt?: Date;
  executionPeriodicEndAt?: Date;
  executionPeriodicFrequency?: ResearchTaskPeriodicFrequencyType;
  executionScheduledAt?: Date;
  urls?: string[];
  canDiscoverLinks?: boolean;
  prompt?: string;
  maxDepth?: number;
  researchAgentId: string;
  fileTagId?: string;
  autoGeneratedTag?: {
    name: string;
    icon: string;
    color: string;
  };
}

export interface UpdateResearchTaskInput {
  title?: string;
  description?: string;
  status?: ResearchTaskStatus;
  urls?: string[];
  canDiscoverLinks?: boolean;
  researchAgentId: string;
}

export interface SearchResearchTasksParams {
  search?: string;
  page?: number;
  limit?: number;
  orderBy?: {
    by: string;
    direction: 'asc' | 'desc';
  };
}

export function useSearchResearchTasks(params: SearchResearchTasksParams = {}) {
  const { search = '', page = 1, limit = 10, orderBy = { by: 'createdAt', direction: 'desc' } } = params;

  return useQuery({
    queryKey: ['research-tasks', 'search', { search, page, limit, orderBy }],
    queryFn: async () => {
      const response = await api.get<{
        data: IResearchTask[];
        hasMore: boolean;
        total: number;
      }>('/api/research/tasks', {
        params: {
          search,
          page,
          limit,
          orderBy,
        },
      });
      return response.data;
    },
  });
}

export function useGetResearchTask(agentId: string, taskId?: string) {
  return useQuery({
    queryKey: ['research-tasks', taskId],
    queryFn: async () => {
      const response = await api.get<IResearchTaskWithData>(`/api/research/agents/${agentId}/tasks/${taskId}`);
      return response.data;
    },
    enabled: !!taskId,
    refetchOnWindowFocus: false,
  });
}

export function useCreateResearchTask() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (input: CreateResearchTaskInput) => {
      const response = await api.post<IResearchTask>(`/api/research/agents/${input.researchAgentId}/tasks`, input);
      return response.data;
    },
    onSuccess: data => {
      queryClient.invalidateQueries({ queryKey: ['research-tasks'] });
      queryClient.invalidateQueries({ queryKey: ['research-tasks', 'list', { agentId: data.researchAgentId }] });
      toast.success('Research task created successfully! 🚀 Starting research...');
    },
    onError: error => {
      console.error('Failed to create research task:', error);
      toast.error('Failed to create research task');
    },
  });
}

export function useUpdateResearchTask(taskId: string) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (input: UpdateResearchTaskInput) => {
      const response = await api.put<IResearchTask>(
        `/api/research/agents/${input.researchAgentId}/tasks/${taskId}`,
        input
      );
      return response.data;
    },
    onSuccess: data => {
      queryClient.invalidateQueries({ queryKey: ['research-tasks'] });
      queryClient.invalidateQueries({ queryKey: ['research-tasks', data.id] });
      queryClient.invalidateQueries({ queryKey: ['research-tasks', 'list', { agentId: data.researchAgentId }] });
      toast.success('Research task updated successfully');
    },
    onError: error => {
      console.error('Failed to update research task:', error);
      toast.error('Failed to update research task');
    },
  });
}

export function useDeleteResearchTask() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (taskId: string) => {
      await api.delete(`/api/research/tasks/${taskId}`);
      return taskId;
    },
    onSuccess: taskId => {
      queryClient.invalidateQueries({ queryKey: ['research-tasks'] });
      queryClient.invalidateQueries({ queryKey: ['research-tasks', taskId] });
      toast.success('Research task deleted successfully');
    },
    onError: error => {
      console.error('Failed to delete research task:', error);
      toast.error('Failed to delete research task');
    },
  });
}

export function useListResearchTasksByAgentId(agentId: string) {
  return useQuery({
    queryKey: ['research-tasks', 'list', { agentId }],
    queryFn: async () => {
      const response = await api.get<IResearchTask[]>(`/api/research/agents/${agentId}/tasks`);
      return response.data;
    },
    enabled: !!agentId,
    refetchOnWindowFocus: false,
    refetchOnMount: false,
  });
}

export function useRemoveResearchTask() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (task: IResearchTask) => {
      await api.delete(`/api/research/agents/${task.researchAgentId}/tasks/${task.id}`);

      return task;
    },
    onSuccess: task => {
      queryClient.invalidateQueries({
        queryKey: ['research-tasks', 'list', { agentId: task.researchAgentId }],
        exact: true,
      });
      toast.success('Research task deleted successfully');
    },
    onError: e => {
      console.log(e);
      if (isAxiosError(e)) {
        toast.error(`Failed to delete research task: ${e.response?.data.error}`);
      }
    },
  });
}

export function useRetryResearchTask() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (task: IResearchTask) => {
      const result = await api.post(`/api/research/agents/${task.researchAgentId}/tasks/${task.id}/retry`);
      return result.data;
    },
    onSuccess: data => {
      queryClient.invalidateQueries({ queryKey: ['research-tasks'] });
      queryClient.invalidateQueries({ queryKey: ['research-tasks', data.id] });
      queryClient.invalidateQueries({ queryKey: ['research-tasks', 'list', { agentId: data.researchAgentId }] });
      toast.success('Research task retried successfully');
    },
    onError: error => {
      console.error('Failed to retry research task:', error);
      if (isAxiosError(error)) {
        toast.error(`Failed to retry research task: ${error.response?.data.error}`);
      }
    },
  });
}

export const useResearchTaskWebSocket = (taskId: string | undefined) => {
  const { subscribeToAction } = useWebsocket();
  const [liveStatus, setLiveStatus] = useState<{
    status: string;
    currentStep: string;
    progress: number;
  } | null>(null);

  useEffect(() => {
    if (!taskId) return;

    console.log(`🔌 [WEBSOCKET] Subscribing to research task updates for task: ${taskId}`);

    const unsubscribe = subscribeToAction('research_task_status_update', async message => {
      console.log(`📨 [WEBSOCKET] Received message:`, message);

      if (message.action === 'research_task_status_update' && message.taskId === taskId) {
        console.log(`✅ [WEBSOCKET] Match found for task ${taskId}:`, {
          status: message.status,
          currentStep: message.currentStep,
          progress: message.progress,
        });

        setLiveStatus({
          status: message.status,
          currentStep: message.currentStep,
          progress: message.progress,
        });
      } else {
        console.log(
          `❌ [WEBSOCKET] Message not for this task. Expected: ${taskId}, Got type: ${(message as any).taskId}`
        );
      }
    });

    return () => {
      console.log(`🔌 [WEBSOCKET] Unsubscribing from research task updates for task: ${taskId}`);
      unsubscribe();
    };
  }, [taskId, subscribeToAction]);

  return liveStatus;
};
