import mongoose from 'mongoose';
import BaseRepository from '@bike4mind/db-core';
import { IResearchTask, IResearchTaskRepository } from '@bike4mind/common';
import { escapeRegex } from '@bike4mind/utils/escapeRegex';
import { softDeletePlugin } from '../../utils/mongo';

const DiscoveredLinkSchema = new mongoose.Schema({
  url: { type: String, required: true },
  text: { type: String },
  status: { type: String, enum: ['pending', 'completed', 'failed'], required: true },
  fileType: { type: String },
  relevance: { type: Number },
  isRecommended: { type: Boolean },
  isDownloadable: { type: Boolean },
  sourceUrl: { type: String },
  researchDataId: { type: String },
});

const ResearchTaskSchema = new mongoose.Schema(
  {
    userId: { type: String, required: true },
    researchAgentId: { type: String, required: true },
    type: { type: String, enum: ['scrape', 'salesforce', 'deepResearch'], required: true },
    title: { type: String, required: true },
    description: { type: String, required: true },
    executionType: { type: String, enum: ['on-demand', 'periodic', 'scheduled'], required: true },
    researchDataId: { type: String },
    organizationId: { type: String },

    // Status fields
    status: { type: String, enum: ['pending', 'processing', 'completed', 'failed'], required: true },
    statusFailedMessage: { type: String },
    statusFailedAt: { type: Date },
    statusCompletedAt: { type: Date },

    url: { type: String },
    canDiscoverLinks: { type: Boolean },
    discoveredLinks: { type: [DiscoveredLinkSchema] },
    prompt: { type: String },

    // Multiple URLs support
    urls: [{ type: String }],

    // Deep research fields
    maxDepth: { type: Number },

    // Tag fields for automatic file organization
    fileTagId: { type: String },
    autoGeneratedTag: {
      name: { type: String },
      icon: { type: String },
      color: { type: String },
    },

    // Execution fields
    executionPeriodicStartAt: { type: Date },
    executionPeriodicEndAt: { type: Date },
    executionPeriodicFrequency: { type: String, enum: ['daily', 'weekly', 'monthly'], required: false },
    executionScheduledAt: { type: Date },
    lastExecutionAt: { type: Date },

    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },
  },
  {
    toJSON: {
      virtuals: true,
    },
    toObject: {
      virtuals: true,
    },
  }
);

ResearchTaskSchema.plugin(softDeletePlugin);

const ResearchTaskModel =
  (mongoose.models['ResearchTask'] as unknown as mongoose.Model<IResearchTask>) ||
  mongoose.model<IResearchTask>('ResearchTask', ResearchTaskSchema);

class ResearchTaskRepository extends BaseRepository<IResearchTask> implements IResearchTaskRepository {
  constructor(private researchTaskModel: mongoose.Model<IResearchTask>) {
    super(researchTaskModel);
    this.model = researchTaskModel;
  }

  async findByIdAndUserId(id: string, userId: string): Promise<IResearchTask | null> {
    const result = await this.model.findOne({ _id: id, userId });
    return result?.toObject() ?? null;
  }

  async findAllByUserId(userId: string): Promise<IResearchTask[]> {
    const result = await this.model.find({ userId });
    return result.map(doc => doc.toJSON());
  }

  async search(
    search: string,
    filters: {
      userId?: string;
    },
    pagination: {
      page: number;
      limit: number;
    },
    orderBy: {
      by: string;
      direction: string;
    }
    // Explicit return type: declaration emit otherwise expands IResearchTask into
    // union members that are not exported from @bike4mind/common's entry (TS4053).
  ): Promise<{ data: IResearchTask[]; hasMore: boolean; total: number }> {
    const queryConditions: Record<string, unknown> = {};

    if (filters.userId) {
      queryConditions.userId = filters.userId;
    }

    if (search) {
      queryConditions.$or = [
        { title: { $regex: escapeRegex(search), $options: 'si' } },
        { description: { $regex: escapeRegex(search), $options: 'si' } },
      ];
    }

    const total = await this.model.countDocuments(queryConditions);

    const query = this.model.find(queryConditions);

    query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit + 1);

    query.sort({ [orderBy.by]: orderBy.direction === 'asc' ? 1 : -1 });

    const result = await query.exec();

    const hasMore = result.length === pagination.limit + 1;
    if (hasMore) result.pop();

    return {
      data: result.map(doc => doc.toJSON()),
      hasMore,
      total,
    };
  }

  /**
   * Update many research tasks by research agent id
   * @param researchAgentId - The research agent id
   * @param update - The update to apply to the research tasks
   */
  async updateManyByResearchAgentId(researchAgentId: string, update: Partial<IResearchTask>) {
    await this.model.updateMany(
      { researchAgentId },
      {
        $set: {
          ...update,
          updatedAt: new Date(),
        },
      }
    );
  }

  /**
   * Find all research tasks by user ID and research agent ID
   * @param userId - The user ID
   * @param researchAgentId - The research agent ID
   * @returns The research tasks
   */
  async findAllByUserIdAndResearchAgentId(userId: string, researchAgentId: string): Promise<IResearchTask[]> {
    const result = await this.model.find({ userId, researchAgentId });

    return result.map(doc => doc.toJSON());
  }
}

export const researchTaskRepository = new ResearchTaskRepository(ResearchTaskModel);
