import { Logger } from '@bike4mind/observability';
import { z } from 'zod';
import { NotFoundError, secureParameters } from '@bike4mind/utils';
import {
  IResearchTaskJobs,
  ITaskScheduleRepository,
  IUserDocument,
  ResearchTaskExecutionType,
  ResearchTaskPeriodicFrequencyType,
  TaskScheduleHandler,
} from '@bike4mind/common';
import {
  IResearchTask,
  IResearchTaskRepository,
  ResearchTaskStatus,
  ResearchTaskType,
  IResearchAgentRepository,
} from '@bike4mind/common';
import { taskSchedulerService } from '..';

const researchTaskCreateSchema = z.object({
  researchAgentId: z.string(),
  title: z.string().max(100),
  description: z.string().max(500),
  prompt: z.string().max(500).optional(),
  type: z.enum(ResearchTaskType),
  executionType: z.enum(ResearchTaskExecutionType).prefault(ResearchTaskExecutionType.ON_DEMAND),
  fileTagId: z.string().optional(),
  autoGeneratedTag: z
    .object({
      name: z.string(),
      icon: z.string(),
      color: z.string(),
    })
    .optional(),
});

const researchTaskScrapeCreateSchema = researchTaskCreateSchema.extend({
  urls: z.array(z.url()).min(1),
  canDiscoverLinks: z.boolean(),
});

const researchTaskPeriodicCreateSchema = researchTaskCreateSchema.extend({
  executionPeriodicStartAt: z.coerce.date(),
  executionPeriodicEndAt: z.coerce.date(),
  executionPeriodicFrequency: z.enum(ResearchTaskPeriodicFrequencyType),
});

const researchTaskScheduledCreateSchema = researchTaskCreateSchema.extend({
  executionScheduledAt: z.coerce.date(),
});

const researchTaskDeepResearchCreateSchema = researchTaskCreateSchema.extend({
  maxDepth: z.number().min(1).max(10).optional(),
});

type ResearchTaskCreateParameters = z.infer<typeof researchTaskCreateSchema>;

interface ResearchTaskCreateAdapters {
  db: {
    transaction: <T>(fn: () => Promise<T>) => Promise<T>;
    researchTasks: IResearchTaskRepository;
    researchAgents: IResearchAgentRepository;
    taskSchedules: ITaskScheduleRepository;
  };
  jobs: {
    researchTasks: IResearchTaskJobs;
  };
  logger?: {
    info: (message: string) => void;
    error: (message: string) => void;
  };
}

export const create = async (
  user: IUserDocument,
  parameters: ResearchTaskCreateParameters,
  { db, jobs, logger }: ResearchTaskCreateAdapters
) => {
  const { title, description, type, researchAgentId, ...rest } = validateParameters(parameters);

  const researchAgent = await db.researchAgents.findByIdAndUserId(researchAgentId, user.id);

  if (!researchAgent) {
    throw new NotFoundError('Research agent not found');
  }

  logger?.info(`Creating research task ${title}`);

  const researchTask = await db.transaction(async () => {
    const buildData: Omit<IResearchTask, 'id'> = {
      title,
      description,
      type,
      userId: user.id,
      researchAgentId,
      ...rest,
      organizationId: user.organizationId ?? undefined,
      status: ResearchTaskStatus.PENDING,
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    const result = await db.researchTasks.create(buildData);

    return result;
  });

  if (researchTask.executionType === ResearchTaskExecutionType.ON_DEMAND) {
    try {
      logger?.info(`Processing research task ${researchTask.id}`);
      await jobs.researchTasks.process(researchTask.id, user.id);
    } catch (e) {
      researchTask.status = ResearchTaskStatus.FAILED;
      researchTask.statusFailedMessage = `Failed to process research task: ${e instanceof Error ? e.message : 'Unknown error'}`;
      researchTask.statusFailedAt = new Date();
      await db.researchTasks.update(researchTask);

      logger?.error(`Failed to process research task ${researchTask.id}: ${e}`);
    }
  } else {
    const processDate =
      researchTask.executionType === ResearchTaskExecutionType.PERIODIC
        ? researchTask.executionPeriodicStartAt
        : researchTask.executionScheduledAt;

    taskSchedulerService.create(
      {
        handler: TaskScheduleHandler.RESEARCH_TASK_PROCESS,
        payload: {
          id: researchTask.id,
          userId: user.id,
        },
        processDate: processDate,
      },
      {
        db,
      }
    );
  }

  return researchTask;
};

const validateParameters = (parameters: ResearchTaskCreateParameters) => {
  let params = secureParameters(parameters, researchTaskCreateSchema);

  switch (params.type) {
    case ResearchTaskType.SCRAPE:
      params = secureParameters(parameters, researchTaskScrapeCreateSchema);
      break;
    case ResearchTaskType.DEEP_RESEARCH:
      Logger.globalInstance.log('researchTaskDeepResearchCreateSchema', researchTaskDeepResearchCreateSchema);
      params = secureParameters(parameters, researchTaskDeepResearchCreateSchema);
      break;

    default:
      throw new Error(`Task not yet supported: ${params.type}`);
  }

  switch (params.executionType) {
    case ResearchTaskExecutionType.ON_DEMAND:
      break;
    case ResearchTaskExecutionType.PERIODIC:
      params = {
        ...params,
        ...secureParameters(parameters, researchTaskPeriodicCreateSchema),
      };
      break;
    case ResearchTaskExecutionType.SCHEDULED:
      params = {
        ...params,
        ...secureParameters(parameters, researchTaskScheduledCreateSchema),
      };
      break;
    default:
      throw new Error(`Execution type not supported: ${params.executionType}`);
  }

  return params;
};
